### PR TITLE
Yuhsuan/1176 pan zoom

### LINKED ISSUE #1176: additional image zoom/pan methods
Should consider to add the following image zoom or pan methods:
- [x] pan by manually setting world coordinates
- [x] zoom by manually setting an angular size
- [ ] zoom/pan by creating a box

### LINKED ISSUE #2080: Remove blueprint popover warnings in the image view settings
**Describe the bug**
Blueprint shows warnings when opening the image view settings.

**To Reproduce**
1. Open Carta
2. Open image view settings
3. Check the console

**Expected behavior**
No warnings.

**Screenshots or videos**
image

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Big Sur
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 108
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

**Additional context**

### PR DESCRIPTION
**Pull request by YuHsuan-Hwang**
**Description**
This PR is for the first two items in #1176 UI for zooming/panning and fixed #2080 remove blueprint warnings.

Changes:
 - Added methods for panning and zooming: `setCenter`, `setCenterWcs`, `zoomToSizeX`, `zoomToSizeY`, `zoomToSizeXWcs`, `zoomToSizeYWcs`
 - Update the centers of spatially matched images. They were not all updated because we only needed the center of the base image.
 - Added a new tab in the image view settings and added inputs for changing the field of view center and size of the active image in image coordinate or wcs coordinate.
 - The wcs inputs are disabled with PV images.
 - Changed the setting label width from 168px to 140px, except for the color bar panel which has longer labels.
 - Set a larger min height of the image view settings widget to avoid two scroll bars
 - Adjusted the tooltip of the Select and pan mode button. Double clicking the button opens the image view settings. If the image view settings is already opened, we close and reopen the widget so that 1. the tab is reset to Pan and Zoom 2. it is shown in front of other settings widgets

Maintenance:
 - Fixed issue 2080 by removing `placement` prop in `fontSelect` and `ColorSelect`. This avoids printing hundreds of the warnings when re-rendering frequently.
 - Added `FrameStore.pixelRatio` variable to be reused.
 - Added shared component `CoordNumericInput` to be reused for zoom and pan inputs and region dialogs (and perhaps distance measuring dialog). Can also be reused in the image fitting dialog in the future.
 - Refactored `EllipticalRegionForm` to remove duplicated code. The changes also allows us to move wcs input methods from components to stores more easily if we want to support them in scripting.
 - Rename `RegionCoordinate` to `CoordinateMode` because it’s not only used for regions.
 - Refactored `CoordinateComponent` to remove `RegionStore` dependence.

Tested that:
 - Pan and zoom methods work fine 1. with different screen devicePixelRatio 2. after exporting images with different resolution 3. with non-square images 4. with spatially matched images.
 - For spatially matched images, the input values of all the images are updated when 1. panning with drag-and-drop 2. zooming to point with mouse wheel 3. clicking the Zoom to fit button.
 - Performance of zooming and panning is not significantly worse.
 - Font and color drop downs in the settings remain at the same positions.
 - Region dialog works as usual.
 - Double-clicking the Select and pan mode button opens the image view settings with Pan and Zoom tab.

~Todo~
~Refactor other region dialogs after the annotation PR is merged~
~Disable wcs input for z-swapped image after the PR is merged~
We can leave them to future work.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [X] ZenHub estimate, milestone, and release (if needed) added
- [X] e2e test passing / ~corresponding fix added~
- [ ] changelog updated / ~no changelog update needed~
- [X] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [X] `BackendService` unchanged / ~`BackendService` changed and corresponding ICD test fix added~

### CODE REVIEW

**Comment by YuHsuan-Hwang** [comment]
Other than the two to-do items, the PR is ready for testing and reviewing.

**Comment by YuHsuan-Hwang** [comment]
new changes (also updated in the description):
* fixed the bug that the wcs fov center is not re-calculated when the wcs system is changed
* set a larger min height of the image view settings widget to avoid two scroll bars
* when the image view settings widget is already opened and we double click the toolbar button, we close and reopen the widget so that 1. the tab is reset to Pan and Zoom 2. it is shown in front of other settings widgets
* replace `RotationNumericInput` with `ImageCoordNumericInput`

**Review by kswang1029 — CHANGES_REQUESTED** [review]
No regression is observed from e2e tests 👍 . Manual tests are looking good. One minor issue: the unit of FOV size in world coordinates is sometimes not visible in the text field (mostly deg).

One UI issue: we may need to widen the settings dialog a bit to avoid showing the horizontal scroll bar (this is seen with my MBP 16")
Screen Shot 2023-01-30 at 10 14 57


One general question: how do we convert FOV size in world coordinates to image coordinates and vise versa? Wide field images are tricky in this aspect.

**Comment by kswang1029** [comment]
@YuHsuan-Hwang can turn this as a formal PR. Code review may proceed.

**Comment by YuHsuan-Hwang** [comment]
> how do we convert FOV size in world coordinates to image coordinates and vise versa? Wide field images are tricky in this aspect

@kswang1029 I apply the same strategy as in the region dialog and in the fitting result of the image fitting dialog.

**Comment by YuHsuan-Hwang** [comment]
@kswang1029 
> the unit of FOV size in world coordinates is sometimes not visible in the text field (mostly deg).

I think the issue also exists in the region dialog. We can file a new issue in the future if it turns out a common use case.

> we may need to widen the settings dialog a bit to avoid showing the horizontal scroll bar (this is seen with my MBP 16")

Please test if the new default width fixes the issue.

**Comment by kswang1029** [comment]
> @kswang1029
> 
> > the unit of FOV size in world coordinates is sometimes not visible in the text field (mostly deg).
> 
> I think the issue also exists in the region dialog. We can file a new issue in the future if it turns out a common use case.
> 
> > we may need to widen the settings dialog a bit to avoid showing the horizontal scroll bar (this is seen with my MBP 16")
> 
> Please test if the new default width fixes the issue.

I tried, we need a width of 660px to avoid the horizontal scroll bar.

**Review by kswang1029 — APPROVED** [review]
This looks good. Manual test works fine. No regression is observed from e2e tests. 

Please proceed code review.

**Review by veggiesaurus — APPROVED** [review]
code looks good to me. We can merge it once we have one more code review :+1:

**Review by crocka — APPROVED** [review]

**Pull request merged**
