### PR TITLE
Mylin/1762 add cursor info to histogram widget

### LINKED ISSUE #1762: missing cursor info in the histogram widget
Like the spatial or spectral profiler, the histogram widget should also show cursor info (pointed x and y values) at the bottom-left corner. The histogram in the render config widget does show the cursor info though.

### PR DESCRIPTION
**Pull request by acdo2002**
Fixed #1762 
I follow the spatial and spectral widget method to add the cursor information to the left bottom of the histogram widget.

### CODE REVIEW

**Review by kswang1029 — CHANGES_REQUESTED** [review]
@acdo2002 thanks for implementing the cursor info for the histogram widget. 👍 
We will need to show "Cursor: ..." only. We don't need to support "Data: ..." as it does not make any sense to show the cursor pointed pixel info there. The "Cursor: ..." part needs to show both x and y values of the histogram, such as (1.23 Jy/beam, 25 counts).

**Comment by acdo2002** [comment]
@kswang1029 I follow your suggestion, adding x(value) and y(count) values into the bottom left of the histogram, please check it.

**Review by kswang1029 — CHANGES_REQUESTED** [review]
now it works nicely and thanks for taking care of singular/plural terms. 
Just one issue I spotted: when the cursor is outside the x-range of the data, the count stays as the first or the last count. I guess this is due to binary search? In such case I think it is better to show "NaN" as counts. 


https://user-images.githubusercontent.com/20819712/152951878-4a7a67d6-21f5-4bed-96c8-46ee54a23e18.mov

**Review by kswang1029 — APPROVED** [review]
feature-wise this works nicely 👍

**Review by YuHsuan-Hwang — APPROVED** [review]

**Pull request merged**
