### PR TITLE
Jason/issue 600

### LINKED ISSUE #600: beam graphic too big
It looks to me like the ellipse in the lower left corner meant to indicate the beam size is too big.  Perhaps the beam sizes in the header are being interpreted as minor axes instead of major axes?

### PR DESCRIPTION
**Pull request by duidae**
closes #600

### CODE REVIEW

**Comment by kswang1029** [comment]
@duidae verified with a Retina display and a non-Retina display. All working good. 👍

**Comment by kswang1029** [comment]
@arusstaylor Could you check if this PR fixes the issue? 
http://carta.asiaa.sinica.edu.tw/frontend/e972f34/?socketUrl=wss://carta.asiaa.sinica.edu.tw/socketdev

**Comment by arusstaylor** [comment]
seems to be fixed in my iMac.

**Comment by kswang1029** [comment]
@arusstaylor thank you for confirmation： ）

**Review by veggiesaurus — APPROVED** [review]

**Pull request merged**
