### PR TITLE
Yuhsuan/1204 color blending enhancement

### LINKED ISSUE #1204: blending three images with R, G, and B colors
as one of the NRAO priorities.

allowing up to three images with each set to R or G or B color then blending them into one pseudo-optical image.

example image (work from Chin-Fei)
HH212-2017-composite

Requirement document:
https://docs.google.com/document/d/11lT4ZViLw95Jll1PCClxKhsWzvSF9_1caA_n7gwG4hg/edit?usp=sharing

### PR DESCRIPTION
**Pull request by YuHsuan-Hwang**
**Description**

Closes #1204. Implemented remaining features for multi color blending:

* Support saving color blending configs in workspaces
    * Save the image list index, selected layers, and alpha values.
    * When loading a workspace, create blended images after loading all images. Set selected layers and alpha values, and then reorder the images based on the image list index.
    * Note that currently the filename ("Color blending i") and the image view overlay (e.g., custom title text) are not restored.
* Added colormap set dropdown in render config widget
    * Interpolate the colormaps to the number of layers and apply to each layer. If the colormap set is a single gradient colormap, it interpolates colors along the gradient for each frame. If the colormap set is a collection of multiple colormaps, it interpolates between the indexes and selects a colormap from the collection to match the number of frames.
    * Extend options by modifying `ColorBlendingStore.ColormapSets`.
    * Added Magenta colormap.
* Shortcut for creating blending images in the file browser dialog
    * When 2-3 images are selected, Loading with RGB blending button is shown.
    * The shortcut loads the images, spatially matches each image to the reference, and append a blended image with the RGB color set.
    * When >3 images are selected, Loading with multi-color blending button is shown and the Rainbow color set will be applied.
    * If spatial matching fails, the image will not be added as a layer.
* Added buttons in the Layer column of the image list widget
   * Toggle the visibility of rasters/contours/vectors on the blended image.
   * Hiding the layers removes the entire React components. Re-render contours when the ContourViewComponent is recreated.
   * This does not affect the composed images.
* Disable saving images when necessary
   * Disable "Save Image" in file menu and the keyboard shortcut when blended image/PV preview is active.
   * If the blended image/PV preview becomes active after the save image dialog is opened, the save image panel shows “not supported” and the save button is disabled.
* Hide the render config settings button when the blended image is active
    * Hide buttons for docked and floating widgets.
* The layer number limit is set to 10 when creating a color blended image. Note that layer number after creating the image is not limited.
* Consider raster scaling matching when applying colormap set.
    * Unmatch raster scaling and reset scaling percentile when using blending shortcut in the file browser dialog.
    * In the color blending config panel, disable colormap dropdown and show a tooltip when the frame is raster scaling matched.
    * Skip raster scaling matched frames when applying the colormap set.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] GitHub Project estimate added

For the pull request:
- [x] reviewers and assignee added
- [x] GitHub Project estimate added
- [x] ~changelog updated~ / no changelog update needed
- [x] unit test added (for functions with no dependenies)
- [x] API documentation added (for public variables and methods in stores)

For dependencies:
- [x] e2e test passing / corresponding fix added / new e2e test created
- [x] ~protobuf version bumped~ / no protobuf version bumped needed
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] ~corresponding ICD test fix added (`BackendService` changed)~ / no ICD test fix needed (`BackendService` unchanged)
- [x] user manual prepared (for large new features)

### CODE REVIEW

**Review by veggiesaurus — APPROVED** [review]

**Comment by loveluthien** [comment]
The color blending function in the file browser is limited to selecting three images. How about relaxing this limit?

**Comment by YuHsuan-Hwang** [comment]
> The color blending function in the file browser is limited to selecting three images. How about relaxing this limit?

We will need to define more then three default colors, perhaps RGBCMY? The limit will become 6 in this case.

**Comment by loveluthien** [comment]
> > The color blending function in the file browser is limited to selecting three images. How about relaxing this limit?
> 
> We will need to define more then three default colors, perhaps RGBCMY? The limit will become 6 in this case.

How about just using rainbow for images n > 3 cases? If n <= 3, use RGB. Two filters blending in file opening might be useful for some users.

**Review by loveluthien — APPROVED** [review]
Good. New functions are pretty useful.

**Comment by YuHsuan-Hwang** [comment]
Updated PR description for the file browser shortcut:
* When 2-3 images are selected, Loading with RGB blending button is shown.
* When 4-7 images are selected, Loading with multi-color blending button is shown and the Rainbow color set will be applied.

**Review by kswang1029 — COMMENTED** [review]
It would be nice if we apply a similar logic to the menu "File -> Multi-Color Blending" based on the number of spatially matched images. Currently it will pick up up to three matched images only and does not apply a preset color set. How about we apply an analogous logic (ie check the number of selected images in the file browser vs check the number of spatially matched images) to that menu item as well?

**Comment by YuHsuan-Hwang** [comment]
> It would be nice if we apply a similar logic to the menu "File -> Multi-Color Blending" based on the number of spatially matched images. Currently it will pick up up to three matched images only and does not apply a preset color set. How about we apply an analogous logic (ie check the number of selected images in the file browser vs check the number of spatially matched images) to that menu item as well?

We can increase the number 3 to 10 if that's more straightforward. I set to 3 because RGB is more commonly used.
For applying a color set, might the users set the colors before creating a blended image? Their color settings will be overwritten in this case.

**Comment by kswang1029** [comment]
> > It would be nice if we apply a similar logic to the menu "File -> Multi-Color Blending" based on the number of spatially matched images. Currently it will pick up up to three matched images only and does not apply a preset color set. How about we apply an analogous logic (ie check the number of selected images in the file browser vs check the number of spatially matched images) to that menu item as well?
> 
> 
> 
> We can increase the number 3 to 10 if that's more straightforward. I set to 3 because RGB is more commonly used.
> 
> For applying a color set, might the users set the colors before creating a blended image? Their color settings will be overwritten in this case.

Let's do up to 10 for the menu.
Good point about overwriting color settings.

**Comment by YuHsuan-Hwang** [comment]
Update:
* The layer number limit is set to 10 when creating a color blended image. The snippet tutorial and tests are also adjusted.
* Note that layer number after creating the image is not limited.

**Comment by YuHsuan-Hwang** [comment]
Update: adjusting the Rainbow colorset.

**Comment by YuHsuan-Hwang** [comment]
Update:

Feature enhancement

* Added "gradient" as a type of colormap set. If the colormap set is a single gradient colormap, it interpolates colors along the gradient for each frame. If the colormap set is a collection of multiple colormaps, it interpolates between the indexes and selects a colormap from the collection to match the number of frames.
* The colormap set options can be easily extended by modifying `ColorBlendingStore.ColormapSets`.
* Changed the CMY color order to: "Magenta", "Yellow", "Cyan"

Bug fix

* Fixed failing to apply colormap set when there is only one layer.
* Adjusted colormap set dropdown design and vertically aligned the colormap blocks to the center (in both colormap dropdown and colormap set dropdown).
* Rerender dropdowns in the color blending config panel when changing the theme.

Refactoring

* Added a shared component `ColormapBlock` and moved related css code to `ColormapComponent.scss`.
* Adjusted hex code to lowercase.

**Comment by YuHsuan-Hwang** [comment]
Update:
* Consider raster scaling matching when applying colormap set.
    * Unmatch raster scaling and reset scaling percentile when using blending shortcut in the file browser dialog.
    * In the color blending config panel, disable colormap dropdown and show a tooltip when the frame is raster scaling matched.
    * Skip raster scaling matched frames when applying the colormap set.
* Removed the upper limit of the frame number for the shortcut since we can now generate different colors from the gradients.

**Review by loveluthien — APPROVED** [review]
Good job!!

**Comment by YuHsuan-Hwang** [comment]
@kswang1029  Updates:

* Bug fix: for a color blending image, when there are contours/vectors from the selected spatially matched images (but not the spatial reference), the Layer column in the Image List widget should show contours/vectors visibility toggle buttons.
* Adjusted the save image panel in the File Browser dialog to include hints for using workspace instead. Add tooltips to the Save Image in the File menu and the Save image button in the  File Browser dialog.

**Review by loveluthien — APPROVED** [review]

**Review by kswang1029 — APPROVED** [review]
nice enhancements 👍 added a few new e2e tests.

**Review by loveluthien — APPROVED** [review]

**Pull request merged**
