### PR TITLE
Icchen/1906 annoying text input in vector dialog

### LINKED ISSUE #1906: annoying text input fields in the vector rendering dialog
reported by v3 beta tests

Need a better handle of the text input fields in the vector rendering dialog. For example, if we enter 0.001 in the threshold and want to change it to 0.002 by deleting 1 and entering 2, it becomes 0 instead.

https://user-images.githubusercontent.com/20819712/177927884-d968e17b-a6f9-4f4d-a001-0659ef60a0d9.mov

### PR DESCRIPTION
**Pull request by I-Chenn**
**Description**

This PR is to resolve #1906.

The issue is related to the globally used class `SafeNumericInput`. If we 

A new prop called `onValueChanged` (note: different from the default `onValueChange` prop) is added to the `SafeNumericInput`. If `onValueChanged` prop is given when using `SafeNumericInput`, the `onBlur` and `onKeyDown` prop will automatically be adopted in the way written in `SafeNumericInput` and hence the value of the input column will be updated with `onBlur` (when move mouse out of the column) or `onKeyDown` (when press any key in the column). The result is shown below:

https://user-images.githubusercontent.com/106953609/219676114-654d8e14-d79a-4ee0-aa0f-d838c472ef60.mov

I have fixed all the Index columns in `Vector Overlay Dialog`. They are: `Threshold`, `Stokes Q Error`, `Stokes U Error`, `Line Length: Min`, `Line Length: Max`, `Bias` and `Contrast` with the usage of `onValueChanged` prop.

Nevertheless, since `SafeNumericInput` is globally used (there seems to be 185 input columns using `SafeNumericInput`) I don't know if I should fix all the input columns or not. If we need to fix all of them, I think we need to build another issue to deal with it.

**Checklist**

For linked issues (if there are):
- [X] assignee and label added
- [ ] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [X] reviewers and assignee added
- [ ] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing / corresponding fix added
- [ ] changelog updated / no changelog update needed
- [X] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [ ] `BackendService` unchanged / ~`BackendService` changed and corresponding ICD test fix added~

### CODE REVIEW

**Comment by YuHsuan-Hwang** [comment]
I prefer we fix all the UI that uses this shared component. Please change the behavior of `onValueChange` prop in `SafeNumericInput` without changing all the other components.

**Comment by I-Chenn** [comment]
@kswang1029 @YuHsuan-Hwang 
The commit bfea5e7 has fixed the issue with maintaining the usage of the `onValueChange` prop, thus all the components using `SafeNumericInput` are now fixed. The `onValueChange` prop is now used to activate the `onBlur` and `onKeyDown` prop of `NumericInput`.
The PR is available for review now.

**Comment by I-Chenn** [comment]
Made some syntax reformation in accordance with @YuHsuan-Hwang's suggestion in 7ba2bad.

**Comment by kswang1029** [comment]
there are multiple e2e test failures. Investigating...

**Comment by kswang1029** [comment]
The spinbox elsewhere in the GUI is not functional thus causing multiple e2e test failure. 

Screen Shot 2023-02-22 at 10 16 21
Screen Shot 2023-02-22 at 10 18 39

**Comment by I-Chenn** [comment]
It seems that the components using `SafeNumericInput` with `stepSize` prop set are problematic. Trying to figure out why.

**Comment by I-Chenn** [comment]
@kswang1029. The spinbox issue is fixed. Please make the e2e test again and see if there's still failure. Thanks~

**Pull request closed without merging**
