### PR TITLE
Mark/2247 Fix the blank screen problem

### LINKED ISSUE #2247: A blank screen shown when clicking X/Y profile setting button without opening images
**Describe the bug**

Not sure has anyone reported this minor bug. When starting the Carta without opening images, if we click the X/Y profile setting button, as shown in the screenshot below, a blank screen will show up. 

**To Reproduce**
1. Start the Carta and do not open any image
2. Click on X or Y profile setting button
3. Result in a blank screen

**Expected behavior**
X or Y profile setting panel should be normally shown like when we have opened images.

**Screenshots or videos**
carta-frontend-issue

**Platform info (please complete the following information):**
 - OS: macOS Ventura 
 - Browser: Chrome
 - Browser version: 116.0.5845.179 
 - Backend branch: dev, v4 release
 - Frontend branch: dev, v4 release

**Additional context**
No.

### PR DESCRIPTION
**Pull request by markccchiang**
**Description**

linked issues and companion PRs (if there are), what is implemented or fixed, how to test it, …

Closes #2247.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] e2e test passing / ~corresponding fix added~ / new e2e test created
- [x] changelog updated ~/ no changelog update needed~
- [x] ~protobuf updated to the latest dev commit /~ no protobuf update needed
- [x] `BackendService` unchanged ~/ `BackendService` changed and corresponding ICD test fix added~

### CODE REVIEW

**Comment by kswang1029** [comment]
@markccchiang please turn this into a formal PR. Code review may proceed. I will implement a new e2e test to catch this widget/dialog initialization issue.

**Review by YuHsuan-Hwang — APPROVED** [review]
Looks good. 👍

**Review by loveluthien — APPROVED** [review]
The bug has been fixed.

**Review by kswang1029 — APPROVED** [review]
tested. added new tests for GUI initialization/reset in the branch `gui_initialization`.

**Pull request merged**
