### PR TITLE
Thchang/region creating buttons in toolbar

### LINKED ISSUE #726: region creating button in toolbar
Do we want a region creating tool button in the top tool bar?  The shortcut in the popup on the image is fine,  but not intuitive.  The average user will look for a button to create a region in the upper tool bar.  Having one there is intuitive.  Not having one there is mystifying for the new user.  "How the heck do I create a region?".  

Should probably give some thought to the logic of what should be in the toolbar and what should be in the popup on the image.  One logic is to put things in the popup that change image properties in a single click on the button...  In that case the region creation tool and the coordinate change would not belong and should be moved to the top level tool bar.

Thoughts?

### PR DESCRIPTION
**Pull request by TienHao**
closes #726 
Add region creating buttons in a new group "actions" of toolbar.

### CODE REVIEW

**Review by veggiesaurus — CHANGES_REQUESTED** [review]
I think it looks better if we move the actions toolbar to the left, so that it's over the default image view location, even if the screen resolution is small: 
image


@kswang1029 we need some tooltips describing the region creation behaviour for each region type

**Comment by kswang1029** [comment]
@TienHao @veggiesaurus How does the following read?


**rectangle**
(when region creation mode is "center to corner"):
_Click-and-drag to define a region in the "center to corner" creation mode. Change the default creation mode via File->Preferences->Region->Creation mode.
Hold shift key to create a square._ 
(when region creation mode is "corner to corner"):
_Click-and-drag to define a region in the "corner to corner" creation mode. Change the default creation mode via File->Preferences->Region->Creation mode.
Hold shift key to create a square._ 

**ellipse**
(when region creation mode is "center to corner"):
_Click-and-drag to define a region in the "center to corner" creation mode. Change the default creation mode via File->Preferences->Region->Creation mode.
Hold shift key to create a circle._ 
(when region creation mode is "corner to corner"):
_Click-and-drag to define a region in the "corner to corner" creation mode. Change the default creation mode via File->Preferences->Region->Creation mode.
Hold shift key to create a circle._ 


**polygon**
_Define control points with a series of clicks. Double-click to close the loop and finish polygon creation._

**Comment by veggiesaurus** [comment]
> Change the default creation mode via File->Preferences->Region->Creation mode.

this line might be a little verbose, and look odd.

**Comment by veggiesaurus** [comment]
> > Change the default creation mode via File->Preferences->Region->Creation mode.
> 
> this line might be a little verbose, and look odd.

It's probably more important to add something like "hold" CTRL to switch to center-to-corner

**Comment by kswang1029** [comment]
@veggiesaurus My original idea is to guide users that the creation mode can be changed. If we just mention holding CTRL can switch to other mode temporarily, it still does not resolve the problem for users who are more used to corner-to-corner mode. 
I do think that long sentence is too verbose. Help needed....

**Comment by TienHao** [comment]
How about we put a small question mark on the right of the actions buttons? 
region creating button

when region creation mode is "center to corner":
The tool tips of question mark display:
_"**Center to Corner**" mode on. Change the default creation mode via File->Preferences->Region->Creation mode_

**rectangle**
_Click-and-drag to define a region._
_Hold shift key to create a square._

**ellipse**
_Click-and-drag to define a region._
_Hold shift key to create a circle._

**polygon**
_Define control points with a series of clicks. Double-click to close the loop and finish polygon creation._

**Comment by veggiesaurus** [comment]
> How about we put a small question mark on the right of the actions buttons?
> region creating button
> 
> when region creation mode is "center to corner":
> The tool tips of question mark display:
> _"**Center to Corner**" mode on. Change the default creation mode via File->Preferences->Region->Creation mode_
> 
> **rectangle**
> _Click-and-drag to define a region._
> _Hold shift key to create a square._
> 
> **ellipse**
> _Click-and-drag to define a region._
> _Hold shift key to create a circle._
> 
> **polygon**
> _Define control points with a series of clicks. Double-click to close the loop and finish polygon creation._

I think it would look odd. And generally we want the tooltip content to be clear, and not have users go looking for extra info

**Comment by veggiesaurus** [comment]
> it still does not resolve the problem for users who are more used to corner-to-corner mode.

@kswang1029 presumably that would be fixed by https://github.com/CARTAvis/carta-frontend/issues/1031 ? Although I don't think @Kechil has described the issue properly. I think she's referring to a first-time-setup wizard (that is _also_ accessible at a later stage)

**Comment by kswang1029** [comment]
@veggiesaurus @TienHao how about:

rectangle
(when region creation mode is "center to corner"):
Click-and-drag to define a region (center to corner).
Hold Ctrl to define a region (corner to corner). 
Change the default creation mode in Preferences.
Hold shift key to create a square.

rectangle
(when region creation mode is "corner to corner"):
Click-and-drag to define a region (corner to corner).
Hold Ctrl to define a region (center to corner).  
Change the default creation mode in Preferences.
Hold shift key to create a square.

ellipse
(when region creation mode is "center to corner"):
Click-and-drag to define a region (center to corner).
Hold Ctrl to define a region (corner to corner).  
Change the creation mode in Preferences.
Hold shift key to create a circle.

ellipse
(when region creation mode is "corner to corner"):
Click-and-drag to define a region (corner to corner). 
Hold Ctrl to define a region (center to corner). 
Change the creation mode in Preferences.
Hold shift key to create a circle.

polygon
Define control points with a series of clicks. Double-click to close the loop and finish polygon creation.

**Pull request merged**
