### PR TITLE
Enable cursor events on the cursor info overlay

### LINKED ISSUE #1794: Regions not selectable near the bottom of the window
A region placed close to the bottom of the image window is not selectable
(nor can I place one here). It appears to be connected with the menu list
at the bottom, but when it is collapsed there is nothing that should
prevent one from being able to place/access regions here. If that is
absolutely not possible I suggest to either block out that area or to move
the menu outside the image window. (To note, it is not pleasant not to be
able to place a region on a source found and rely on one's finding it again
when one moves the pan window to the next position - and to pan around and
lose one's settings for the search is inefficient).

### PR DESCRIPTION
**Pull request by YuHsuan-Hwang**
**Description**

Enable cursor events on the cursor info overlay and the area around the toolbar with simple css changes.

Users can pan/zoom images and create/drag regions on the grey blank area where there is no cursor info text. They can still highlight and copy the text as usual.
Same fix for the area around the toolbar. They can still hover and click toolbar buttons as usual.

Closes #1794.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [ ] ZenHub estimate, milestone, and release (if needed) added
- [x] changelog updated / ~no changelog update needed~
- [x] ~unit test added (for functions with no dependenies)~
- [x] ~API documentation added (for public variables and methods in stores)~

For dependencies:
- [x] e2e test passing / corresponding fix added / new e2e test created
- [x] ~protobuf version bumped~ / no protobuf version bumped needed
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] ~corresponding ICD test fix added (`BackendService` changed)~ / no ICD test fix needed (`BackendService` unchanged)
- [x] ~user manual prepared (for large new features)~

### CODE REVIEW

**Comment by kswang1029** [comment]
Can we apply the same trick to the toolbar? 

https://github.com/CARTAvis/carta-frontend/issues/1794

**Comment by YuHsuan-Hwang** [comment]
> Can we apply the same trick to the toolbar?
> 
> #1794

Yes. 👍 
This is also fixed.

**Review by loveluthien — APPROVED** [review]
It works well.

**Review by kswang1029 — APPROVED** [review]
Nice fix! 👍 no regression detected via e2e tests.

**Review by crocka — APPROVED** [review]

**Pull request merged**
