### PR TITLE
Yuhsuan/1397 model residual image

### PR DESCRIPTION
**Pull request by YuHsuan-Hwang**
**Description**

This PR is for the 7th and 9th items in #1397: adding progress bar dialog and appending model/residual images.
* Added two toggles in the fitting dialog to enable appending model/residual images.
* After we click the Fit button, a progress dialog is shown. The progress is updated every fitting iteration.
* Added Cancel button in the progress dialog. Message will be shown at the button after the task is canceled.
* Carta-generated PV images and model/residual images are not supported. The Fit button is disabled for these images. A simple work-around is to save and open the images. This avoids very large file ids which may break frontend tile coordinate encoding.
* Other changes: the tooltip is hidden when the Fit button is disabled.

Corresponding PRs:
https://github.com/CARTAvis/carta-backend/pull/1222
https://github.com/CARTAvis/carta-protobuf/pull/78

**Checklist**

For linked issues (if there are):
- [X] assignee and label added
- [X] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [X] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] e2e test passing / ~corresponding fix added~
- [x] changelog updated / ~no changelog update needed~
- [x] protobuf updated to the latest dev commit / ~no protobuf update needed~
- [x] ~`BackendService` unchanged~ / `BackendService` changed and corresponding ICD test fix added

### CODE REVIEW

**Comment by kswang1029** [comment]
@YuHsuan-Hwang in `AppStore.ts`, 
```
"You have been disconnected from the server. Do you want to reconnect? Please note that temporary images such as moment images or PV images generated via the GUI will be unloaded.",
```
needs a revision to include fitting model image and fitting residual image.

**Comment by YuHsuan-Hwang** [comment]
> needs a revision to include fitting model image and fitting residual image.

@kswang1029 Adjusted the reconnection alert.

**Review by veggiesaurus — APPROVED** [review]

**Review by kswang1029 — APPROVED** [review]
this looks good! no regression is observed via e2e tests.

**Review by crocka — APPROVED** [review]

**Comment by kswang1029** [comment]
@YuHsuan-Hwang confirmed the session resume fix. 👍

**Review by acdo2002 — APPROVED** [review]
The updated `BackendService.ts` has been adding into and tested with the `MessageController.ts` in the current RxJS ICD test .
Adding new ICD messages (i.e. FittingProgress) works fine with the current all tests (at lease all passed with MacOS11)
Once this issue backend/frontend/protobuf have been merged into the dev branch.
RxJS ICD can update very soon.

**Pull request merged**
