### PR TITLE
Kuanchou/2045 remove redundant close button

### PR DESCRIPTION
**Pull request by loveluthien**
**Description**

This PR is for the improvement of UI proposed in #2045 that removing the redundant "close" buttons in dialogs and widgets such as File Browser, Preferences, Contours, Vector, Snippets.  

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] e2e test passing / corresponding fix added / ~new e2e test created~
- [x] ~changelog updated~ / no changelog update needed
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] ~protobuf version bumped~ / protobuf version not bumped
- [x] `BackendService` unchanged / ~`BackendService` changed and corresponding ICD test fix added~

### CODE REVIEW

**Review by YuHsuan-Hwang — APPROVED** [review]
The changes are good. 👍

**Comment by YuHsuan-Hwang** [comment]
I think we can skip the change log since there is minor user impact.

**Review by kswang1029 — APPROVED** [review]
Looks good. In the about dialog, since close button is removed, I think we can shorten the height a bit.

Some e2e tests are modified accordingly.

**Review by crocka — APPROVED** [review]

**Comment by loveluthien** [comment]
The above dialog is adjusted.

**Comment by loveluthien** [comment]
The above dialog is adjusted for various browsers.

**Pull request merged**
