### PR TITLE
Jason/issue 265 2

### LINKED ISSUE #265: animator usability enhancement
referencing https://github.com/CARTAvis/carta-backend/issues/367

Missing features
- [x] playback mode: forward (implemented), backward, bouncing, blinking 
- [x] set start and end ranges
- [x] Adjust step for playback
- [x] display channel index as well as the corresponding frequency and velocity.

### PR DESCRIPTION
**Pull request by duidae**
closes #265

### CODE REVIEW

**Comment by kswang1029** [comment]
@duidae is it possible to show the reference frame, frequency and velocity with one per line (ie three lines)? It may look nicer and be easier to read. 

Update: suggesting the order as velocity, frequency and reference frame

**Comment by kswang1029** [comment]
@duidae I will think about how to determine a proper upper limit for the step spinbox. Apparently 5 is not sufficient. We might need to use the range slider to dynamically determine a proper upper limit. For example, if the width of the range slider is 101 channel, we may use 50 (ie width//2) as the upper limit.

**Comment by kswang1029** [comment]
@duidae regarding the upper limit for step, let’s just try 50 for now. I guess this should work mostly and is an easy solution

**Comment by duidae** [comment]
i think the upper limit can be dynamic, since it should be easy to have the frame number

**Review by kswang1029 — APPROVED** [review]
Tested with different steps with different playback modes. It works well. 👍 

Just a note here that when a step is defined, the playback sequence is defined based on the range slider. This ensures that from the 2nd loop onward, uses see _same_ set of channels in the animation. However, the 1st loop may have a different set of channels depending on the starting channel index. This is fine I think. 

The rest minor improvements are:
1) set the upper limit of step spinbox to 50.
2) display spectral info text in three lines with the following order: Velocity, Frequency, and Reference frame.

**Comment by duidae** [comment]
@kswang1029  fixed & please have a look, thanks.

**Comment by kswang1029** [comment]
Screen Shot 2020-11-03 at 4 04 01 PM
I suggest to have consistent font type for image/channel/Stokes. In addition, the spectral info should not be displayed for Stokes slider.

**Comment by duidae** [comment]
@kswang1029 Refined, please have a look, thanks.

**Comment by kswang1029** [comment]
@duidae f9ce122 looks good. The Stokes string display will be dealt with https://github.com/CARTAvis/carta-frontend/issues/1046

**Review by veggiesaurus — CHANGES_REQUESTED** [review]
this looks great. One very minor issue: this seems to break the responsive layouts, because the dropdown is slightly larger. 

image

**Comment by kswang1029** [comment]
@veggiesaurus @duidae to save some space, how about changing "frame rate" to "rate"? We could add tooltip if it is necessary. "Rate" should be already clear enough. 

ps I tried to find two icons from blueprint to represent frame rate and step for the responsive layout but I failed. -_-

**Comment by duidae** [comment]
the responsive issue is fixed, I think we dont need extra manipulations.

**Review by veggiesaurus — APPROVED** [review]

**Pull request merged**
