### PR TITLE
Jason/moment generator

### LINKED ISSUE #861: Moment map generator
- [X] 1. add tabs to spectral profiler settings panel
- [X] 2. wire up UI
- [X] 3. wire up sending message to backend
- [X] 4. wire up plotting from returned message
- [X] 5. save moment image

Add to existing spectral profile widget, or create moment generator widget/dialogue.

Requirements doc: https://docs.google.com/document/d/1RciBmqsa_bZw1vgC4J0-YSOxnlIMDQyP-MINL81MYOs/edit#heading=h.pd8c2kw8bdfy

### PR DESCRIPTION
**Pull request by duidae**
closes #861 

need companion PR for backend & protobuf.

btw, @markccchiang @veggiesaurus can we merge protobuf branch into dev first? Since moment branch in protobuf should be fixed already, and so that this frontend branch would be available to test for @kswang1029 in mix'n match. (frontend cant work properly with incorrect protobuf branch in mix'n match)

### CODE REVIEW

**Comment by kswang1029** [comment]
@duidae is it possible to show the tooltip _only_ when the generate button is disabled? We might consider to use multiple lines for the tooltip (the current way is a bit too long in one line), such as

```
To generate moment images, please ensure
1. Animation playback is stopped.
2. There is no streaming spectral profile.
```

Screen Shot 2020-07-29 at 10 08 25 AM

**Comment by duidae** [comment]
ok refined tooltip

image

**Comment by veggiesaurus** [comment]
I think streaming spectral profile might confuse users. Perhaps "spectral profile generation is complete"?

I wonder if we should use a similar styling to the the toolbar tooltips, with the first line in normal font stating that moment generation is not available and the small text below giving the specific reason why it's disabled

**Comment by duidae** [comment]
@veggiesaurus @kswang1029  is this ok?

image

**Comment by kswang1029** [comment]
@duidae looks good 👍

**Comment by duidae** [comment]
@kswang1029  @TienHao  smoothing/moments shortcuts merged, please have a look, thanks.

**Comment by kswang1029** [comment]
@duidae looking good! 👍

**Comment by veggiesaurus** [comment]
@duidae will you fix the merge conflicts in this branch, and then I'll do a final review

**Comment by duidae** [comment]
ok merged.

**Pull request merged**
