### PR TITLE
Jason/issue 884

### LINKED ISSUE #884: export profile images missing grid lines and mean and rms graphic
The green rectangular display of the mean and dotted line for the rms and the display of values are not retained when the image is exported.  And exported images are missing the outer box or gridlines.  Shots of explorted and original image below.

1578317762_sdp_l0 1375 0~1400 0MHz XMMLSS_12 ms NOSELFCAL contsub cube extendednoise hdf5-Z-profile-2020-4-17-12-20-41

profile

_Originally posted by @arusstaylor in https://github.com/CARTAvis/carta-frontend/issues/883#issuecomment-615411562_

### PR DESCRIPTION
**Pull request by duidae**
closes #884

### CODE REVIEW

**Review by kswang1029 — CHANGES_REQUESTED** [review]
check deviceRatio? Following are generated with a Retina display. It works fine with a non-retina display.

HD163296_C18O_2-1 fits-Z-profile-2020-11-10-10-46-0


HD163296_C18O_2-1 fits-X-profile-2020-11-10-10-45-18

**Comment by duidae** [comment]
@kswang1029  thanks for spotting, please help check 4c5806a to see if it is fixed or not.

**Comment by kswang1029** [comment]
@duidae yes now with a Retina display, it works properly. 

I found a weird thing in 4c5806a (seen with Chrome), however. There are additional lines on screen but not in the png. There are no such lines in 
3d9c7ee.
Screen Shot 2020-11-11 at 10 23 26 AM

could you have another look?

**Comment by duidae** [comment]
@kswang1029 fixed, please have a look, thanks.

**Review by kswang1029 — APPROVED** [review]
Tested with retina and non-retina display. All working well. 👍

**Review by veggiesaurus — APPROVED** [review]

**Pull request merged**
