### PR TITLE
Jason/backport refine check

### PR DESCRIPTION
**Pull request by duidae**
backport PR for #827 , please have a look & test, thanks!

### CODE REVIEW

**Comment by veggiesaurus** [comment]
looks fine to me. Can merge once @kswang1029 tests.

**Comment by kswang1029** [comment]
I tried with cubes
with CTYPE3 = XYZ and CUNIT3 = Hz (working)
with CTYPE4 = XYZ and CUNIT4 = Hz, and CTYPE3 = STOKES and CUNIT3 = ' ' (backend does not return headers and provides an error message)
with CTYPE3 = XYZ and CUNIT3 = GigaHertz (backend does not return headers and provides an error message)

For the frontend part I think it is good to go. Now the question is do we want to support this kind of exception in the backend header parser?

**Comment by veggiesaurus** [comment]
> I tried with cubes
> with CTYPE3 = XYZ and CUNIT3 = Hz (working)
> with CTYPE4 = XYZ and CUNIT4 = Hz, and CTYPE3 = STOKES and CUNIT3 = ' ' (backend does not return headers and provides an error message)
> with CTYPE3 = XYZ and CUNIT3 = GigaHertz (backend does not return headers and provides an error message)
> 
> For the frontend part I think it is good to go. Now the question is do we want to support this kind of exception in the backend header parser?

Hmm, that's odd. Why would it strip those out?

**Comment by kswang1029** [comment]
backend says:
"Problem loading image: cannot determine coordinate axes from incomplete header. Select another file from the folder."

and the headers:
SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                  -32 / array data type                                
NAXIS   =                    4 / number of array dimensions                     
NAXIS1  =                   64                                                  
NAXIS2  =                   64                                                  
NAXIS3  =                    4                                                  
NAXIS4  =                    4                                                  
EXTEND  =                    T                                                  
BSCALE  =                  1.0 / PHYSICAL = PIXEL*BSCALE + BZERO                
BZERO   =                  0.0                                                  
BMAJ    =   4.180019088465E-05                                                  
BMIN    =   3.012913555345E-05                                                  
BPA     =       11.51531397762                                                  
BTYPE   = 'intensity'                                                           
BUNIT   = 'Jy/beam '                                                            
RADESYS = 'ICRS    '                                                            
EQUINOX =               2000.0                                                  
LONPOLE =                180.0                                                  
LATPOLE =       17.98947222223                                                  
CTYPE1  = 'RA---SIN'                                                            
CRVAL1  =    93.22416666661999                                                  
CDELT1  =  -8.333333333333E-06                                                  
CRPIX1  =               320.75                                                  
CUNIT1  = 'deg     '                                                            
CTYPE2  = 'DEC--SIN'                                                            
CRVAL2  =       17.98947222223                                                  
CDELT2  =   8.333333333333E-06                                                  
CRPIX2  =               320.75                                                  
CUNIT2  = 'deg     '                                                            
CTYPE3  = 'XYZ     '                                                            
CRVAL3  =       100000000000.0                                                  
CDELT3  =             100000.0                                                  
CRPIX3  =                  1.0                                                  
CUNIT3  = 'GigaHertz'                                                           
CTYPE4  = 'Stokes  '                                                            
CRVAL4  =                  1.0                                                  
CDELT4  =                  1.0                                                  
CRPIX4  =                  1.0                                                  
CUNIT4  = ''                                                                    
RESTFRQ =       100000000000.0 / Rest Frequency (Hz)                            
SPECSYS = 'LSRK    '           / Spectral reference frame                       
OBSGEO-X=       2225142.180269                                                  
OBSGEO-Y=      -5440307.370349                                                  
OBSGEO-Z=      -2481029.851874                                                  
VELREF  =                  257 / 1 LSR, 2 HEL, 3 OBS, +256 Radio                
TIMESYS = 'UTC     '                                                            
OBSRA   =    93.22416666661999                                                  
OBSDEC  =       17.98947222223                                                  
TELESCOP= 'ALMA    '                                                            
END

**Comment by veggiesaurus** [comment]
> backend says:
> "Problem loading image: cannot determine coordinate axes from incomplete header. Select another file from the folder."
> 
> and the headers:
> SIMPLE = T / conforms to FITS standard
> BITPIX = -32 / array data type
> NAXIS = 4 / number of array dimensions
> NAXIS1 = 64
> NAXIS2 = 64
> NAXIS3 = 4
> NAXIS4 = 4
> EXTEND = T
> BSCALE = 1.0 / PHYSICAL = PIXEL*BSCALE + BZERO
> BZERO = 0.0
> BMAJ = 4.180019088465E-05
> BMIN = 3.012913555345E-05
> BPA = 11.51531397762
> BTYPE = 'intensity'
> BUNIT = 'Jy/beam '
> RADESYS = 'ICRS '
> EQUINOX = 2000.0
> LONPOLE = 180.0
> LATPOLE = 17.98947222223
> CTYPE1 = 'RA---SIN'
> CRVAL1 = 93.22416666661999
> CDELT1 = -8.333333333333E-06
> CRPIX1 = 320.75
> CUNIT1 = 'deg '
> CTYPE2 = 'DEC--SIN'
> CRVAL2 = 17.98947222223
> CDELT2 = 8.333333333333E-06
> CRPIX2 = 320.75
> CUNIT2 = 'deg '
> CTYPE3 = 'XYZ '
> CRVAL3 = 100000000000.0
> CDELT3 = 100000.0
> CRPIX3 = 1.0
> CUNIT3 = 'GigaHertz'
> CTYPE4 = 'Stokes '
> CRVAL4 = 1.0
> CDELT4 = 1.0
> CRPIX4 = 1.0
> CUNIT4 = ''
> RESTFRQ = 100000000000.0 / Rest Frequency (Hz)
> SPECSYS = 'LSRK ' / Spectral reference frame
> OBSGEO-X= 2225142.180269
> OBSGEO-Y= -5440307.370349
> OBSGEO-Z= -2481029.851874
> VELREF = 257 / 1 LSR, 2 HEL, 3 OBS, +256 Radio
> TIMESYS = 'UTC '
> OBSRA = 93.22416666661999
> OBSDEC = 17.98947222223
> TELESCOP= 'ALMA '
> END

@pford any idea what that would happen?

**Comment by pford** [comment]
I am not sure why the second dataset fails if the first succeeds. For the third dataset, I suspect it's not happy with "GigaHertz"; casacore Quantity definitely does not know this unit string or "Hertz"; "Hz", "GHz" are ok.  The FITS standard lists Hz as the unit with an optional 1-char prefix.

The casacore CoordinateSystem determines coordinate types for the axes (Direction, Linear, Quality, Spectral, Stokes, Tabular) with pixel axes assigned to each coordinate so that it can convert between pixel and world coordinates.  A typical 4D image has a DirectionCoordinate with 2 pixel axes, a SpectralCoordinate with 1 pixel axis, and a StokesCoordinate with 1 pixel axis, therefore counting the pixel axes in CoordinateSystem::nPixelAxes() = 4.  The backend compares the shape of the data to nPixelAxes( ) and throws the "incomplete header" error when they are not equal.

If you point me to the two failing datasets I can give a more specific answer.

**Comment by kswang1029** [comment]
@pford here are the examples
[tmp.zip](https://github.com/CARTAvis/carta-frontend/files/4378653/tmp.zip)

only the first one can be understood by casacore.

**Comment by veggiesaurus** [comment]
@kswang1029 shall we merge this frontend fix in the mean time?

**Comment by kswang1029** [comment]
Yes, please. This frontend fix is ready to go.

**Pull request merged**
