### PR TITLE
Jason/issue 1444

### LINKED ISSUE #1444: label in region dropdown menus of the spectral profiler and moment generator out of sync
When we change region in the moment generator, the spectral profile data get updated in the spectral profiler as expected. However the label does not get updated. @duidae could you help to have a look for v2.0 final?

https://user-images.githubusercontent.com/20819712/118429151-97882900-b703-11eb-984c-e1d6f60c8c9a.mp4

### PR DESCRIPTION
**Pull request by duidae**
closes #1444 

P.S. image selection(image drop down in moment tab) still needs to trigger frame change in spectral profiler because range values of moment are calculated from the selected image, or users will get weird range values from the unmatched frame during range selection.

### CODE REVIEW

**Review by kswang1029 — APPROVED** [review]
👍

**Comment by veggiesaurus** [comment]
The one issue I have is that its not possible to generate a moment map for the entire image if you've got a region selected, even by using the dropdown. Shouldn't there be an "image" entry as well? I guess this is out of the scope of the PR though, and a separate issue

**Comment by veggiesaurus** [comment]
image

The question mark icon as a home for a tooltip seems out of place to me. Do we use this approach anywhere else in the UI?

**Comment by duidae** [comment]
> image
> 
> The question mark icon as a home for a tooltip seems out of place to me. Do we use this approach anywhere else in the UI?

yeah I got confused with previous implementation (dropdown did not include `image` option) as well, the question mark is to clarify how to generate a moment map for the entire image, which was implicit previously.

**Comment by veggiesaurus** [comment]
> > image
> > The question mark icon as a home for a tooltip seems out of place to me. Do we use this approach anywhere else in the UI?
> 
> yeah I got confused with previous implementation (dropdown did not include `image` option) as well, the question mark is to clarify how to generate a moment map for the entire image, which was implicit previously.

But why not put the tooltip on the dropdown instead? Or only show it when the selected region is "active". It's not an approach we've used elsewhere. 

If we do stick with the icon, then we should at least make its intent "info" instead of "warning"

**Comment by duidae** [comment]
> The one issue I have is that its not possible to generate a moment map for the entire image if you've got a region selected, even by using the dropdown. Shouldn't there be an "image" entry as well? I guess this is out of the scope of the PR though, and a separate issue

the major ambiguity is from:
1. if current region is 'cursor', generate the moment map of whole image, but point regions are not selectable in the dropdown in moment tab, previous implementation solved this by using the 'Active' option.
2. the 'Active' option is to provide a convenient way for region selection.
3. and kind of weird to append 'Image' option because 'Active' option and 'Image' option create duplication when region is cursor.

therefore the question mark tool tip comes out for fixing this ambiguity. And the text in parentheses for region is also to clarify the ambiguity. can also place the tooltip to the dropdown if we think it's obvious enough.

**Comment by veggiesaurus** [comment]
@kswang1029 suggests we remove the tooltip entirely

**Comment by duidae** [comment]
> @kswang1029 suggests we remove the tooltip entirely

changed to 
image


@kswang1029  it's the easiest way for implementation, but will this not confuse user (just like @veggiesaurus and me in the beginning)?

**Comment by kswang1029** [comment]
the text label after "Region" is clear enough I think. ok to have a tooltip with the dropdown if you prefer.

**Comment by veggiesaurus** [comment]
> and kind of weird to append 'Image' option because 'Active' option and 'Image' option create duplication when region is cursor.

This is the approach we take with histograms and stats, so doing so would at least be consistent

**Comment by duidae** [comment]
image

@veggiesaurus @kswang1029 added image option, please have a look, thanks.

**Review by kswang1029 — APPROVED** [review]

**Review by veggiesaurus — APPROVED** [review]

**Pull request merged**
