### PR TITLE
Add layer-list to preset layouts

### LINKED ISSUE #772: adding the new layer widget to preset layouts
As CARTA can do spatial and spectral matching of images, it would be good to have the layer widget enabled in all preset layouts. The other purpose of doing so is to use this layer widget to guide and train users to get used to the "match" feature in v1.3.

Default
default

Cube view
cube_view

Cube analysis
cube_analysis

Continuum analysis
continuum_analysis

@duidae Could you help quickly for v1.3?

### PR DESCRIPTION
**Pull request by duidae**
closes #772

### CODE REVIEW

**Comment by kswang1029** [comment]
Looks good. The table somehow is not displayed properly? We can deal with it in other issue.

**Comment by duidae** [comment]
yeah the file name & index is overlapped, looking into it now

**Comment by duidae** [comment]
@veggiesaurus  @kswang1029  I suggest we don't merge this for beta, since layer list table in docked widget still does not work properly

**Comment by veggiesaurus** [comment]
> @veggiesaurus @kswang1029 I suggest we don't merge this for beta, since layer list table in docked widget still does not work properly

fixed :+1: Merging this in now

**Comment by duidae** [comment]
@veggiesaurus really brilliant :joy:

**Review by veggiesaurus — APPROVED** [review]

**Pull request merged**
