### PR TITLE
Jrhosk/1837 optional spectral profiler info

### PR DESCRIPTION
**Pull request by jrhosk**
The option for an additional cursor coordinate has been added to the spectral profile. The user can enable the option for a secondary axis cursor display in the spectral profile settings as Settings > Styling > Show Secondary Info. The coordinate can be set as Settings > Conversion > Coordinate(2).

image

The additional coordinate information is displayed in the bottom-right corner of the spectral profile window.

### CODE REVIEW

**Review by kswang1029 — CHANGES_REQUESTED** [review]
@jrhosk this is good!
Could you set the displayed number of decimals "smart"? Based on my test, adjacent channels may have identical displayed value so we cannot tell the differences. 

https://user-images.githubusercontent.com/20819712/167056223-80db3c11-048f-4765-b1d4-7aa62caa928e.mov

Also could you add "channel" too? This would be just the array index I suppose?

**Comment by jrhosk** [comment]
> 

I have made changes to the way the decimal precision is computed, hopefully it is working as expected now. Things looked good in my quick testing.

**Review by kswang1029 — CHANGES_REQUESTED** [review]
@jrhosk Could you check the performance while zooming in the spectral profile (with the default setup where the 2nd spectral info is disabled)? In v3b2 for example, when zooming in with mouse wheel, it is "smooth" and we can observe en route zoom levels. With the current branch, it is "jumpy" and we cannot see the en route zoom levels.

**Comment by jrhosk** [comment]
> @jrhosk Could you check the performance while zooming in the spectral profile (with the default setup where the 2nd spectral info is disabled)? In v3b2 for example, when zooming in with mouse wheel, it is "smooth" and we can observe en route zoom levels. With the current branch, it is "jumpy" and we cannot see the en route zoom levels.

Hi @kswang1029 I can't recreate the problem. It seems smooth to me and I had another set of eyes look at it here in the office and they didn't see any jumpiness either. I tried a couple coordinate combinations as well. I'll make sure the branch is up-to-date.

**Comment by kswang1029** [comment]
@jrhosk could you try a cube with lots channels? (eg 2000 in my test case).

With v3b2, we see (no 2nd info enabled)

https://user-images.githubusercontent.com/20819712/167643579-01b22394-7eec-4545-8c9e-06f98f87740b.mov

with this branch we see (no 2nd info enabled)

https://user-images.githubusercontent.com/20819712/167643693-13cb6c7f-c8ad-47e2-a748-1d471c411131.mov

Do you recalculate the conversion for every throttled zoom actions?

**Comment by kswang1029** [comment]
@jrhosk please try this test image https://drive.google.com/file/d/1ls7rSkcAcgk8aruvKwIktGyNCq3BLhRE/view?usp=sharing (warning: 28 GB)

Another way to spot the performance issue is when we move cursor around in the profile plot, there is a grey vertical marker tracing the cursor movement. It should catch up the cursor movement easily but in this branch it takes time to catch up the cursor movement (that's why I speculate the conversion is triggered for every throttled zoom levels.)

**Comment by jrhosk** [comment]
> @jrhosk please try this test image https://drive.google.com/file/d/1ls7rSkcAcgk8aruvKwIktGyNCq3BLhRE/view?usp=sharing (warning: 28 GB)
> 
> Another way to spot the performance issue is when we move cursor around in the profile plot, there is a grey vertical marker tracing the cursor movement. It should catch up the cursor movement easily but in this branch it takes time to catch up the cursor movement (that's why I speculate the conversion is triggered for every throttled zoom levels.)

@kswang1029 As far as I can tell the issue is with the coordinate conversion section. Every time the cursor is moved or anything is updated it has to do the coordinate conversion of the data. I'll think about how to do this in a better way but in case you have an idea I will post the code section below.

```
if (this.widgetStore.spectralAxisVisibleSecondary){
                const optionalXUnit = this.frame.spectralUnitSecondary;
                const optConverted = this.calculateFormattedValues(optional);

                if (this.frame.spectralType === SpectralType.CHANNEL) {
                    const nativeCoord = this.findNativeCoordinateValues(parseInt(cursorXValue.toFixed()));
                    var cursorXOpt = AST.transformSpectralPoint(this.frame.returnSpectralFrame(), SpectralType.FREQ, SpectralUnit.GHZ, this.frame.spectralSystem, nativeCoord, false);
                    cursorXOpt = AST.transformSpectralPoint(this.frame.returnSpectralFrame(), this.frame.spectralTypeSecondary, this.frame.spectralUnitSecondary, this.frame.spectralSystem, nativeCoord);
                    nearestOpt = binarySearchByX(optConverted, cursorXOpt);
                } else {
                    const nativeCoord = AST.transformSpectralPoint(this.frame.returnSpectralFrame(), this.frame.spectralType, this.frame.spectralUnit, this.frame.spectralSystem, cursorXValue, false);
                    const cursorXOpt = AST.transformSpectralPoint(this.frame.returnSpectralFrame(), this.frame.spectralTypeSecondary, this.frame.spectralUnitSecondary, this.frame.spectralSystem, nativeCoord);

                    nearestOpt = binarySearchByX(optConverted, cursorXOpt);
                }
                const optionalXStr = this.precisionFormatting(nearestOpt, optConverted);
            
                const xLabel =
                    cursorXUnit === "Channel"
                        ? `Channel ${toFixed(nearest.point.x)}${optionalXStr ? `, ${optionalXStr} ${optionalXUnit}` : ""}`
                        : `${floatXStr}${cursorXUnit ? ` ${cursorXUnit}` : ""}${optionalXStr ? `, ${optionalXStr} ${optionalXUnit}` : ""}`;
                cursorInfoString = `(${xLabel}, ${toExponential(nearest.point.y, 2)})`;
```

Seems like the first step would be to only convert the input data once for each time the secondary coordinate value is set and just adjust the precision thereafter. I'll see what I can do.

**Comment by jrhosk** [comment]
I have pushed changes that should fix the optimization issues. Let me know if there more issues.

**Comment by kswang1029** [comment]
@jrhosk Performance-wise it is smooth now. 👍 

could you try the case when the bottom axis is channel and the 2nd convention is velocity? In this case, I see incorrect values ~ the speed of light. If we switch to frequency (value incorrect too), then the frontend may crash (happened to me few times).


https://user-images.githubusercontent.com/20819712/168517698-d8e66e16-183f-4c6e-98bb-926c063d40b9.mov

**Comment by jrhosk** [comment]
> @jrhosk Performance-wise it is smooth now. +1
> 
> could you try the case when the bottom axis is channel and the 2nd convention is velocity? In this case, I see incorrect values ~ the speed of light. If we switch to frequency (value incorrect too), then the frontend may crash (happened to me few times).
> 
>  Screen.Recording.2022-05-16.at.11.59.56.mov

This should be fixed now.

**Comment by kswang1029** [comment]
@jrhosk uh, what happened?

**Comment by jrhosk** [comment]
Yu asked me to start over with a completely fresh to be sure my branch was even or close to even with dev. We discussed come changes she wanted to make to how I had structured things and I am now finishing up the new branch. I deleted this one and replaced it for that reason. I think I should be done next week and ready for you to test it works the same as before or better.

**Comment by kswang1029** [comment]
@jrhosk ok, thanks for the explanations. 🙂

**Pull request closed without merging**
