### PR TITLE
migrating from incorrect async actions to flows

### LINKED ISSUE #1889: Use flow functions instead of async/promises for async actions
We should consistently use the `@flow` (and `@flow.bound`) decorator instead of async functions and `runInAction()` wrappers when we're writing asynchronous actions. See [here](https://mobx.js.org/actions.html#using-flow-instead-of-async--await-) for details. The changes are generally as simple as:
- switching from `@action fnName(params)` to `@flow.bound *fnName(params)`
- switching any `await` keywords to `yield`

For example, the change would look like this for `closeFile`:

```typescript
    @action closeFile = async (frame: FrameStore, confirmClose: boolean = true) => {
        if (!frame) {
            return;
        }
        // Display confirmation if image has secondary images
        const secondaries = frame.secondarySpatialImages.concat(frame.secondarySpectralImages).filter(distinct);
        const numSecondaries = secondaries.length;

        if (confirmClose && numSecondaries) {
            const confirmed = await this.alertStore.showInteractiveAlert(`${numSecondaries} image${numSecondaries > 1 ? "s that are" : " that is"} matched to this image will be unmatched.`);
            if (confirmed) {
                this.removeFrame(frame);
            }
        } else {
            this.removeFrame(frame);
        }

        this.widgetsStore.updateImageWidgetTitle(this.layoutStore.dockedLayout);
    };
```
to 

```typescript
    @flow.bound *closeFile(frame: FrameStore, confirmClose: boolean = true) {
        if (!frame) {
            return;
        }
        // Display confirmation if image has secondary images
        const secondaries = frame.secondarySpatialImages.concat(frame.secondarySpectralImages).filter(distinct);
        const numSecondaries = secondaries.length;

        if (confirmClose && numSecondaries) {
            const confirmed = yield this.alertStore.showInteractiveAlert(`${numSecondaries} image${numSecondaries > 1 ? "s that are" : " that is"} matched to this image will be unmatched.`);
            if (confirmed) {
                this.removeFrame(frame);
            }
        } else {
            this.removeFrame(frame);
        }

        this.widgetsStore.updateImageWidgetTitle(this.layoutStore.dockedLayout);
    }
```

note that the arrow function is not needed when using `@flow.bound`

### PR DESCRIPTION
**Pull request by veggiesaurus**
**Description**
This PR migrates incorrectly applied `async` `@action` functions to `@flow` instead. Closes #1889.

**Checklist**
- [x] ~~changelog updated~~ / no changelog update needed
- [x] e2e test passing / ~~added corresponding fix~~
- [x] ~~protobuf updated to the latest dev commit~~ / no protobuf update needed

### CODE REVIEW

**Comment by veggiesaurus** [comment]
this is mostly done. I think the main issue will be e2e / manual testing for @kswang1029

**Comment by kswang1029** [comment]
@veggiesaurus e2e test is done. All passing. Once this becomes formal PR I will run the tests again.

**Review by YuHsuan-Hwang — COMMENTED** [review]
https://github.com/CARTAvis/carta-frontend/pull/1973/files#diff-0b237f54e5ccefd37b82a30bf7d343b3f504496cb63ead79984ffba62d00b2e7R616

`appendFile` also need changes. Or perhaps we don't need `@action` for this function?

**Review by YuHsuan-Hwang — APPROVED** [review]

**Review by kswang1029 — APPROVED** [review]
all e2e tests are passing. Based on the changed files I tried some manual tests and don't see abnormal behaviors as far as I can tell.

**Pull request merged**
