### PR TITLE
Angus/1854 vector line width

### LINKED ISSUE #1854: inconsistent vector line width observed on spatially matched images
This is observed in v3-beta3 which I thought this issue was fixed during the implementation stage 🤔

Screen Shot 2022-05-17 at 10 20 07

@veggiesaurus could this be introduced from the colormap control map fix?

### PR DESCRIPTION
**Pull request by veggiesaurus**
**Description**
Closes #1854. It was actually the feather width, rather than the line thickness :facepalm: That's why it only showed up in extreme cases (where `featherWidth * relativeScale ~ lineThickness`)

(also reverts erroneous [commit](https://github.com/CARTAvis/carta-frontend/commit/a244aa7ccf3ab649c8c8e28fbed078adae3f0350)) 

**Checklist**
- [ ] changelog updated / no changelog update needed
- [ ] e2e test passing / ~~added corresponding fix~~
- [ ] ~~protobuf updated to the latest dev commit~~ / no protobuf update needed

### CODE REVIEW

**Review by kswang1029 — CHANGES_REQUESTED** [review]
@veggiesaurus the issue persists. The black vectors are generated with the 1024 image as the data source, while the green vectors are with the 128 image.

Screen Shot 2022-08-05 at 17 36 01

**Comment by veggiesaurus** [comment]
> @veggiesaurus the issue persists. The black vectors are generated with the 1024 image as the data source, while the green vectors are with the 128 image.
> 
> Screen Shot 2022-08-05 at 17 36 01

@kswang1029 Isn't this the expected behaviour? previously the vectors were _different_ thicknesses when rendered on different frames. In this case, they are the same.

The thickness being related to the pixel size seems like a different issue to me :thinking:

**Comment by veggiesaurus** [comment]
@kswang1029 I've modified this, please re-review. I think this handles the other issue as well.
cluster_04096 fits-cluster_00128 fits-image-2022-08-05-12-08-01

**Review by kswang1029 — APPROVED** [review]
@veggiesaurus I have repeated my test with two images having very different pixel sizes. Tried to set each as a spatial matching reference and generated vector overlay using each image as data source. Now the line width of vector overlay is rendered corrected. I also tried block overlay and it works normally. 

All e2e tests are passing except the changes due to https://github.com/CARTAvis/carta-frontend/pull/1923 which has been merged to dev.

**Review by YuHsuan-Hwang — APPROVED** [review]

**Pull request merged**
