### PR TITLE
Thchang / implementing precise wcs axis in spatial profilers

### LINKED ISSUE #1319: world coordinate offset in the spatial profiler
Please refer to the following video and focus on RA=13:30:00.00. The cursor stays as RA=13:30:00.00 while zooming and the red vertical line should stay at RA=13:30:00.00. However, there is offset at different zoom levels. 
In addition, at high zoom level, there seems to be an 1-pixel offset (due to the legacy 0-index/1-index issue?).

https://user-images.githubusercontent.com/20819712/108473853-8a58cb00-72c9-11eb-8e7e-b01c65c67d3c.mp4

### PR DESCRIPTION
**Pull request by TienHao**
**Description**
implemented precise wcs axis in spatial profiler:
- The previous wcs value could have a small offset in the spatial profile. The showing ticks/grids were selected by pixel values(eg._60, 70..._) at first, and were transformed into wcs values(eg. _0:05:15.59xxx, 0:05:15.69xxx..._) by AST. After rounding the wcs values, the rounded wcs values(eg. _0:05:15.6, 0:05:15.7..._) was displayed at the unrounded position, resulting the offset.
- The new method calculates the needed wcs ticks/grids at first, and than transforms the wcs value into pixel values. And displays the wcs values ticks/grids at the unrounded transformed pixel values.

https://user-images.githubusercontent.com/20379662/183001350-3fb8b6dd-6f7d-49b5-927e-187364203b04.mov

**Checklist**
- [ ] changelog updated / no changelog update needed
- [ ] e2e test passing / ~~added corresponding fix~~
- [x] ~~protobuf updated to the latest dev commit~~ / no protobuf update needed

### CODE REVIEW

**Comment by kswang1029** [comment]
@TienHao I suggest we improve the following:
1) when "Show WCS Axis" toggle is enabled, disable the upper x ticks.
2) change the green line to the "gray" color same as the grid lines and change the green world coordinates to the "gary" color same as the x-tick values.
3) actually, if now we can place the "green" lines plus labels in any locations, can we just place them just on top of the original vertical grid lines? Then we don't show the green lines but we show the custom "green" labels instead. We would need to skip some labels if it is too crowded.

**Comment by kswang1029** [comment]
currently all e2e tests are passing. I will re-run all tests again once another revision is made and check the checkbox.

**Comment by YuHsuan-Hwang** [comment]
Not sure if this is possible, but I personally prefer we have "secondary ticks" instead of "secondary grids." It may be easier to distinguish things when everything is in gray color.

image

**Comment by veggiesaurus** [comment]
> Not sure if this is possible, but I personally prefer we have "secondary ticks" instead of "secondary grids." It may be easier to distinguish things when everything is in gray color.
> 
> image

I agree. It's quite confusing with two grids

**Comment by kswang1029** [comment]
@TienHao when we disable "Show WCS Axis", shall we turn off the upper tick values?

Screen Shot 2022-08-05 at 08 55 09

**Comment by TienHao** [comment]
> @TienHao when we disable "Show WCS Axis", shall we turn off the upper tick values?

@kswang1029 : I have changed it. Now It turns off upper x value ticks and wcs grids when we disable "Show WCS Axis", and will always show x value grids in the profile.

**Comment by YuHsuan-Hwang** [comment]
The secondary tick design looks really nice 👍 

I found some issues with wide field images:
The ticks are not showing with zoom to fit:
image

In hms format (FK5), the ticks become too close and the plot width sometimes changes:
image
image

**Comment by kswang1029** [comment]
@TienHao @YuHsuan-Hwang should this PR be closed due to the new PR https://github.com/CARTAvis/carta-frontend/pull/2032?

**Comment by TienHao** [comment]
Yes, this one should be closed for now.

**Pull request closed without merging**
