### PR TITLE
carli/1989_cannot_pan_when_change_mode

### LINKED ISSUE #1989: cannot pan or zoom image if catalog selection button is enabled and we change image view modes
**Describe the bug**

When the catalog selection button is enabled and if we switch from the multi-panel mode to the single-panel mode and change it back to multi-panel mode without leaving the catalog selection mode, after we click the pan button we cannot pan/zoom images.

**To Reproduce**
1. load two images and have them spatially matched and viewed in the multi-panel view mode
2. load a catalog file and enable catalog image overlay
3. in one image, enable catalog selection and click on a source
4. switch to single-panel mode and click another source
5. switch back to the multi-panel mode
6. click the pan button to leave the catalog selection mode
7. try to zoom/pan images and we should see the issue

**Expected behavior**
When the pan button is enabled, we should be able to pan/zoom images in the above scenario. 

**Screenshots or videos**

[Screencast from 08-29-2022 03:15:11 PM.webm](https://user-images.githubusercontent.com/20819712/187145053-fc84fd43-f981-490e-9148-d38b8d3bd4c2.webm)

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: ubuntu 22.04
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 104
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

**Additional context**

### PR DESCRIPTION
**Pull request by crocka**
**Description**

The issue is caused by the `docked` props of the `RegionViewComponent` in the `ImagePanelComponent`. If the `docked` props is true, the image viewer works as expected. If the `docked` props is false, the image viewer cannot zoom or pan, or even create region or distance measurement curve. The `docked` props is dependent on` AppStore.Instance.activeLayer`, which is saved as a `readonly` attribute in `ImagePanelComponent`. The `activeLayer` attribute is initialised when the `ImagePanelComponent` is instantiated. When the user sets the image panel mode to single panel, and switches back to multi panel view, the `ImagePanelComponent` object of the hidden frame is instantiated, and the `activeLayer` attribute is set to `AppStore.Instance.activeLayer` at that instance in time. For instance, when the user set to single panel mode, and switches the `activeLayer` to catalog selection, and returns to the multi panel mode. The `activeLayer` attribute of the `ImagePanelComponent` of the hidden frame is initialised to catalog selection. The problem is that since the `AppStore.Instance.activeLayer` is set to a `readonly` attribute, further changes in `AppStore.Instance.activeLayer` would not affect the `activeLayer` attribute of the `ImagePanelComponent`. Consequently, the frame stays at catalog selection mode and the `docked` props of the `RegionViewComponent` stays false. The simple fix is to use `AppStore.Intance.activeLayer` directly in the `ImagePanelComponent`. The PR fixed #1989.

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] e2e test passing / ~corresponding fix added~
- [x] ~~changelog updated~~ / no changelog update needed
- [x] ~~protobuf updated to the latest dev commit~~ / no protobuf update needed
- [x] `BackendService` unchanged / ~~`BackendService` changed and corresponding ICD test fix added~~

### CODE REVIEW

**Review by kswang1029 — APPROVED** [review]
this looks good. No regression is seen from e2e tests. 👍

**Review by YuHsuan-Hwang — APPROVED** [review]
Is this a regression after the release?

**Comment by kswang1029** [comment]
> Is this a regression after the release?

unfortunately this bug exists in the v3-stable too.

**Comment by YuHsuan-Hwang** [comment]
> unfortunately this bug exists in the v3-stable too.

Ok, thanks for checking. @crocka Please update the change log because it exists in the release, thanks.

**Pull request merged**
