### PR TITLE
Angus/jsdoc

### PR DESCRIPTION
**Pull request by veggiesaurus**
Initial work at adding JSDoc / TypeDoc comments to actions. But this then spun off into a much larger issue of:
- Improving the "debug execution" dialog to execute actual code
- Add syntax highlighting to the dialog
- Migrate all 1-to-1 responses from requests to `Promise<T>` instead of `Observable<T>`, in order to use the `async/await` pattern

Scripting in action:

https://user-images.githubusercontent.com/592504/121241090-52d35600-c89b-11eb-8163-fed8afcfd863.mp4

edit: requires `angus/snippets_api` backend branch for full functionality

### CODE REVIEW

**Comment by kswang1029** [comment]
found an issue related to moment generator which does not exist in release 2.0.
To reproduce:
1) load HD163296_CO_2_1.fits
2) generate a moment 0 image
3) use the image dropdown from the moment tab to select HD163296_CO_2_1.fits
4) we should see the moment generator progress popup shows up and hangs there forever.

**Comment by veggiesaurus** [comment]
> found an issue related to moment generator which does not exist in release 2.0.
> To reproduce:
> 
> 1. load HD163296_CO_2_1.fits
> 2. generate a moment 0 image
> 3. use the image dropdown from the moment tab to select HD163296_CO_2_1.fits
> 4. we should see the moment generator progress popup shows up and hangs there forever.

Can you check if it exists in `dev`?

**Comment by kswang1029** [comment]
> > found an issue related to moment generator which does not exist in release 2.0.
> > To reproduce:
> > 
> > 1. load HD163296_CO_2_1.fits
> > 2. generate a moment 0 image
> > 3. use the image dropdown from the moment tab to select HD163296_CO_2_1.fits
> > 4. we should see the moment generator progress popup shows up and hangs there forever.
> 
> Can you check if it exists in `dev`?

dev is fine. 🤔

**Comment by veggiesaurus** [comment]
> found an issue related to moment generator which does not exist in release 2.0.
> To reproduce:
> 
> 1. load HD163296_CO_2_1.fits
> 2. generate a moment 0 image
> 3. use the image dropdown from the moment tab to select HD163296_CO_2_1.fits
> 4. we should see the moment generator progress popup shows up and hangs there forever.

Something like this? 
image

edit: fixed in latest commit :slightly_smiling_face: Thanks for spotting it @kswang1029

**Review by kswang1029 — APPROVED** [review]
as far as I can tell this PR does not break things. Will keep an eye on this later.

**Review by duidae — APPROVED** [review]

**Pull request merged**
