### PR TITLE
Re-arrange File menu order

### LINKED ISSUE #2092: refine the context order in the File menu
**Describe the bug**
This is pointed out by @pford.

The current context order in the File menu is not logically sensible. 
Screen Shot 2023-02-01 at 09 44 19

We should group the context as the following:

group1:
Open image
Append image
Save image
Close image

group2:
Import regions
Export regions
Import catalog
Export image
 
group3:
Preferences
Server

@pford @confluence @veggiesaurus @YuHsuan-Hwang @ajm-asiaa please see if this new grouping strategy is better.

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Monterey
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 109
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

### PR DESCRIPTION
**Pull request by I-Chenn**
**Description**
The PR is to resolve #2092. The File menu order is re-arranged following @kswang1029's idea (see the attached image), but is still available for discussion.
image

**Checklist**

For linked issues (if there are):
- [X] assignee and label added
- [X] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [X] reviewers and assignee added
- [ ] ZenHub estimate, milestone, and release (if needed) added
- [x] e2e test passing / ~corresponding fix added~
- [X] changelog updated / ~no changelog update needed~
- [X] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [X] `BackendService` unchanged / ~`BackendService` changed and corresponding ICD test fix added~

### CODE REVIEW

**Comment by veggiesaurus** [comment]
@kswang1029 do you want workspaces to go above or below images?

**Comment by kswang1029** [comment]
> @kswang1029 do you want workspaces to go above or below images?

if it is my grouping strategy, I would say as a new group (Import workspace, Export workspace) and like this
 
215980306-39d0de8c-4510-4849-81dc-ff5eec4880fa

If it is @ajm-asiaa's grouping strategy, then as a new group above the preference group probably.

**Comment by I-Chenn** [comment]
@veggiesaurus @kswang1029 @confluence @YuHsuan-Hwang @ajm-asiaa @pford 
We decided to keep the arrangement from 7d1a7da. We will adjust the arrangement if there are further opinion/feedback from the developers/users. The PR is ready for review now.

**Review by kswang1029 — APPROVED** [review]
no regression from e2e tests. 👍

**Review by YuHsuan-Hwang — APPROVED** [review]

**Pull request merged**
