### PR TITLE
Yuhsuan/2252 fix spatial match

### LINKED ISSUE #2252: failed to match images spatially
**Describe the bug**

In some special cases (probably trying to match images with different coordinate systems, such as FK5 <-> GALACTIC), CARTA refuses to match images. The console log shows

Screenshot 2023-09-11 at 21 00 57

Once we start seeing the error, we will not be able to match any images. Sometimes, if we change the active image and redo matching, it may work or may not.

See the steps below to reproduce the issue.

This might be a regression between the v3 and v4 releases. With v3, the issue cannot be reproduced.

**To Reproduce**
1. download the test images at https://drive.google.com/file/d/1ZVJxTFF_K56cTlnB4vXYuAIen-xKr5dy/view?usp=share_link
2. load the folder using filename to sort
3. load all the images _at once_ in the order like below
Screenshot 2023-09-11 at 20 50 54

4. the image viewer should stay as 2x2 grid
5. without touching anything else, try to match images in order (or try to match the 8th image directly)
6. until the 8th image we will see matching failure and cannot match any other images anymore
7. try to change the active image and repeat the test, sometimes we can match images but it may fail again

If we preconfigure the grid layout to 4x4, for example, all images can be matched successfully. Maybe this is something to do with AST memory management/leakage or racing condition?

**Expected behavior**
images should match

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Ventura
 - Browser [e.g. chrome, safari, electron app]: electron
 - Browser version [e.g. 22]: 
 - Backend branch [e.g. dev, v3b2 release]: dev, v4-stable
 - Frontend branch [e.g. dev, v3b2 release]: dev, v4-stable

### PR DESCRIPTION
**Pull request by YuHsuan-Hwang**
**Description**

Fixed #2252. The root cause is that the coordinate system is updated only for rendered images. Fixed by updating all the images instead of only rendered images when the coordinate system is changed.

This is a regression from #2190. Before the PR, we create the transformation by combining two AST FrameSet. The images can still be matched when their coordinate systems are different. After the PR, we create it simply by combining the conversion of image coordinate <-> WCS coordinate of the two images. Therefore, it fails when their WCS values are different.

Please note that if we implement independent coordinate systems (#1619) in the future, for spatial matching we might need to create a temporary copy of the matched frame, set it to the same coordinate system, and then create the transformation.

Changes:
* Added coordinate system update to overlay store `autorun` function.
* Refactoring
    * Removed unused variables in overlay store `autorun` functions.
    * Removed unnecessary update in `setSystem`.

Tested that:
* All the image overlays update with the global coordinate system and the number custom XY formats.
* Pan and zoom and region inputs update with the global coordinate system and the number custom XY formats as usual.
* Distance measuring on all the images updates with the global coordinate system as usual.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] changelog updated / ~no changelog update needed~
- [x] ~unit test added (for functions with no dependenies)~
- [x] ~API documentation added (for public variables and methods in stores)~

For dependencies:
- [x] e2e test passing / ~corresponding fix added~ / ~new e2e test created~
- [x] ~protobuf version bumped~ / no protobuf version bumped needed
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] ~corresponding ICD test fix added (`BackendService` changed)~ / no ICD test fix needed (`BackendService` unchanged)
- [x] ~user manual prepared (for large new features)~

### CODE REVIEW

**Review by kswang1029 — CHANGES_REQUESTED** [review]
@YuHsuan-Hwang The matching part appear fine. However, if we use one of the secondary image as the data source for contours, it seems that other images may not have the contours rendered _initially_ (in my test case it is with a 2x2 layout). We may need to either set to next image as active or pan/zoom a bit to trigger re-rendering. 

https://github.com/CARTAvis/carta-frontend/assets/20819712/bc0220b1-f3d9-437a-add4-0a919bd8579a

UPDATE: would it be fixed with https://github.com/CARTAvis/carta-frontend/pull/2322 ? Guess not?

**Comment by YuHsuan-Hwang** [comment]
> However, if we use one of the secondary image as the data source for contours, it seems that other images may not have the contours rendered _initially_ (in my test case it is with a 2x2 layout). We may need to either set to next image as active or pan/zoom a bit to trigger re-rendering.

Looks like this also exists in dev?

**Comment by kswang1029** [comment]
> > However, if we use one of the secondary image as the data source for contours, it seems that other images may not have the contours rendered _initially_ (in my test case it is with a 2x2 layout). We may need to either set to next image as active or pan/zoom a bit to trigger re-rendering.
> 
> Looks like this also exists in dev?

Right, it is in dev (but not v4-stable). So it is another regression. Would you prefer to fix it in https://github.com/CARTAvis/carta-frontend/pull/2322 as well? Or as a separate PR (plus a new issue)?

**Comment by YuHsuan-Hwang** [comment]
Separate PR would be better for preparing v4.1.

**Comment by kswang1029** [comment]
> Separate PR would be better for preparing v4.1.

ok. issue filed as https://github.com/CARTAvis/carta-frontend/issues/2330

I would need to re-test this once #2293 and #2230 are fixed.

**Comment by loveluthien** [comment]
Is this under expectation? Using test data provided in #2252, there are four images that can not be matched. However, if I manually click the toggle, they still can do the spatial match.
截圖 2024-01-09 下午2 25 37
截圖 2024-01-09 下午2 37 08
截圖 2024-01-09 下午2 37 37

**Comment by YuHsuan-Hwang** [comment]
> Is this under expectation? Using test data provided in #2252, there are four images that can not be matched. However, if I manually click the toggle, they still can do the spatial match.

I see. I will fix this.

**Comment by YuHsuan-Hwang** [comment]
Updates:
* Fixed incorrect precision of the overlay numbers (regression in this branch) by adding back the AST updates in the overlay component.
* Fixed failing to match images on append by updating images when setting AST defaults of a new image.

**Review by loveluthien — APPROVED** [review]
The fix is good.

**Comment by YuHsuan-Hwang** [comment]
Updates:
* Update the frames in FrameStore instead of OverlayStore.
* When matching images on append, update images only when the system is set as auto.

**Review by kswang1029 — APPROVED** [review]
tested manually with the test images mentioned in the issue in some other orders, with some other test images (different target sources), and with images that cannot be matched. all looking fine so far. No other regression from e2e tests. 

Note:
1. contour rendering issue https://github.com/CARTAvis/carta-frontend/issues/2330 exists in this PR. 
2. vector rendering issue https://github.com/CARTAvis/carta-frontend/issues/2293 has been fixed in this PR. 👍

**Review by crocka — APPROVED** [review]

**Pull request merged**
