### PR TITLE
adds contour properties to resume message

### PR DESCRIPTION
**Pull request by veggiesaurus**
Companion PR of https://github.com/CARTAvis/carta-backend/pull/471

Should allow contours to be used correctly when session is resumed

### CODE REVIEW

**Review by duidae — APPROVED** [review]

**Comment by kswang1029** [comment]
tested with
http://carta.asiaa.sinica.edu.tw/frontend/35b5f3e/?socketUrl=wss://carta.asiaa.sinica.edu.tw/socket5036
frontend: 35b5f3e
backend: 68a06a0

When there is one image cube with contour enabled, contour resume works. After session resume, changing channels results in contour update per channel as expected. 

When there are two image cubes matched both spatially and spectrally, contour resume does not work. After session resume, changing channels only results in raster update per channel. Contour images stay the same as the ones before session resume.

**Comment by veggiesaurus** [comment]
> When there are two image cubes matched both spatially and spectrally, contour resume does not work. After session resume, changing channels only results in raster update per channel. Contour images stay the same as the ones before session resume.

@kswang1029 I have fixed this issue, please retest. I have also added catalog support in a later commit, which should be built shortly in mix 'n match

**Comment by kswang1029** [comment]
@veggiesaurus now contour resume works fine 👍 

do we need a dedicated backend for catalog resume?

**Comment by veggiesaurus** [comment]
> @veggiesaurus now contour resume works fine 
> 
> do we need a dedicated backend for catalog resume?

Frontend commit `1e236a1` should work with catalogs as well

**Comment by kswang1029** [comment]
catalog resume works too. Tried to load two catalog and after resume, I can apply filters to each. 👍

**Pull request merged**
