### PR TITLE
Jason/issue 1129 2

### LINKED ISSUE #1129: [2.0 suggestion] refactoring: explicitly describe center/size from controlpoints[] in RegionStore for clear code
size & center can be explicitly expressed from controlpoints[] with delegation(not easy to entirely pulled out from controlPoints because of the original ICD design)
and those center = region.controlPoints[0] should be eliminated

center = region.controlPoints[0]
size = region.controlPoints[1]
setControlPoint(0, ...) => change to setCenter()
setControlPoint(1, ...) => change to setSize()

### PR DESCRIPTION
**Pull request by duidae**
closes #1129

please help test center/size fields in region dialog to see whether the results are correct or not, thanks.
frontend crash issue while creating region is fixed.

### CODE REVIEW

**Review by kswang1029 — APPROVED** [review]
the region list widget behaves the same after refactoring. 👍 

I spotted a coordinate transformation bug but we can deal with it with a new issue as it exists somehow in the dev branch too.....🙈

**Comment by duidae** [comment]
just want to make sure: @kswang1029 did u test the region dialogs or region list widget? the refactoring requires testing the center/size values in region dialogs.

> the region list widget behaves the same after refactoring. 
> 
> I spotted a coordinate transformation bug but we can deal with it with a new issue as it exists somehow in the dev branch too.....

**Comment by kswang1029** [comment]
Yes, region dialog works as same as before refactoring.

**Review by veggiesaurus — APPROVED** [review]
code looks fine. So we're ready to merge this in again, right @kswang1029 ?

**Comment by kswang1029** [comment]
Yes ready!

**Pull request merged**
