### PR TITLE
Qi/migrate to chartjs3

### LINKED ISSUE #1567: ChartJS 3 migration
ChartJS 3 has large performance improvements, but has a number of breaking changes. The migration guide is provided [here](https://www.chartjs.org/docs/latest/getting-started/v3-migration.html).

### PR DESCRIPTION
**Pull request by panchyo0**
Related issue #1567 
1. updated `chartjs` form `2.9.4` to `3.5.1`, `chartjs-color`, `chartjs-color-string` and `chartjs-color/node_modules/color-convert` are auto removed from package-lock.json after updating to `3.5.1`
2. updated  `react-chartjs-2` from `2.11.2` to `3.1.1`(Plugin has type error before v3.1.1)
3. removed `@types/chart.js` since chartjs has it own type support 
4. removed self defined `multicolorLine` chart type, since Chartjs3 support [Line Segment Styling](https://www.chartjs.org/docs/3.2.0/samples/line/segments.html)
5. when logY enabled, replacing log(0) with log(0.5) to avoid the line missing bug after update to chartjs3

### CODE REVIEW

**Comment by kswang1029** [comment]
The padding to the right of the spatial profile plot is missing. For the spectral profile plot, the padding is there. 

Screen Shot 2021-10-28 at 12 55 35 PM

**Comment by kswang1029** [comment]
the gaussian profile line plot needs to be thicker. In addition, the residual point plot is missing (cf dev)

Screen Shot 2021-10-28 at 1 00 20 PM

**Comment by kswang1029** [comment]
regarding the histogram widget, sometimes we see broken histogram like the following example. This is plot with log scale in y.

Screen Shot 2021-10-28 at 1 09 05 PM

Broken histogram is also observed in the contour dialog.
Screen Shot 2021-10-28 at 1 35 30 PM

**Comment by kswang1029** [comment]
when trying to apply profile smoothing to the profiles in the Stokes analysis widget, frontend will crash.
Screen Shot 2021-10-28 at 1 19 34 PM

**Comment by kswang1029** [comment]
there are missing x ticks and labels in the spectral profiler widget (also observed in the render config widget and spatial profiler). In the following example, it is expected to have 84.1 and 84.9. I remember @TienHao fixed the too-many-digits issue before so this might be related. 
Screen Shot 2021-10-28 at 1 28 38 PM

**Comment by panchyo0** [comment]
@kswang1029 I fixed the first 5 issues. Please check again.
> there are missing x ticks and labels in the spectral profiler widget (also observed in the render config widget and spatial profiler). In the following example, it is expected to have 84.1 and 84.9. I remember @TienHao fixed the too-many-digits issue before so this might be related.
> Screen Shot 2021-10-28 at 1 28 38 PM

the first and last tick are removed because the `initialDist < interTickDist * 0.999` or `initialDist > interTickDist * 1.001`, for example when we have ticks like [83.9999999, 84.2, 84.3, 84.4, 84.5555555]. Will those ticks show up when you zoom in/out ?

**Comment by kswang1029** [comment]
> @kswang1029 I fixed the first 5 issues. Please check again.
> 
> > there are missing x ticks and labels in the spectral profiler widget (also observed in the render config widget and spatial profiler). In the following example, it is expected to have 84.1 and 84.9. I remember @TienHao fixed the too-many-digits issue before so this might be related.
> > Screen Shot 2021-10-28 at 1 28 38 PM
> 
> the first and last tick are removed because the `initialDist < interTickDist * 0.999` or `initialDist > interTickDist * 1.001`, for example when we have ticks like [83.9999999, 84.2, 84.3, 84.4, 84.5555555]. Will those ticks show up when you zoom in/out ?

Nope, it appears that there is always one missing each side at different zoom levels.
Screen Shot 2021-11-02 at 12 57 09 PM
Screen Shot 2021-11-02 at 12 57 01 PM
Screen Shot 2021-11-02 at 12 56 54 PM

**Comment by kswang1029** [comment]
> @kswang1029 I fixed the first 5 issues. Please check again.
> 
> >

Yes, confirmed that issues are fixed. The remaining one is the missing ticks part.

**Comment by panchyo0** [comment]
@kswang1029 please, check the missing tick issue

**Review by veggiesaurus — APPROVED** [review]

**Review by kswang1029 — APPROVED** [review]

**Pull request merged**
