### PR TITLE
Angus/chore package updates

### PR DESCRIPTION
**Pull request by veggiesaurus**
Update packages where possible. We're still stuck using a slightly older version of `protobufjs` due to a known issue (https://github.com/protobufjs/protobuf.js/issues/1452)

@kswang1029, you can see the diff for package.json below for details on which packages have been updated

### CODE REVIEW

**Review by duidae — APPROVED** [review]

**Comment by veggiesaurus** [comment]
some issue with the number of rows being displayed in the table :thinking: I'll try to fix it.

**Comment by kswang1029** [comment]
with 7731d05, when resizing a floating widget, its position changes (we had same issue before I remember. due to Mobx?)

https://user-images.githubusercontent.com/20819712/106078504-7f899b00-614e-11eb-85a2-88914616af47.mp4

**Comment by kswang1029** [comment]
with 7731d05, polygon creation is affected. 

Uploading Jan-28-2021 09-40-39.mp4…

**Comment by kswang1029** [comment]
origin/angus/chore_package_updates c24cb8f  this latest one seems problematic. The file browser loads but if we click a folder, the frontend seems crashed (i see a blank page, all GUI gone)

**Comment by kswang1029** [comment]
with 7731d05, we cannot dock a _new_ widget by click-dragging a widget button to a panel.

**Comment by kswang1029** [comment]
with 7731d05 table is broken (known issue)
Screen Shot 2021-01-28 at 10 31 13 AM

**Comment by kswang1029** [comment]
with 7731d05, polygon creation is affected (Konva?). 

https://user-images.githubusercontent.com/20819712/106085094-87e7d300-615a-11eb-9993-32f68d97f8ed.mp4

**Comment by veggiesaurus** [comment]
@kswang1029 please re-test. I am now using @blueprint/table 3.7.1, as @panchyo0 has suggested.

Still to fix: 
- [x] Polygon creation
- [x] ~~Click and drag to create a docked widget~~ (this seems to be broken in `dev` as well?)
- [x] ~~Floating widget~~ (will be handled in a separate existing issue: #1234)

**Comment by kswang1029** [comment]
@veggiesaurus with `0589029` the table issue is fixed 👍 The issue of resizing a floating widget resulting in a position shift is still there. 

> with [7731d05](https://github.com/CARTAvis/carta-frontend/commit/7731d054da1302327fc756b1b7e3b91400f61dd5), when resizing a floating widget, its position changes (we had same issue before I remember. due to Mobx?)
> 
>  Jan-28-2021.09-50-08.mp4

**Comment by veggiesaurus** [comment]
> with [7731d05](https://github.com/CARTAvis/carta-frontend/commit/7731d054da1302327fc756b1b7e3b91400f61dd5), polygon creation is affected (Konva?).
> 
>  Jan-28-2021.09-40-39.mp4

this is actually due to #1292, I'll fix it as well :+1:

**Comment by veggiesaurus** [comment]
@kswang1029 please re-test. I've reverted the change to react-rnd (we've got an open issue for it already: #1234), and I fixed the polygon creation bug. The click-and-drag seems to already be broken in `dev`, shall we handle it in a separate issue?

**Comment by kswang1029** [comment]
Yes with 19d5c73, polygon issue and floating widget resizing issue are gone. I will file a new issue for drag-and-drop issue. 👍

**Pull request merged**
