### PR TITLE
Carli/1327 spectral line off precision

### LINKED ISSUE #1327: spectral line label off by one channel?
In the following example, if we set the velocity shift to be 1540 km/s, it is expected to see the label is plotted at 1540 km/s but it appears there is one channel offset. Changing to other velocity shift (eg 1600 km/s) has the same issue. @duidae do you think this is due to the 0-index/1-index issue?

Screen Shot 2021-02-23 at 1 58 05 PM

### PR DESCRIPTION
**Pull request by crocka**
**Description**

Closes #1327. The redshift factor is calculated incorrectly.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] ~e2e test passing~ / corresponding fix added
- [ ] changelog updated / ~~no changelog update needed~~
- [ ] protobuf updated to the latest dev commit / ~~no protobuf update needed~~
- [ ] `BackendService` unchanged / ~~`BackendService` changed and corresponding ICD test fix added~~

### CODE REVIEW

**Review by kswang1029 — APPROVED** [review]
this looks good with some high-z sources. a fix to e2e test is applied. please proceed code review.

**Comment by kswang1029** [comment]
@crocka @YuHsuan-Hwang a quick question: are we using AST to perform frequency to radio velocity conversion (ie calling an AST function to do the conversion, instead of making our own conversion function)? If so, are we able to tell the formula of the AST conversion? I would like to figure our this detail and probably this is the key to explain why our relativistic formula does not work.

**Comment by YuHsuan-Hwang** [comment]
Yes, I think we are using AST. Will need to check the user guide.

**Comment by kswang1029** [comment]
> Yes, I think we are using AST. Will need to check the user guide.

ok thanks. My speculation is that AST does not use relativistic formula to convert frequency to radio velocity. But in CARTA before @crocka's fix, we use relativistic formula to compute line ID label shift. Now @crocka uses non-relativistic formula and we don't see the inconsistency.

**Review by kswang1029 — APPROVED** [review]
conventionally frequency to radio velocity conversion is non-relativistic. The original line ID label shift formula we adopted is relativistic. So this is the root cause of the offset we observed when source has high(er) radial velocity. The current fix switches back to the non-relativistic formula for consistency.

**Review by YuHsuan-Hwang — APPROVED** [review]

**Comment by YuHsuan-Hwang** [comment]
Ready for merge. @crocka Please update the change log, thanks.

**Comment by YuHsuan-Hwang** [comment]
@crocka Please also update to the latest dev branch, thanks.

**Pull request merged**
