### PR TITLE
Add rigorous check (dev)

### PR DESCRIPTION
**Pull request by duidae**
test file: 18h03m_tabular_axis.image

spectral header is invalid for AST to convert data, so should only enable native wcs & channel

### CODE REVIEW

**Comment by veggiesaurus** [comment]
@pford does this fix the issue you brought up in the frontend channel?

**Comment by pford** [comment]
Shouldn't it revert to channel as before?

**Comment by veggiesaurus** [comment]
Yes. Is that not what it's doing?

**Comment by pford** [comment]
The spectral profile is empty, Value vs Channel with default ranges 0 - 1.
I tested frontend origin/jason/refine_check_dev and backend origin/dev 22b5f9d (before my FREQ fix)

**Comment by veggiesaurus** [comment]
@duidae please check. I agree with @pford. In fact, You should always be able to view the spectral axis as channel or whatever the native type is, even if AST doesn't recognize the type.

**Comment by duidae** [comment]
kk will resume plot & disable conversion

**Comment by duidae** [comment]
@veggiesaurus @pford @kswang1029  ok, please have a look, thanks.

**Comment by pford** [comment]
@duidae looks good!  Plots the spectral profile vs channel.

**Comment by arusstaylor** [comment]
If spectral frame is empty one should still be able to due basic wcs conversion, i.g convert channel to frequency and wavelength.

**Comment by pford** [comment]
@arusstaylor this fix is for a missing or non-standard CTYPE header for the spectral axis.

**Comment by veggiesaurus** [comment]
> If spectral frame is empty one should still be able to due basic wcs conversion, i.g convert channel to frequency and wavelength.

If the spectral frame is non-standard, the only thing we should be able to do is convert from channel to whatever the spectral frame is (same as DS9). Converting from that frame to another (e.g. freq -> wavelength) should require that the image adheres to WCS standards

**Comment by duidae** [comment]
@veggiesaurus @kswang1029  changed to show only native wcs + channel when cube's spectral axis is invalid (like DS9), please have a look & test, thanks.

**Comment by kswang1029** [comment]
verified. 👍

**Review by veggiesaurus — APPROVED** [review]
this looks fine. I'll merge into `dev`, please make a backport for 1.3, which @kswang1029 will test carefully to ensure no other issues crop up

**Comment by kswang1029** [comment]
I tried with cubes 
with CTYPE3 = XYZ and CUNIT3 = Hz (working)
with CTYPE4 = XYZ and CUNIT4 = Hz, and CTYPE3 = STOKES and CUNIT3 = ' ' (backend does not return headers and provides an error message)
with CTYPE3 = XYZ and CUNIT3 = GigaHertz (backend does not return headers and provides an error message)

For the frontend part I think it is good to go. Now the question is do we want to support this kind of exception in the backend header parser?

**Pull request merged**
