### PR TITLE
Kuanchou/2278_crash_when_deleting_annotations

### LINKED ISSUE #2278: Delete regions when Export Regions dialog is open
**Describe the bug**
Frontend crashes if we delete regions when Export Regions dialog is open.

**To Reproduce**
1. Open an image.
2. Create two regions.
3. Create two annotations.
4. Open Export Regions dialog.
5. Delete a region or an annotation.

**Expected behavior**
Frontend does not crash and the export region checkbox list is updated.

**Screenshots or videos**
image

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Big Sur
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 117
 - Backend branch [e.g. dev, v3b2 release]: dev and v4
 - Frontend branch [e.g. dev, v3b2 release]: dev and v4

**Additional context**

### PR DESCRIPTION
**Pull request by loveluthien**
**Description**

Fix #2278. The frontend will crash when deleting annotations if the export window is opened. The crash is due to that undefined was found in the index of the deleted annotation when the system counted annotation object numbers in the file browser store. 

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] e2e test passing / corresponding fix added / new e2e test created
- [x] changelog updated / no changelog update needed
- [x] protobuf updated to the latest dev commit / no protobuf update needed
- [x] protobuf version bumped / protobuf version not bumped
- [x] `BackendService` unchanged / `BackendService` changed and corresponding ICD test fix added

### CODE REVIEW

**Review by YuHsuan-Hwang — APPROVED** [review]
Looks good. Please update the change log, thanks.

**Comment by loveluthien** [comment]
the last push is to fix the incorrect text formatting in CHANGELOG.md.

**Review by kswang1029 — CHANGES_REQUESTED** [review]
Yes, the crashing issue is resolved. The GUI part, however, need additional changes which may be in another PR. The logic of the text description generation need a fix when a region/annotation is deleted. We may consider to rename "regions" as "elements" so it is kinda generic for region and annotation. Otherwise, we may consider to have another text entry for annotations. 

Screenshot 2023-11-23 at 19 53 52

If we decide to fix the text info in another PR, I will approve this PR. Please let me know.

**Comment by loveluthien** [comment]
I don't mind making additional changes to this PR, since only one place has been modified.

**Comment by YuHsuan-Hwang** [comment]
@loveluthien I suggest we file an issue and add it to the change log.

**Comment by loveluthien** [comment]
@kswang1029 please approve this issue, I will file another one to fix the text.

**Review by kswang1029 — APPROVED** [review]

**Pull request merged**
