### PR TITLE
Jason/issue 1312 2

### LINKED ISSUE #1312: show warning to users when spatial matching failed & get AST error
to reproduce:
1. open a file with NAXIS3=stoke NAXIS4=FREQ
2. append a file with spectral axis
3. click XY matching

P.S.  the file in (1) has the headers as below (I renamed the file to multi-stoke so dont know what's the original file name):
image

image

### PR DESCRIPTION
**Pull request by duidae**
closes #1312

major changes: adding error handling to ensure transformedWcsInfo is obtained successfully, then do spatial matching.

### CODE REVIEW

**Comment by kswang1029** [comment]
@duidae spatial matching seems not functional as before. Please check the location of world(90deg, 5deg). It should stay at the center of the viewer as this is how spatial matching is handled. We get the center coordinates of the viewer and apply world coordinate match among different images. 

dev/v2.0 release:

https://user-images.githubusercontent.com/20819712/124540597-5504e200-de52-11eb-855d-95b5f3b55809.mov

this branch:

https://user-images.githubusercontent.com/20819712/124540713-96958d00-de52-11eb-89d2-f0dce9c1fe4e.mov

**Comment by duidae** [comment]
should be fixed, please have a look. Thanks.

**Comment by kswang1029** [comment]
@duidae the solution here is we still try to match the images first and see if it is successful or not? ie the try/except approach?

**Comment by duidae** [comment]
> @duidae the solution here is we still try to match the images first and see if it is successful or not? ie the try/except approach?

the problem comes from missing error handlings for matching-related byproducts & AST object, add prevention for those things.

**Review by kswang1029 — APPROVED** [review]

**Review by veggiesaurus — APPROVED** [review]

**Review by veggiesaurus — APPROVED** [review]

**Pull request merged**
