### PR TITLE
add SafeNumericInput component

### LINKED ISSUE #615: NaN appears in numeric input
when entering "-1" to various numeric inputs in current CARTA, NaN appears. On ubuntu platform, it can be reset by entering a normal number, however, on Mac, users could be totally stucked.

image

### PR DESCRIPTION
**Pull request by veggiesaurus**
This PR adds a `SafeNumericInput` component, which checks whether the value is finite before calling `onValueChange`. 

This fixes #615 in all of the spots that I could find (please check that I haven't missed any)

### CODE REVIEW

**Review by duidae — APPROVED** [review]

**Comment by kswang1029** [comment]
@veggiesaurus NaN is gone. 👍 

I noticed that when a text field is
1) empty
2) "-"
3) "."
4) "+"

the reset default button does not work.
When the text field is one of the above, we can still generate contour levels.

**Comment by veggiesaurus** [comment]
> @veggiesaurus NaN is gone. 
> 
> I noticed that when a text field is
> 
> 1. empty
> 2. "-"
> 3. "."
> 4. "+"
> 
> the reset default button does not work.
> When the text field is one of the above, we can still generate contour levels.

This change shouldn't affect clear-able fields. Can you check with `dev`

**Comment by kswang1029** [comment]
@veggiesaurus ok, you are right, dev has the same thing. OK, for NaN fix, I think it is effective. :)

**Comment by veggiesaurus** [comment]
> @veggiesaurus ok, you are right, dev has the same thing. OK, for NaN fix, I think it is effective. :)

can you file a separate issue for this?

**Comment by kswang1029** [comment]
done: https://github.com/CARTAvis/carta-frontend/issues/840

**Pull request merged**
