### PR TITLE
Angus/close file

### PR DESCRIPTION
**Pull request by veggiesaurus**
This PR adds the ability to remove the currently active image by clicking File->Close Image, or using the shortcut key "{modifier}+W" (so ALT + W for browser, CTRL + W for linux desktop and CMD + W for MacOS)

If the image is currently active, the first remaining image becomes the new active image. If the image is currently the spatial reference for any other images, a confirmation alert is shown, indicating that other images will also be closed. If the user confirms, the first remaining image becomes the new spatial reference.

### CODE REVIEW

**Comment by veggiesaurus** [comment]
@kswang1029 please give this a try. The other option would be to simply un-match other files, rather than closing them

**Comment by kswang1029** [comment]
> The other option would be to simply un-match other files, rather than closing them

could we support this? I think this is much better than closing all other matched images.

**Comment by veggiesaurus** [comment]
> > The other option would be to simply un-match other files, rather than closing them
> 
> could we support this? I think this is much better than closing all other matched images.

Ok. And we still make the first file the reference?

**Comment by kswang1029** [comment]
yes, the first remaining image is the new reference and no one is matched wrt it. Sounds intuitive to you?

**Comment by veggiesaurus** [comment]
> yes, the first remaining image is the new reference and no one is matched wrt it. Sounds intuitive with you?

Yes, I think that should be fine. In this case, I'll still warn that images will be unmatched, and any regions in the images will be deleted

**Comment by kswang1029** [comment]
👍

**Pull request merged**
