### PR TITLE
Add disabled props to disable the button

### LINKED ISSUE #2057: Invisible export txt file button in the image fitting dialog
**Describe the bug**
There is an invisible export txt file button in the image fitting dialog when there's no fitting results. Users can click the button and get an empty txt file.

**To Reproduce**
1. Open a file
2. Open the image fitting dialog
3. Hover the fitting result column
4. Click the button and get an empty txt file

**Expected behavior**
The entire button group is not rendered.

**Screenshots or videos**
image

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: dev
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 107
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

**Additional context**

### PR DESCRIPTION
**Pull request by I-Chenn**
**Description**

This draft PR is to fix #2057.

Since the buttons are rendered as a whole with the panel, `disabled` props are added to `AnchorButton` and `Tooltip2` to disable the buttons & tooltips. The modification does disappear the tooltip and prevent user from outputting the result, nevertheless, a "forbidden" icon is shown when the cursor hover to the position of the button (see the image shown below...)
Dialog2
(Sorry for taking the photo using my cellphone since the "print screen" function of Linux cannot record the cursor status.)
which is a bit weird.

It is perhaps not the best solution thus I would like to take suggestions from you.

**Checklist**

For linked issues (if there are):
- [X] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [X] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [X] e2e test passing / ~corresponding fix added~
- [X] changelog updated / ~no changelog update needed~
- [X] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [X] `BackendService` unchanged / ~`BackendService` changed and corresponding ICD test fix added~

### CODE REVIEW

**Comment by kswang1029** [comment]
This would fix the problem.

```
        const fittingResultPanel = (
            <Pre className="fitting-result-pre">
                <Text className="fitting-result-text">{fittingStore.effectiveFrame?.fittingResult ?? ""}</Text>
                {fittingStore.effectiveFrame.fittingResult !== "" ? (
                    <ButtonGroup className="output-button" style={{opacity: this.isMouseEntered && fittingStore.effectiveFrame.fittingResult !== "" ? 1 : 0}}>
                        <Tooltip2 content={"Export as txt"} position={Position.LEFT}>
                            <AnchorButton icon="th" onClick={this.exportResult}></AnchorButton>
                        </Tooltip2>
                    </ButtonGroup>) : null}
            </Pre>
        );
```

**Comment by YuHsuan-Hwang** [comment]
or fix with `{fittingStore.effectiveFrame?.fittingResult !== "" && (<ButtonGroup...)}`

**Comment by I-Chenn** [comment]
@kswang1029 @YuHsuan-Hwang 
Thanks for the suggestions and I have made the modification following your methods (01c1b85). I think this PR is ready for review.

**Review by kswang1029 — APPROVED** [review]

**Review by YuHsuan-Hwang — CHANGES_REQUESTED** [review]
We don't need to update change log because it's a newly added feature.

**Comment by I-Chenn** [comment]
I have deleted the update of changelog, but I'm not sure what's going on with the `CI / node-v16` test.

**Review by YuHsuan-Hwang — APPROVED** [review]

**Pull request merged**
