### PR TITLE
Fix warning

### PR DESCRIPTION
**Pull request by duidae**
`fix warning of <ul> cant be descendant of <p>` 

image

### CODE REVIEW

**Comment by kswang1029** [comment]
There might be other help contents with same problem... need to double check.

**Comment by duidae** [comment]
yeah there are a few

**Comment by kswang1029** [comment]
Thanks for fixing 🙈

That’s I didn’t follow the HTML rules or it is react doesn’t like it? Or else?

**Comment by duidae** [comment]
`<p></p>` tag can only contain inline elements according to W3C spec.

**Review by veggiesaurus — APPROVED** [review]

**Pull request merged**
