### PR TITLE
Fix 887 for 1.3 patch

### LINKED ISSUE #887: incorrect or inaccurate angular size of rectangle and ellipse regions in the region dialogue
In the region dialogue, angular sizes of ellipse region or rectangle region are displayed next to the sizes in image coordinate. These values, however, are not correct for ellipse or are not accurate for rectangle. See the following screenshots. 

Screen Shot 2020-04-20 at 1 19 56 PM

Screen Shot 2020-04-20 at 1 20 09 PM

In addition, the unit of the angular size should be dynamic based on the angular size. For example, in the above cases, it is preferred to use arcsec, instead of arcmin.

### PR DESCRIPTION
**Pull request by duidae**
closes #887

### CODE REVIEW

**Review by kswang1029 — APPROVED** [review]
Tested and it looks good!

**Comment by kswang1029** [comment]
Oops, found a small issue:
Major axis of an ellipse points to North in astronomical convention (and also CRTF definition). So we need to swap the derived angular sizes in the text.
Screen Shot 2020-04-30 at 10 39 23 AM
Screen Shot 2020-04-30 at 10 39 37 AM

That is, the two text input fields are ordered as major(vertical direction)-minor(horizontal direction). So the following derived angular sizes need to be swapped.

**Comment by duidae** [comment]
@kswang1029 fixed, please have a look, thanks.

**Comment by kswang1029** [comment]
@duidae Looking great! Thanks 👍

**Pull request merged**
