### PR TITLE
Yuhsuan/scroll shadow

### LINKED ISSUE #2166: [v4-beta user feedback] always show the scroll bar for the input parameter pane in the image fitting widget
The feedback is user did not know there are other required input fields in the image fitting widget so cannot figure out why the fit button does not work.

### LINKED ISSUE #2375: header info display color in the dark theme
**Describe the bug**
The "comment" part of the header display becomes hard to read in the dark theme as demonstrated below. We better use a lighter color to show the "comment" part.

Screenshot 2024-05-10 at 16 22 28

**To Reproduce**
1. switch to the dark theme
2. use the file browser to see image header and see the issue

**Expected behavior**
We better use a lighter color to show the "comment" part.

**Screenshots or videos**
If applicable, add screenshots/videos to help explain your problem.

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Ventura
 - Browser [e.g. chrome, safari, electron app]:  chrome / electron app
 - Browser version [e.g. 22]: 
 - Backend branch [e.g. dev, v3b2 release]: dev, v4.1
 - Frontend branch [e.g. dev, v3b2 release]: dev, v4.1

### LINKED ISSUE #2446: [Regression] Inconsistent dark theme background
**Describe the bug**

There are some changes to the dark theme background in this dev cycle (possibly results from upgrading to bp v5):

1. The menu buttons have a darker color comparing to the overall background.
    image

    cf. v4.1: Consistent background.
    image

2. Among all the widgets, z profile, histogram, and spectral line query widgets has a lighter color comparing to other widgets.

    image
    
    cf. v4.1: All widgets have the same color.

3. Undocked widgets have a lighter color comparing to docked widgets. This includes all undocked normal widgets, all settings widgets that cannot be docked, and PV previewer and catalog scatter/histogram plots. (Dialogs have the same color with the docked widgets.)

    image

    When we export png file of the profile, we always get the light background (undocked widget background) instead of the dark one (docked widget background).

    cf. v4.1: Docked widgets, undocked widgets, and dialogs all have the same color.

**Expected behavior**
Consistent background color.

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS 14
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 129
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

### LINKED ISSUE #2450: Improve dark theme string color in the header information panel
**Describe the bug**
The string color in the header information panel in dark theme could be improved.

For comments, we could apply light gray instead:
image

For highlighted strings, we could apply black instead:
image

This includes the file browser dialog and the file header dialog. The screenshots are from dev branch, but we have the same issue in v4.1.

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: maxOS 14
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 129
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

### LINKED ISSUE #2451: Improve consistency of table dark theme backgrounds
**Describe the bug**

The table dark theme backgrounds could be improved:

Pasted Graphic 26
image

1. (dark blue squares) We could apply a darker color (same with the widget background) for empty spaces to avoid them being emphasized by the light gray and to be consistent with the statistic and region list widgets. This will require overwriting the blueprint component style.
2. (light blue squares) We could apply lighter colors to the statistics table to be consistent with all the other tables.

Note that we have similar issue with v4.1:

Pasted Graphic 25

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: maxOS 14
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 129
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

### PR DESCRIPTION
**Pull request by YuHsuan-Hwang**
**Description**

Implemented features:

1. Closes #2446 by fixing background regressions.
    1. The menu button dark theme color is changed to the overall background color.
    2. The z profile, histogram, and spectral line query widget dark theme background is changed to a darker color, consistent with other widgets.
    3. The undocked widget dark theme background is changed to a darker color, consistent with docked widgets and dialogs. Also adjusted catalog scatter/histogram plot dark theme background and exported png file dark theme background.
2. Closes #2166 by adding scroll shadows to several widgets, including:
    1. dialogs (preference dialog, save image panel in file browser dialog, contour dialog, vector dialog, image fitting dialog, online data query dialog, region dialog)
    2. settings widgets (spatial profiler settings, spectral profiler settings, histogram settings, stokes analysis settings, catalog settings, render config settings, image view settings)
    3. PV generator widget, animator widget, render config widget options, and z profile widget legend
3. Closes #2450 and closes #2375: adjust the string colors in dark theme.
4. Closes #2451: adjust the blueprint table empty space background color and stats table background color in dark theme.
5. Fixed regression: avoid showing a horizontal scrollbar after image fitting in the image fitting dialog.
6. Increased the default width of histogram settings to avoid horizontal scrollbar easily being triggered.

Note that we might also consider disabling the shadows when the scroll bar exists, and I prefer we create a separate issue for it if necessary. (A new issue is filed.)

Code changes:

1. background related CSS changes
    1. Overwritten the menu button dark theme color.
    2. Avoided setting bp#-dark to elements which applies unnecessary additional styles in `App.scss`.
    3. For undocked widgets, changed the dark theme background color to `$pt-dark-app-background-color` in `App.scss`.
2. Created a new component `ScrollShadow` which applies scroll shadows with a pure CSS approach. There are some disadvantages with the simple approach but most of them look minor:
    1. The shadow is implemented in the background. Input columns and buttons are displayed on top of it.
    2. Does not support custom background color. Currently, we only deal with two background colors (light and dark theme).
    3. In Safari and Firefox, we temporally see the shadows when scrolling to the end because of the interaction design.
3. CSS changes: Changed the string colors in dark theme.
4. CSS changes: Overwritten blueprint table dark theme background color. The tables in file browser and work space dialogs are set to a lighter color to display the border of the panel. Changed the stats table dark theme background colors.

Tested that:

1. UI in the dark mode looks clear with the new background.
2. The background colors in the light mode are unchanged.
3. The shadows do not create double scroll bars.
4. The shadows are responsive to the theme.
5. Responsive UI in the animator and render config widget works as usual.

There are some failed e2e tests, to be investigated.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] GitHub Project estimate added

For the pull request:
- [x] reviewers and assignee added
- [x] GitHub Project estimate added
- [ ] changelog updated / ~no changelog update needed~
- [x] ~unit test added (for functions with no dependenies)~
- [x] ~API documentation added (for public variables and methods in stores)~

For dependencies:
- [x] e2e test passing / corresponding fix added / ~new e2e test created~
- [x] ~protobuf version bumped~ / no protobuf version bumped needed
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] ~corresponding ICD test fix added (`BackendService` changed)~ / no ICD test fix needed (`BackendService` unchanged)
- [x] ~user manual prepared (for large new features)~

### CODE REVIEW

**Comment by YuHsuan-Hwang** [comment]
Update: Fixed #2450 and #2451. The details are updated in the description.

**Review by loveluthien — APPROVED** [review]
looks very good.

**Comment by kswang1029** [comment]
Few comments:
1. missing shadow in "render configuration settings dialog" and "image view settings dialog"
2. the horizontal scrollbar blocks the shadow in the "histogram settings dialog" when we disable auto pixel bounds/bins. maybe we should make the default dialog width wider.
Screenshot 2024-12-24 at 10 55 06
3. (observed in dev and this PR, but not v4.1) after image fitting, the dialog shows a horizontal scrollbar. Do you think we can fix this in this PR as well?
Screenshot 2024-12-24 at 10 45 21
4. we should try to disable the shadow effect when scrollbar shows up in a separate PR.

**Review by kswang1029 — CHANGES_REQUESTED** [review]
see comments in the thread.

**Comment by YuHsuan-Hwang** [comment]
@kswang1029 Thanks for testing the UI in detail.

> 1. missing shadow in "render configuration settings dialog" and "image view settings dialog"

Added shadows to render config settings and panels in image view settings.

> 2. the horizontal scrollbar blocks the shadow in the "histogram settings dialog" when we disable auto pixel bounds/bins. maybe we should make the default dialog width wider.

Fixed by increasing the default width of histogram settings.

> 3. (observed in dev and this PR, but not v4.1) after image fitting, the dialog shows a horizontal scrollbar. Do you think we can fix this in this PR as well?

Fixed by adjusting CSS.

> 4. we should try to disable the shadow effect when scrollbar shows up in a separate PR.

Filed a new issue #2453.

**Review by kswang1029 — APPROVED** [review]
looks good. e2e tests are fixed accordingly.

**Pull request merged**
