### PR TITLE
Yuhsuan/2106 fk4 plot

### LINKED ISSUE #2106: incorrect FK5-2000 and FK4-1950 pair grid line rendering
**Describe the bug**
This issue is found while testing the swapped axes PRs.

The issue is when we load a FK5(2000) image and switch to FK4(1950) grid, the rendered grid line is incorrect. Same happens when we load a FK4(1950) image and switch to FK5(2000) grid. Fortunately spatial matching is not affected as it seems it takes both RADESYS and EQUINOX header into account. 

As a note here, when we render AST grid line, we will need to quote both RADESYS and EQUINOX. If EQUINOX is missing from the header, we set it as 2000 for RADESYS=FK5 and 1950 for RADESYS=FK4. ICRS, GALACTIC, and ECLIPTIC systems do not need an EQUINOX.

Test images are available from https://drive.google.com/file/d/18LkunUi_c-5P1j_F3I1Jrr--zSxlp4dM/view?usp=share_link

in the image "binary_FK5.image", the center source is at J2000 10h00m00s, +10d00m00s. The one at the corner is at B1950 10h00m00s, +10d00m00s. So if we switch to the FK4 grid, we should see the corner source is at 10h00m00s, +10d00m00s grid intersect. Instead, we see the grid shift is quite small. I suspect this is because we did not specify EQUINOX for AST so it renders FK4(2000) not FK4(1950). Please check if EQUINOX is set properly in this case.

In the following screenshot, we see images are properly matched spatially. But the rendered grid line (FK4) is incorrect on the left panel which is a FK5(2000) image.

tmp

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Monterey 
 - Browser [e.g. chrome, safari, electron app]: v3-stable electron app
 - Browser version [e.g. 22]: v3-stable electron app
 - Backend branch [e.g. dev, v3b2 release]: v3-stable
 - Frontend branch [e.g. dev, v3b2 release]: v3-stable

**Additional context**

### PR DESCRIPTION
**Pull request by YuHsuan-Hwang**
**Description**

Fixes #2106. Added an Equinox argument to the AST plot ~when the system is FK4~. Set equinox to 1950 for FK4, and 2000 for the others. When the system is "Auto", equinox should follow the header.

Also adjust the tooltip to show ecliptic coordinates is in equinox 2000.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] e2e test passing / ~corresponding fix added~
- [x] changelog updated / ~no changelog update needed~
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] `BackendService` unchanged / ~`BackendService` changed and corresponding ICD test fix added~

### CODE REVIEW

**Review by kswang1029 — CHANGES_REQUESTED** [review]
@YuHsuan-Hwang please refer to the following video. The image on the right (matched one) behaves correctly when we switch the WCS between FK5 and FK4. But the image on the left does not. We should see the source is at (10h, 10d) when it is FK4. When it is FK5, it should be something else. Currently the difference is very small. I suspect we also need to explicitly define an equinox for FK5 as 2000. So in short, FK4 equinox 1950 and FK5 equinox 2000.


https://user-images.githubusercontent.com/20819712/224052600-54fbb926-52f4-4e02-80c2-6ef15286a41f.mov

**Comment by kswang1029** [comment]
> @YuHsuan-Hwang please refer to the following video. The image on the right (matched one) behaves correctly when we switch the WCS between FK5 and FK4. But the image on the left does not. We should see the source is at (10h, 10d) when it is FK4. When it is FK5, it should be something else. Currently the difference is very small. I suspect we also need to explicitly define an equinox for FK5 as 2000. So in short, FK4 equinox 1950 and FK5 equinox 2000.

fixed with [d07f03a](https://github.com/CARTAvis/carta-frontend/pull/2115/commits/d07f03a53574ad799e140bb0f0433f0b69a0cae3)

**Comment by YuHsuan-Hwang** [comment]
@kswang1029 Thanks for fixing!

**Comment by YuHsuan-Hwang** [comment]
New changes:
* set equinox to 1950 for FK4, and 2000 for others
* adjust tooltip to show ecliptic coordinates is in equinox 2000

**Review by kswang1029 — APPROVED** [review]
this looks good. no regression from e2e tests. new e2e tests to be implemented.

**Comment by kswang1029** [comment]
code review may proceed.

**Review by crocka — APPROVED** [review]

**Pull request merged**
