### PR TITLE
Display full major/minor instead of semi-major/minor

### LINKED ISSUE #862: reported axes dimensions for regions
Looks like the axes dimensions in the region edit widget is reporting semi-major axes but listed as maj: and min:  Should change the values to major and minor axes. 

Screenshot 2020-04-06 at 09 43 02

### PR DESCRIPTION
**Pull request by duidae**
closes #862 

will create backport PR for 1.3 patch release if this PR is ok

### CODE REVIEW

**Comment by veggiesaurus** [comment]
Code looks fine to me. Can merge once @kswang1029 approves

**Comment by kswang1029** [comment]
hmm the issue is getting weird... See the gif. The size changes when we just click the text field.
Apr-17-2020 13-30-29

**Comment by duidae** [comment]
@kswang1029  oops, sorry for missing adjustment. Fixed.

**Comment by kswang1029** [comment]
The sizes in the region dialogue are correct now. However in the region list the sizes are still half. Also, when exporting to region files (both casa and ds9 format, both world and image coordinates), the sizes are half too. 
Screen Shot 2020-04-20 at 1 12 44 PM

**Pull request closed without merging**
