### PR TITLE
updating help manual for release 1.4

### PR DESCRIPTION
**Pull request by kswang1029**
PR to the release/1.4 branch

The help manual is updated mostly. Please check. @veggiesaurus @confluence @TienHao

### CODE REVIEW

**Review by TienHao — APPROVED** [review]

**Review by confluence — APPROVED** [review]
I would like to do a more complete pass over the wording of these messages, but that's not limited to these changes and I think outside the scope of this PR.

**Comment by kswang1029** [comment]
I am fixing the line wrapping issue now. Please wait.

**Comment by kswang1029** [comment]
Fixed with b14a1f0

**Comment by veggiesaurus** [comment]
backported from #1205 instead, closing this PR and branch

**Pull request closed without merging**
