### PR TITLE
add overlay visible state

### LINKED ISSUE #2341: Hide AST overlay with scripting
It would be convenient for testing if we can hide the AST overlay with scripting.

### PR DESCRIPTION
**Pull request by YuHsuan-Hwang**
**Description**

Closes #2341. Add a variable for hiding/showing the AST overlay. The overlay can be hidden/shown by
```js
app.overlayStore.setVisible(false/true);
```

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] ~changelog updated~ / no changelog update needed
- [x] ~unit test added (for functions with no dependenies)~
- [x] API documentation added (for public variables and methods in stores)

For dependencies:
- [x] e2e test passing / ~corresponding fix added / new e2e test created~
- [x] ~protobuf version bumped~ / no protobuf version bumped needed
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] ~corresponding ICD test fix added (`BackendService` changed)~ / no ICD test fix needed (`BackendService` unchanged)
- [x] ~user manual prepared (for large new features)~

### CODE REVIEW

**Review by kswang1029 — APPROVED** [review]
This looks good. No regression from e2e tests as expected. 

I tested browser refreshing rate (fps) by loading four images and matching them one by one. Still I see fps dropping when we have more images matched, even with AST overlay turned off. This performance degradation is observed with MBP's 120 Hz retina screen. However, with a regular 60Hz non-retina screen, I do not see such performance degradation (still 60Hz when panning with 4 images matched).

**Comment by loveluthien** [comment]
Do we have a toggle button for this? Maybe people want a "clean" picture for non-scientific purposes.

**Review by loveluthien — APPROVED** [review]
It is nice.

**Comment by YuHsuan-Hwang** [comment]
> Do we have a toggle button for this? Maybe people want a "clean" picture for non-scientific purposes.

Currently we don't have UI for it. There is an alternative way by setting every part of the overlay invisible and ticks width to 0.001. Not sure if this is widely used, so I suggest we implement it if we receive user requests in the future.

**Review by crocka — APPROVED** [review]

**Pull request merged**
