### PR TITLE
Fix dark mode issue

### LINKED ISSUE #1131: color theme mismatch
beta test feedback: 
Screen Shot 2020-08-19 at 10 06 44 PM

### PR DESCRIPTION
**Pull request by duidae**
close #1131

### CODE REVIEW

**Comment by kswang1029** [comment]
@duidae this looks good. I also spotted a number of places having this issue.

when a session is resumed:
Screen Shot 2020-08-20 at 9 22 55 AM

when we close an image as the spatial reference:
Screen Shot 2020-08-20 at 9 20 58 AM

when trying to save the 11th layout:
Screen Shot 2020-08-20 at 9 20 23 AM

When requesting cube histogram:
Screen Shot 2020-08-20 at 9 18 38 AM

When launch the online user manual:
Screen Shot 2020-08-20 at 9 30 31 AM



The "control and shortcut" is alway dark, independent of the theme.
Screen Shot 2020-08-20 at 9 32 35 AM

**Comment by duidae** [comment]
ok fixed.

**Review by kswang1029 — APPROVED** [review]
all fixed! 🥇

**Review by veggiesaurus — APPROVED** [review]
This looks low risk. @kswang1029 shall we backport this?

**Comment by kswang1029** [comment]
@veggiesaurus yes please.

**Pull request merged**
