### PR TITLE
Update to latest MobX version and enable strict mode

### LINKED ISSUE #1139: [2.0 suggestion] usestrict for mobx
switch to strict mode for solid code

### PR DESCRIPTION
**Pull request by veggiesaurus**
closes #1139 

This PR is the first of a few "chore" PRs to get our dependencies up to date. The major change is that MobX is now version 6. This means that we have to manually run `makeObservable` during object construction. 

I've used the opportunity to split the widget config into an _interface_ (for storing the default widget config) and a class (for storing the actual widget config with observables).

I've also enabled MobX's strict mode, so `@observable` properties can only be changed from inside an `@action`. Currently, MobX spits out an error in the console if properties are changed outside of an action. 

@kswang1029 please can you test and see if you can find any situations where: 
1. Things don't seem to respond properly or are broken (this might be me missing a `makeObservable` somewhere)
2. The console creates warnings that look like 
```MobX] Since strict-mode is enabled, changing (observed) observable values without using an action is not allowed. Tried to modify: ImageViewSettingsPanelComponent@364.selectedTab```

### CODE REVIEW

**Review by duidae — APPROVED** [review]

**Comment by kswang1029** [comment]
@veggiesaurus I will try to perform some tests and report back by this week.

**Review by panchyo0 — APPROVED** [review]

**Comment by veggiesaurus** [comment]
some additional package changes, @duidae can you have another look quickly?

**Review by duidae — APPROVED** [review]

**Comment by duidae** [comment]
tried rebuliding it, seems working good.

**Comment by kswang1029** [comment]
found an issue that does not exist in dev.
When resizing a floating widget, its position is changed toward the top side and eventually we cannot close it XD
Oct-23-2020 10-51-36

**Comment by kswang1029** [comment]
When unpin a docked widget, its aspect ratio changes unexpectedly. Please try to undock render config widget or image list widget and see the issue.

**Comment by kswang1029** [comment]
@veggiesaurus Except the above two issues I spotted while testing this branch, others seem to work fine as far as I can see. We probably can merge this PR first and I will keep an eye on it for abnormal things.

**Comment by veggiesaurus** [comment]
I'll try sort out those weird issues, and then I'll merge.

**Comment by veggiesaurus** [comment]
@kswang1029 can you give this another quick check to confirm that those two issues have been fixed?

**Comment by veggiesaurus** [comment]
confirmed working on mix 'n match

**Comment by kswang1029** [comment]
sorry for the late response. Yes, confirmed the two issues are fixed! 👍

**Pull request merged**
