### PR TITLE
Yuhsuan/1397 fov fitting

### PR DESCRIPTION
**Pull request by YuHsuan-Hwang**
**Description**
This PR is for the 6th item in #1397: image fitting with field of view.

changes:
* added calculations of the current fov by using the center and zoom level of the frame.
* added calculations for checking if the current fov includes the entire image.
* added info (in region format) of the applied fov in the fitting log.
* refactored `regionStore.regionProperties` and `FrameStore.getRegionWcsProperties` to reuse the formatting code for fov info.
* added disabled region dropdown.

tested:
* Regions created by the fov info in the fitting log shows the applied fov.
* Fitting the current fov is equivalent to fitting a saved subimage of the fov region (with shifted initial center values).
* The region id is set to -1 if the current fov includes the entire image.
* The result does not change if we fit the current fov right after exporting a high resolution png.
* Returns error `Image fitting failed: insufficient data points` if image data num < 6 * component num.
* Returns error `Image fitting failed: region is outside image or is not closed` if the current fov is blank.

Corresponding PRs:
https://github.com/CARTAvis/carta-backend/pull/1128
https://github.com/CARTAvis/carta-protobuf/pull/74

**Checklist**
- [x] changelog updated / ~no changelog update needed~
- [X] e2e test passing / added corresponding fix
- [x] protobuf updated to the latest dev commit / ~no protobuf update needed~

### CODE REVIEW

**Comment by YuHsuan-Hwang** [comment]
update: added disabled region dropdown
image

**Comment by kswang1029** [comment]
@YuHsuan-Hwang with the new region dropdown, we need to have a greater _default_ height to show P.A. textbox. 
Screen Shot 2022-06-21 at 12 26 02

Other than that, it works fine as far as I can tell. @veggiesaurus @TienHao please proceed with code review. I will work on e2e test revision due to UI change.

UPDATE: updated e2e tests and added two tests for fov fitting.

**Comment by YuHsuan-Hwang** [comment]
> @YuHsuan-Hwang with the new region dropdown, we need to have a greater default height to show P.A. textbox.

@kswang1029 fixed by removing some margins and slightly decreasing the height of the result column

**Review by kswang1029 — APPROVED** [review]
via e2e tests, no regression is observed in [1365ac8](https://github.com/CARTAvis/carta-frontend/pull/1885/commits/1365ac8738fe32f9eb794b1b5dda08df37779dcc). Some manual tests were performed and they looked fine as far as I can tell.

**Review by veggiesaurus — APPROVED** [review]

**Comment by veggiesaurus** [comment]
@confluence and I will coordinate the PR merges when we both have electricity :facepalm:

**Pull request merged**
