### PR TITLE
Yuhsuan/2314 telemetry dialog display

### LINKED ISSUE #2314: Avoid showing the telemetry dialog temporarily (carta-controller only)
**Describe the bug**
When launching Carta with carta-controller, we see the telemetry dialog temporarily.

**To Reproduce**
1. Launch Carta with carta-controller
2. See the telemetry dialog temporarily

**Expected behavior**
No telemetry dialog shown.

**Screenshots or videos**
Screen Recording 2023-12-13 at 2 06 04 PM

With Slow-3G network option in Chrome Develop tools:
Screen Recording 2023-12-13 at 12 35 11 PM
(The buttons are clickable, but I did not click them.)

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: server with carta-controller
 - Browser [e.g. chrome, safari, electron app]: Chrome
 - Browser version [e.g. 22]: 119
 - Backend branch [e.g. dev, v3b2 release]: v4
 - Frontend branch [e.g. dev, v3b2 release]: v4

### PR DESCRIPTION
**Pull request by YuHsuan-Hwang**
**Description**

Fixed #2314. Check if the preference data is initialized before showing the dialog.
Also removed unused variable `supportsServer`.

Tested that:
* (without carta-controller) The dialog is not shown temporarily (behind the splash screen) when the preference file contains "telemetryConsentShown: true".
* (without carta-controller) The dialog is shown when there is no preference file, or when the preference file does not contain "telemetryConsentShown", or when the preference file contains "telemetryConsentShown: false".
* (with carta-controller) The dialog is not shown temporarily.

~To be tested with carta-controller.~
Update: tested with carta-controller, thanks to help from @ajm-asiaa.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] changelog updated / ~no changelog update needed~
- [x] ~unit test added (for functions with no dependenies)~
- [x] API documentation added (for public variables and methods in stores)

For dependencies:
- [x] e2e test passing / corresponding fix added / ~new e2e test created~
- [x] protobuf version bumped / ~no protobuf version bumped needed~
- [x] protobuf updated to the latest dev commit / ~no protobuf update needed~
- [x] ~corresponding ICD test fix added (`BackendService` changed)~ / no ICD test fix needed (`BackendService` unchanged)
- [x] ~user manual prepared (for large new features)~

### CODE REVIEW

**Comment by YuHsuan-Hwang** [comment]
Update: tested with carta-controller, thanks to help from @ajm-asiaa.

**Review by kswang1029 — APPROVED** [review]
This looks fine as far as I can tell without a controller. In the fix, is the telemetry popup web element only created when it is necessary? Due to this, a few e2e tests related to catalog image overlay rendering need a fix due to xpath shift (eg `xpath:/html/body/div[9]...` -> `xpath:/html/body/div[8]/...`.

**Comment by YuHsuan-Hwang** [comment]
> This looks fine as far as I can tell without a controller.

I tested with carta-controller, and it looks fine.

> In the fix, is the telemetry popup web element only created when it is necessary? Due to this, a few e2e tests related to catalog image overlay rendering need a fix due to xpath shift (eg `xpath:/html/body/div[9]...` -> `xpath:/html/body/div[8]/...`.

Yes, I think this is what we expected.

**Review by loveluthien — APPROVED** [review]
It goods good.

**Review by crocka — APPROVED** [review]

**Pull request merged**
