### PR TITLE
Adding toolbar for dialogs

### LINKED ISSUE #642: toolbar for dialogs
we should have a separate "dialogs" toolbar at the top near the widgets. We can have buttons for preferences, file info, overlay config, contour config and so on.

### PR DESCRIPTION
**Pull request by TienHao**
closes [#642](https://github.com/CARTAvis/carta-frontend/issues/642):toolbar for dialogs 
Add toolbar for dialogs on the right of widgets.

### CODE REVIEW

**Review by veggiesaurus — COMMENTED** [review]
Do you think we should move all of the various dialogs into one component, instead of littering the `App` component with them?

e.g. moving this chunk of text to a separate component:
```
                <SplashScreenComponent appStore={appStore}/>
                <RootMenuComponent appStore={appStore}/>
                <OverlaySettingsDialogComponent appStore={appStore}/>
                <AuthDialogComponent appStore={appStore}/>
                <FileBrowserDialogComponent appStore={appStore}/>
                <AboutDialogComponent appStore={appStore}/>
                <RegionDialogComponent appStore={appStore}/>
                <PreferenceDialogComponent appStore={appStore}/>
                <SaveLayoutDialogComponent appStore={appStore}/>
                <FileInfoDialogComponent appStore={appStore}/>
                <ContourDialogComponent appStore={appStore}/>
```

**Comment by veggiesaurus** [comment]
@duidae I'd forgotten that we'd asked @TienHao to do this :laughing: 

Where does that leave #209?

**Comment by TienHao** [comment]
@veggiesaurus : Yeah, that should be great. I will create a new component to put them.

**Review by veggiesaurus — APPROVED** [review]
looks good!

**Pull request merged**
