### PR TITLE
Fix crash issue

### LINKED ISSUE #1598: region list widget crash and frontend crash
It appears that if the initial width or the width after resizing is greater than a threshold, the region list widget will crash. Launching a new region list from the widget bar will cause the frontend crash.

https://user-images.githubusercontent.com/20819712/128280007-40452e8f-1e54-4992-b9be-885218603d7c.mov

Screen Shot 2021-08-05 at 10 10 45 AM

### PR DESCRIPTION
**Pull request by duidae**
closes #1598

### CODE REVIEW

**Comment by duidae** [comment]
btw, @YuHsuan-Hwang in line 157 of the `else` statement:

sizeContent = region.regionType === CARTA.RegionType.LINE ? toFixed(length2D(region.wcsSize), 1) : ...
                   
                    
 wanna make sure is it toFixed(length2D(region.`wcsSize`) or toFixed(length2D(region.`size`)?

**Comment by kswang1029** [comment]
> btw, @YuHsuan-Hwang in line 157 of the `else` statement:
> 
> sizeContent = region.regionType === CARTA.RegionType.LINE ? toFixed(length2D(region.wcsSize), 1) : ...
> 
> wanna make sure is it toFixed(length2D(region.`wcsSize`) or toFixed(length2D(region.`size`)?

making a line region would crash the region widget. might be related.

Screen Shot 2021-08-10 at 11 12 52 AM

**Comment by YuHsuan-Hwang** [comment]
> btw, @YuHsuan-Hwang in line 157 of the `else` statement:
> 
> sizeContent = region.regionType === CARTA.RegionType.LINE ? toFixed(length2D(region.wcsSize), 1) : ...
> 
> wanna make sure is it toFixed(length2D(region.`wcsSize`) or toFixed(length2D(region.`size`)?

Yes, should be `toFixed(length2D(region.size)`

**Comment by duidae** [comment]
ok fixed.

**Comment by kswang1029** [comment]
> > btw, @YuHsuan-Hwang in line 157 of the `else` statement:
> > sizeContent = region.regionType === CARTA.RegionType.LINE ? toFixed(length2D(region.wcsSize), 1) : ...
> > wanna make sure is it toFixed(length2D(region.`wcsSize`) or toFixed(length2D(region.`size`)?
> 
> making a line region would crash the region widget. might be related.
> 
> Screen Shot 2021-08-10 at 11 12 52 AM

confirmed that this is related to #1572 . with ALMA image cubes, it works fine.

**Review by kswang1029 — APPROVED** [review]
Thanks for the quick fix~

**Review by veggiesaurus — APPROVED** [review]

**Pull request merged**
