### PR TITLE
Normalize directory and filename in loadFile using a path library

### LINKED ISSUE #1357: Casa image paths saved incorrectly in workspaces if images added via snippets with a trailing slash
**Describe the bug**

If a casa image is opened via a snippet with a path which has a trailing space (something that can easily happen if the path was copied from the commandline after tab autocompletion), the image is *opened* correctly, but when the workspace is *saved* the name of the image is duplicated at the end of the directory path. This means that when the workspace is loaded the image cannot be opened. This happens because the image's directory is incorrectly set in the metadata when it is opened.

**To Reproduce**

1. Open a casa image with snippets, with and without a trailing slash:
```
# without slash
await app.openFile("/home/adrianna/data/casa/test.image");
# with slash
await app.appendFile("/home/adrianna/data/casa/test.image/");
```
2. Save the workspace.
3. Try to load the workspace.
4. If you reproduce this on a local backend (with objects saved as files), you can easily inspect the workspace file and see that the images are saved as follows:
```
# without slash
"directory": "/home/adrianna/data/casa",
"filename": "test.image",

# with slash
"directory": "/home/adrianna/data/casa/test.image",
"filename": "test.image",
```
**Expected behavior**

Both images should be saved with the same correct path.

**Platform info (please complete the following information):**

This has been reproduced on Ubuntu Jammy (controller installation saving to a database) and Ubuntu Focal (local installation saving to file). It was present in 4.0 and is still present in 4.1.

**Additional context**

The directory is set incorrectly in the metadata when the image is opened -- you can compare the two open images with snippets:
```
# Snippet code:
console.log(app.frames[0].frameInfo.directory);
console.log(app.frames[1].frameInfo.directory);

# Result:
09:51:12.574 /home/adrianna/data/casa
09:51:12.575 /home/adrianna/data/casa/test.image
```

### LINKED ISSUE #1816: Opening a CASA image with a trailing / using the URL parameter doesn't work properly
**Describe the bug**
@Jordatious found this issue. If you open a CASA image using the `?file=<CASA image path>/` (note trailing slash), then odd things happen:

- The current folder gets set to the _inside_ of the CASA image, rather than the containing directory
- Resuming sessions seems to break

**To Reproduce**
1. Go to a CARTA browser instance and add `?file=<CASA image path>/`
2. Open the file browser. The starting folder will be incorrect.
3. Resume the session after disconnecting. This will fail.

**Expected behavior**
Resuming should work, and the file browser should start in the containing folder, rather than the image folder.

### PR DESCRIPTION
**Pull request by confluence**
**Description**

This fixes [backend bug #1357](https://github.com/CARTAvis/carta-backend/issues/1357) and #1816 by using (the browser port of) node's `path` module to normalize the directory and filename in the `loadFile` function.

The library correctly handles edge cases such as the one causing the bug. Since it's already available to us as a dependency, I would recommend making use of it instead of hand-coding path parsing (which is error-prone!). The browser version only implements posix paths, which I think is what we always need.

Step by step instructions for reproducing the backend bug can be found [in the bug's description](https://github.com/CARTAvis/carta-backend/issues/1357#issue-2107173165). ~I have not yet tested the issue in #1816, but I believe that it has the same underlying cause.~ I have confirmed that this also fixes #1816 (or at least I can see that it prevents the initial incorrect image request which later causes errors).

Outstanding questions:

1. I'm not sure if I'm importing `path-browserify` in the optimal way. It's [intended to be imported as `path`](https://github.com/browserify/path-browserify), because it's the browser port of node's `path` module, and webpack is supposed to provide it as a fallback transparently. I know that webpack 5 no longer sets this up automatically, and it looks like we have a fix for this in a patch -- but when I attempt to import `path`, I get an error about `path-browserify` being outside the `src` tree. This doesn't happen when I import `path-browserify` directly, and doesn't happen with other dependencies in `node_modules`. I'm not sure if this is some weird interaction with the alias, and I haven't been able to find a solution. @veggiesaurus, is there a piece missing somewhere?
2. This code always performs the same normalization step, regardless of what the original directory and filename parameters are. This includes cases where the directory is empty and the filename does not contain a slash (which are skipped in the previous code). The effect of this is to change the directory to `"."`. I did some tests in the previous code, and from what I understand, a directory which is `""` or `"."` is evaluated as the top-level directory. Is that correct? If that's the case, then changing `""` to `"."` shouldn't make a difference.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] changelog updated / no changelog update needed
- [x] unit test added (for functions with no dependenies)
- [x] API documentation added (for public variables and methods in stores)

For dependencies:
- [x] e2e test passing / corresponding fix added / new e2e test created
- [X] ~protobuf version bumped~ / no protobuf version bumped needed
- [X] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] corresponding ICD test fix added (`BackendService` changed) / no ICD test fix needed (`BackendService` unchanged)
- [x] user manual prepared (for large new features)

### CODE REVIEW

**Review by YuHsuan-Hwang — APPROVED** [review]
Looks good to me.

**Comment by confluence** [comment]
I'm moving this out of draft -- I think it's up to frontend devs whether the import needs to be changed or is fine as-is. Either way this should probably be tested.

**Review by kswang1029 — APPROVED** [review]
Tested the URL cases
http://localhost:3002/?file=/Users/kswang/set_QA_e2e_v2/M17_SWex.image
http://localhost:3002/?file=/Users/kswang/set_QA_e2e_v2/M17_SWex.image/
and both work fine.

Tested the snippet case and workspace and it works fine with the fix. 

No regression from e2e tests.

**Comment by YuHsuan-Hwang** [comment]
We install `path-browserify` directly without adding alias after upgrading to react-script v5, so the import looks fine to me.

**Pull request merged**
