### PR TITLE
show dashboard link when appropriate

### LINKED ISSUE #1874: Add a link to the dashboard on the splash screen
There are some situations where the user gets stuck at the splash screen (e.g. the backend has crashed or locked up, or their authentication is invalid). It would be useful to add a link to the dashboard (in situations where there _is_ a dashboard, i.e. in SDM) to this splash screen.

Suggested by @Jordatious after feedback from IDIA users

### PR DESCRIPTION
**Pull request by veggiesaurus**
**Description**
Closes #1874. Shows dashboard links if the runtime config defines a dashboard address.

image
image

**Checklist**
- [x] changelog updated / ~~no changelog update needed~~
- [ ] e2e test passing / added corresponding fix
- [x] ~~protobuf updated to the latest dev commit~~ / no protobuf update needed

### CODE REVIEW

**Comment by Jordatious** [comment]
Look amazing! Can I test this somewhere? Not seeing it on mix n' match.

**Comment by veggiesaurus** [comment]
> Look amazing! Can I test this somewhere? Not seeing it on mix n' match.

mix 'n match doesn't have a dashboard associated with it, so the links won't show up. I guess we'll have to put it on carta-testing to test (or I can deploy to my personal server for a brief test)

**Comment by Jordatious** [comment]
Ok cool, let me know!

**Comment by kswang1029** [comment]
@veggiesaurus  I am not able to set this up with my dev environment. I would rely on @Jordatious to test this, if this is okay. 

Just one very minor cosmetics and biased personal taste (meaning you can ignore it 🙂), I would prefer to center “CARTA dashboard” link on the splash screen and maybe have it as a button just like the one in popup window.

**Comment by Jordatious** [comment]
I'm ready to test this once you are! I do think people won't necessarily click the link unless it's clear it will solve their connection issues, as per my suggestion in #1874. I also like @kswang1029's suggestion for a pop-up if there's a timeout, where it would be more obvious to the user that they should open their dashboard. Will that automatically be detected every time?

**Comment by veggiesaurus** [comment]
@YuHsuan-Hwang has helped me do the functional testing. 

@Jordatious I've adjusted the text to indicate that they should visit the dashboard if facing connection problems:
image

(or centered)
image


This is the alternative that @kswang1029 suggested:
(right-aligned)
image

(centered)
image


My personal preference is the centred link rather than button. But happy to go with what @kswang1029  and @Jordatious prefer.

**Comment by kswang1029** [comment]
vote for centred link 👍

**Comment by veggiesaurus** [comment]
> vote for centred link 👍 

Oh good, that's what the pr currently does 😊

**Comment by Jordatious** [comment]
I vote for the text link, so it's clear users should click on the dashboard if there are connection issues. I still prefer [this](https://github.com/CARTAvis/carta-frontend/issues/1874#issuecomment-1144791762), but @veggiesaurus mentioned that would require more work. So I vote for text for now! I prefer right justified, but I don't feel (too) strongly about it!

**Review by Jordatious — APPROVED** [review]

**Review by YuHsuan-Hwang — APPROVED** [review]

**Pull request merged**
