### PR TITLE
carli/1790_jumpy_pv_image

### PR DESCRIPTION
**Pull request by crocka**
**Description**

A ``reaction`` in ``RegionViewComponent.tsx`` watches for changes in ``frame`` and runs ``syncStage`` when ``frame`` changes. ``syncStage`` would incorrectly set the origin for PV images, so to fix the problem, a ``frame.aspectRatio`` is multiplied to the x element of the origin. This PR closes issue #1790.

The changes in ``RegionViewComponent.tsx`` ``handleWheel`` function was because I found that the ``FrameStore.getCursorInfo`` does not change the ``cursorPosImageSpace`` argument. Therefore, ``cursorImageSpace`` is exactly the same as ``cursorInfo.posImageSpace``.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] e2e test passing / corresponding fix added
- [x] ~~changelog updated~~ / no changelog update needed
- [x] ~~protobuf updated to the latest dev commit~~ / no protobuf update needed
- [x] `BackendService` unchanged / ~~`BackendService` changed and corresponding ICD test fix added~~

### CODE REVIEW

**Comment by kswang1029** [comment]
initial manual tests are looking good. No regression is observed from e2e tests. I will have another look sometime soon. Please proceed code review.

**Review by YuHsuan-Hwang — APPROVED** [review]
Good work on the fix. Thanks for looking into the issue!

**Comment by YuHsuan-Hwang** [comment]
We will need change log update because this exists in release versions.

**Review by kswang1029 — CHANGES_REQUESTED** [review]
mostly this works properly and no regression is seen from e2e tests.

The catalog image overlay is affected when the image pixel is not square. Guessing there is a missing image-pixel-ratio scaling factor?

v3-stable
image_x_3_y_1 fits-image-2023-02-22-11-32-15

this PR
image_x_3_y_1 fits-image-2023-02-22-11-32-08

**Comment by kswang1029** [comment]
the above issue exists in dev so it is nothing to do with this PR.

**Review by kswang1029 — APPROVED** [review]
👍 mystery busted

**Comment by YuHsuan-Hwang** [comment]
@crocka This is ready for merge 👍  Please update the change log, thanks.

**Pull request merged**
