### PR TITLE
Jason/fix 168

### PR DESCRIPTION
**Pull request by duidae**
closes https://github.com/CARTAvis/carta-frontend/issues/168

### CODE REVIEW

**Comment by veggiesaurus** [comment]
@kswang1029 this solves the jumpy cursor by displaying the _required channel_, rather than the currently displayed channel. However, do you think we should also show the currently displayed one on the graph if they are different?

**Comment by kswang1029** [comment]
Good idea. Maybe with different transparency?

**Comment by veggiesaurus** [comment]
It looks pretty odd with the extra marker: 
show_req_current_channels

Not sure what to do, really. On the one hand, the slider is not great if you use the current channel (jumpy) and on the other hand, if you use the required channel, you aren't displaying a marker indicating which channel is actually displayed, which may lead to confusion. 

The two was around this I can think of are:
1. Display a marker for the current channel as well (see attached, looks a bit weird)
2. Disable dragging of the marker entirely, and just allow the user to click on the channel to move the marker. Which would be annoying, as @duidae has put a fair bit of time and effort into this, and it's mostly great.

@kswang1029 any other ideas?

**Comment by kswang1029** [comment]
I suggest “current” so that the values will be consistent with the values in other widgets (cursor info bar in viewer, xy profilers).

**Comment by arusstaylor** [comment]
Is dragging the marker the only way to change the channel with the marker?  The most common use case for this is to be able to click on a feature in the profile and have the channel change.  Therefore need to be able to change the channel just with a click.

Russ

**Comment by kswang1029** [comment]
@arusstaylor I think now we have both: dragging to change channels and clicking to jump to a certain channel. @veggiesaurus @duidae could you confirm?

**Comment by veggiesaurus** [comment]
@arusstaylor yes, you can left click to move the marker

**Pull request merged**
