### PR TITLE
Yuhsuan/issue 1037 export selected region

### LINKED ISSUE #1037: support exporting selected regions only
Need to say "export all items" or show a list of regions for the user to select/deselect / right-click on a region and go to export just for that region.

### PR DESCRIPTION
**Pull request by YuHsuan-Hwang**
This PR closes https://github.com/CARTAvis/carta-frontend/issues/1037: exporting selected regions from the file browser dialog.
Supports multiple selection. Changing the active image resets the selection.

### CODE REVIEW

**Comment by YuHsuan-Hwang** [comment]
Changing to tab element based on @kswang1029 's suggestion.

**Comment by YuHsuan-Hwang** [comment]
@kswang1029 Added a new tab for selecting regions.

**Comment by veggiesaurus** [comment]
I haven't looked at the code yet, but I do wonder whether we can easily extend this at a later stage to actually allow users to select multiple regions in the image view widget or region list

**Comment by kswang1029** [comment]
> I haven't looked at the code yet, but I do wonder whether we can easily extend this at a later stage to actually allow users to select multiple regions in the image view widget or region list

We need to be careful about this due to Active and linked behavior…🤔

**Comment by YuHsuan-Hwang** [comment]
> I haven't looked at the code yet, but I do wonder whether we can easily extend this at a later stage to actually allow users to select multiple regions in the image view widget or region list

In my current implement, this multiple selection is totally different from multiple active regions. This export selection looks for the index in the active image rather than id (reset easily by switching the active image).

**Review by kswang1029 — APPROVED** [review]
Feature-wise this is good. 👍

**Review by veggiesaurus — APPROVED** [review]

**Pull request merged**
