### PR TITLE
fixes #1053

### LINKED ISSUE #1053: selecting texts with cursor in the file info box has an offset
In other words, it seems we cannot select the correct row of texts, where the cursor is pointing at.
Jul-22-2020 11-11-40

### PR DESCRIPTION
**Pull request by veggiesaurus**
Not entirely sure why I added the 15px padding to start with... @kswang1029 please check for weird rendering behaviour on Safari. Looks fine to me on Chrome and FF

### CODE REVIEW

**Review by kswang1029 — COMMENTED** [review]
This fixes the selection problem. I think with padding it looks nicer however.
was
Screen Shot 2020-08-26 at 9 41 36 AM
now
Screen Shot 2020-08-26 at 9 41 58 AM

**Comment by veggiesaurus** [comment]
> This fixes the selection problem. I think with padding it looks nicer however.

Unfortunately the padding is what was causing the selection offset. I'll see how else I can fix it :thinking:

**Comment by veggiesaurus** [comment]
@kswang1029 please retest with `0150649`

**Review by kswang1029 — APPROVED** [review]
wonderful 🚀

**Pull request merged**
