### PR TITLE
KSW/support up to 16 profiles in multiprofile plotting mode

### LINKED ISSUE #2440: [spectral profiler] support more than 10 profiles in the multi-profile plotting mode
This is a Helpdesk ticket:

> I am analysing some JWST MRS data simultenously with ALMA data.
> 
> The MRS spectra typically come in 12 different cubes, and I noticed that CARTA only seems able to plot 10 (?) spectra simultaneously in the Z Profile window.
> 
> Would it be possible to increase this number, so I can plot the full spectral range at once?

Currently we hardcoded up to 10 profiles for the multi-profile plotting mode.

### PR DESCRIPTION
**Pull request by kswang1029**
**Description**

Close #2440.

This PR changes the up-to-10 profiles in the spectral multi-profile plotting mode to up-to-16 based on the available colors from blueprintjs.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] GitHub Project estimate added

For the pull request:
- [x] reviewers and assignee added
- [x] GitHub Project estimate added
- [x] changelog updated / ~no changelog update needed~
- [x] ~unit test added (for functions with no dependenies)~
- [x] ~API documentation added (for public variables and methods in stores)~

For dependencies:
- [x] e2e test passing / ~corresponding fix added~ / ~new e2e test created~
- [x] ~protobuf version bumped~ / no protobuf version bumped needed
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] ~corresponding ICD test fix added (`BackendService` changed)~ / no ICD test fix needed (`BackendService` unchanged)
- [x] ~user manual prepared (for large new features)~

### CODE REVIEW

**Comment by YuHsuan-Hwang** [comment]
Thanks for spotting the typo!

I found that when plotting multiple regions, the first three colors are skipped and the last two colors black and white are not set successfully.

Pasted Graphic 9

**Comment by kswang1029** [comment]
> Thanks for spotting the typo!
> 
> I found that when plotting multiple regions, the first three colors are skipped and the last two colors black and white are not set successfully.
> 
> Pasted Graphic 9

The root cause is from "white" and "black" colors which do not support sub-colors like blue1/blue2/blue3/blue4/blue5. A simple solution is to remove the two colors from the selectable colors and supported colors. Once done so, we should be able to support 17 colors without the missing color issue. @YuHsuan-Hwang please have a look.

**Comment by kswang1029** [comment]
> Thanks for spotting the typo!
> 
> I found that when plotting multiple regions, the first three colors are skipped and the last two colors black and white are not set successfully.
> 
> Pasted Graphic 9

The missing color box issue is fixed by removing the "white" and "black" colors from the `SELECTABLE_COLORS`. @YuHsuan-Hwang please have another look. Thanks.

**Review by YuHsuan-Hwang — APPROVED** [review]
The changes look good. The multiple region color issue is fixed. 👍

**Review by loveluthien — APPROVED** [review]

**Pull request merged**
