### PR TITLE
Yuhsuan/stores null check

### PR DESCRIPTION
**Pull request by YuHsuan-Hwang**
**Description**

This PR is for #2343 migrating part of the files in `/stores` to strictNullChecks enabled. The rest of the files in `/stores` will be migrated in a separate PR.

Some additional changes:
- `CatalogPlotWidgetStore` `fitting`, `minMaxX`, and `statistic`: set the entire variable to null instead of setting all members to undefined.
- Adjusted `PvGeneratorWidgetStore` `setSpectralCoordinate` and `setSpectralSystem`.
- Fixed the returned values in `SpectralLineQueryWidgetStore.filters`. Return an array of filter strings instead of an array of headers.
- Fixed incorrect telemetry data in `SpectralProfileWidgetStore.requestMoment`. Send the info of the selected region (either active or a specific id) instead of the active region.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] GitHub Project estimate added

For the pull request:
- [x] reviewers and assignee added
- [x] GitHub Project estimate added
- [x] ~changelog updated~ / no changelog update needed
- [x] ~unit test added (for functions with no dependenies)~
- [x] ~API documentation added (for public variables and methods in stores)~

For dependencies:
- [x] e2e test passing / ~corresponding fix added~ / ~new e2e test created~
- [x] ~protobuf version bumped~ / no protobuf version bumped needed
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] corresponding ICD test fix added (`BackendService` changed) / ~no ICD test fix needed (`BackendService` unchanged)~
- [x] ~user manual prepared (for large new features)~

### CODE REVIEW

**Review by kswang1029 — CHANGES_REQUESTED** [review]
As picked up by the e2e tests, when we select a casa image or a miriad image in the file list, the file info cannot be displayed. fits and hdf5 are fine. 
Screenshot 2024-05-06 at 13 18 12

**Comment by YuHsuan-Hwang** [comment]
Fixed failed e2e tests.

**Review by kswang1029 — CHANGES_REQUESTED** [review]
When we have a spectral profile plot, if we switch the x-axis to "channel", we cannot click a channel to switch to the channel in the image viewer. We cannot zoom/pan the spectral profile plot neither.

**Comment by YuHsuan-Hwang** [comment]
> When we have a spectral profile plot, if we switch the x-axis to "channel", we cannot click a channel to switch to the channel in the image viewer. We cannot zoom/pan the spectral profile plot neither.

This is fixed.

**Review by kswang1029 — APPROVED** [review]
I tried to check the changed files and performed test based on my understanding of the changed parts. I did not see other odd behaviors apart from the ones I reported before. No regression from e2e tests. Hope I did not miss something. 🤞

**Comment by kswang1029** [comment]
@acdo2002 please run ICD tests to see if there are unexpected regressions.

**Comment by YuHsuan-Hwang** [comment]
> I tried to check the changed files and performed test based on my understanding of the changed parts. I did not see other odd behaviors apart from the ones I reported before. No regression from e2e tests. Hope I did not miss something. 🤞

Thanks for the detailed testing!

**Review by acdo2002 — APPROVED** [review]
The corresponding ICD test [PR](https://github.com/CARTAvis/ICD-RxJS/pull/54) has already and all ICD tests are passed. Once this PR merged into the frontend dev, I will merge the ICD PR to the dev.

**Review by loveluthien — APPROVED** [review]
Well done!

**Review by crocka — APPROVED** [review]

**Pull request merged**
