### PR TITLE
Thchang/2051 protobufjs version bump

### LINKED ISSUE #2051: Bump protobufjs from 6.9.0 to 6.10.3
Bumps [protobufjs](https://github.com/protobufjs/protobuf.js) from 6.9.0 to 6.10.3. See https://github.com/CARTAvis/carta-frontend/pull/1925 for the details.

### PR DESCRIPTION
**Pull request by TienHao**
**Description**

this PR closes #2051

The package `protobufjs` was updated to the latest 7.2.6, since there was a bug when we implemented 6.10.8 and it did not be fixed until 7.0.0. And I also added package `protobufjs-cli` for the building tools(pbjs, pbts) have been moved from `protobufjs` after 7.0.0. Therefore, a update for build_proto.sh in the carta-protobuf was also needed.

The companion carta-protobuf PR: https://github.com/CARTAvis/carta-protobuf/pull/95 

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [ ] ZenHub estimate, milestone, and release (if needed) added
- [x] ~changelog updated~ / no changelog update needed
- [x] ~unit test added (for functions with no dependenies)~
- [x] ~API documentation added (for public variables and methods in stores)~

For dependencies:
- [x] ~e2e test passing / corresponding fix added / new e2e test created~
- [ ] protobuf version bumped / no protobuf version bumped needed
- [ ] protobuf updated to the latest dev commit / ~no protobuf update needed~
- [x] ~corresponding ICD test fix added (`BackendService` changed)~ / no ICD test fix needed (`BackendService` unchanged)
- [x] ~user manual prepared (for large new features)~

### CODE REVIEW

**Comment by YuHsuan-Hwang** [comment]
@TienHao Please also send a protobuf PR and add the link in the description, thanks.

**Review by YuHsuan-Hwang — APPROVED** [review]
Looks good.

**Review by loveluthien — APPROVED** [review]
Ubuntu is also fine.

**Comment by acdo2002** [comment]
Could you add ICD-RxJS protobuf version bump as another dependent check box?
Although there is no BackendService.ts change, the ICD-RxJS also used protobufjs version, so ICD-RxJS needs the companion PR. I have pushed the PR for it in [here](https://github.com/CARTAvis/ICD-RxJS/pull/50)

**Review by kswang1029 — APPROVED** [review]
Tested with the corresponding backend PR https://github.com/CARTAvis/carta-backend/pull/1367 and the carta-protobuf PR https://github.com/CARTAvis/carta-protobuf/pull/95. All e2e tests are passing. 👍

**Review by crocka — APPROVED** [review]

**Pull request merged**
