### PR TITLE
Angus/remove css animation

### LINKED ISSUE #1808: Bad behavior when coming back from sleep
I'm using the standalone app v3.0.0-beta.1b on my mac laptop.  When I put the computer to sleep (close it), it appears to clear the GPU cache.  CARTA then goes into a waiting mode where it asks whether to reload the session.  As long as it's in this waiting mode, it uses ~50% CPU according to activity monitor, using up battery & causing the fans to go strong - i.e., it's doing a lot of processing for nothing.  As soon as I hit 'Retry', the problem clears up.  It would be helpful to avoid this behavior.

### PR DESCRIPTION
**Pull request by veggiesaurus**
**Description**
Closes #1808 and https://github.com/CARTAvis/carta/issues/153 by:
- removing the CSS animation on the loading indicator
- hiding the splash screen (with animated spinner) when an alert is displayed

**Checklist**
- [x] changelog updated / ~~no changelog update needed~~
- [x] e2e test passing / ~~added corresponding fix~~
- [x] ~~protobuf updated to the latest dev commit~~ / no protobuf update needed

### CODE REVIEW

**Comment by kswang1029** [comment]
@ajm-asiaa tested with Chrome 103 and the high CPU/GPU issue is gone! I guess we can switch back to the latest electron lib.

**Review by kswang1029 — APPROVED** [review]
no regression spotted via e2e tests. It appears fine when performing manual tests. When CARTA is idle, CPU and GPU usages as seen in Chrome related processes are basically 0. 👍

**Review by YuHsuan-Hwang — APPROVED** [review]
If there's a performance issue with the spinner, shall we plan to also replace the others? Carta may be busy with calculations when we show a spinner ...

**Comment by kswang1029** [comment]
This is the CPU/GPU usage of Chrome 103 when we load the spinner page from blueprintjs user manual. 

Screen Shot 2022-06-30 at 10 20 07

If the duration of rendering the spinner is not too long, it might be still okay to use it as a "in progress" indicator. However, if there are better and power-efficient solutions, we should try those.

**Comment by veggiesaurus** [comment]
> If the duration of rendering the spinner is not too long, it might be still okay to use it as a "in progress" indicator. However, if there are better and power-efficient solutions, we should try those.

I think using it for in progress is fine. The main problem is idle usage when reconneting

**Pull request merged**
