### PR TITLE
carli/2318_missing_region_telemetry

### LINKED ISSUE #2318: missing region info in telemetry data
**Describe the bug**
based on https://github.com/CARTAvis/carta-frontend/blob/5068f5618e61f0105c957f233edc5d09539dd0de/src/services/TelemetryService.ts#L265 it appears that there is missing region info in region spectral profile request. 

We should also collect region type instead of region id.

We will also need to double check if region info for other tasks are collected correctly.

Apologies not picking this up back in time...

**To Reproduce**
1. enable telemetry to full and enable verbose mode in the browser console
2. load images and perform region spectral profile requests with different region types.
3. check telemetry log to see issues.

**Expected behavior**
region type should be part of the region telemetry data

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS ventura
 - Browser [e.g. chrome, safari, electron app]: electron app, chrome
 - Browser version [e.g. 22]: 
 - Backend branch [e.g. dev, v3b2 release]: v4-stable, dev
 - Frontend branch [e.g. dev, v3b2 release]: v4-stable, dev

### PR DESCRIPTION
**Pull request by crocka**
**Description**

Added regionType to spectral profile entry and closes #2318.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] ~changelog updated~ / no changelog update needed
- [x] ~unit test added (for functions with no dependenies)~
- [x] ~API documentation added (for public variables and methods in stores)~

For dependencies:
- [x] e2e test passing / ~corresponding fix added~ / ~new e2e test created~
- [x] ~protobuf version bumped~ / no protobuf version bumped needed
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] ~corresponding ICD test fix added (`BackendService` changed)~ / no ICD test fix needed (`BackendService` unchanged)
- [x] ~user manual prepared (for large new features)~

### CODE REVIEW

**Review by kswang1029 — APPROVED** [review]
@crocka now in the log I can see "region type". 👍 no other regression from e2e tests.

**Review by YuHsuan-Hwang — APPROVED** [review]
Maybe we don't need to include this in the changelog?

**Comment by kswang1029** [comment]
> Maybe we don't need to include this in the changelog?

no we don't need it I think.

**Comment by kswang1029** [comment]
@acdo2002 please verify that with this fix, region type is registered in the telemetry db.

**Comment by acdo2002** [comment]
Basically all codes are good and fine. 
However I have one thing would like to confirmed with KS @kswang1029 
Will PV generator only accept the line region? 
Or in the future we will support polyline region? 
Because I found current PvGenerator only accept the line region? I just curious about if we only support region, perhaps we do not need to add regionType into the PvGenerator telemetry (we already know it definitely is a line region)

In the line 36 of `src/stores/Widgets/PvGeneratorWidgetStore/PvGeneratorWidgetStore.ts`, it filters the line region.

If we will support polyline region for PvGenerator, I think it is necessary to add the regionType into the PvGenerator telemetry.

**Comment by acdo2002** [comment]
Kuo-Song @kswang1029  has confirmed we will have polyline region for PV generator. 
Then we should keep region Type telemetry in PV generator action.

**Review by acdo2002 — APPROVED** [review]

**Pull request merged**
