### PR TITLE
Thchang/help buttons for manual context 679

### LINKED ISSUE #679: adding context-sensitive in-app help
Currently the only way to access to the online user manual is via the "help" menu. For better UX, we should also provide in-app help manual with a question mark icon. For widgets, it should be in the header, next to the "cog". For dialog, it should be next to the close button (X). Once the help button is hit, we can use the blueprint "drawer" to show in-app help. For example, https://blueprintjs.com/docs/#core/components/drawer

The content for each widget and dialogue is TBD (@kswang needs to think about the maintainability of this in-app help and the online user manual).

### PR DESCRIPTION
**Pull request by TienHao**
close #679 : adding context-sensitive in-app help

The help buttons are now functional, but the help content hasn't been able to display videos.(Is this needed in in-app help?) I created  `/src/components/HelpDrawer/HelpContent`  to store help content components, and  `/src/static/help/` to store images. A demo can be seen by clicking help button of File Browser dialogue.

### CODE REVIEW

**Comment by kswang1029** [comment]
Supporting video is not needed I think. Texts and images should just fit.

**Comment by kswang1029** [comment]
@TienHao just checked your example with the file browser. Excellent job!

**Comment by TienHao** [comment]
The maintainability of content is quite challenging.:joy:  We have 24 empty help draws now.(all list in HelpType of HelpStore)

The step to build a help drawer from the manual_source are:
1. Copying the needed html from `manual_source/build/html` into `render()` of corresponding component
2. Removing unneeded parts, like `<video>`,`<a>`
3. Removing any error attribute, like `class` (the css is from Sphinx)
4. Adding needed images in `/src/static/help/` and importing them into the component
5. Modifying the style of ``

I think I can help with step 3 to 5, since the help drawers are hardcode in frontend.

**Comment by kswang1029** [comment]
@TienHao I think I will just create the in-app help from scratch and point users to the online manual when necessary. We don't want to put too much info with it. :)

**Comment by kswang1029** [comment]
@TienHao also I found there is tool to convert markdown to html. So I will try it and just copy-paste the html to the right place in the codebase.

**Comment by veggiesaurus** [comment]
@TienHao looks like this has a bunch of conflicts with `dev`, can you sort them out?

**Comment by kswang1029** [comment]
@TienHao for each widget or dialogue, could you make a template .tsx, just like you did for the file browser? Then I can follow and insert the help contents as html.

**Review by veggiesaurus — APPROVED** [review]
This is going to be so helpful! Looks good

**Pull request merged**
