### PR TITLE
Yuhsuan/1149 line region

### PR DESCRIPTION
**Pull request by YuHsuan-Hwang**
This PR is for https://github.com/CARTAvis/carta-frontend/issues/1149 line regions.
* Requires backend branch `pam/610_line_region`.
* Also refactored `RegionViewComponent` so that the logic and naming are more straightforward. Please also test if all kinds of region creation still works fine.
* Hide length and PA inputs if there are non square pixels.

### CODE REVIEW

**Comment by YuHsuan-Hwang** [comment]
Changed to click-and-drag creation mode for better ctrl/cmd key event handling.

**Comment by kswang1029** [comment]
@YuHsuan-Hwang found some issues:
1. if we manually edit the length, sometimes it changes to an unexpected length (and PA becoming 45deg?) after hitting the return key. Sometimes the length is 0 and PA becomes NaN. There seems no way to fix it except deleting it. 

https://user-images.githubusercontent.com/20819712/124538524-621fd200-de4e-11eb-9d84-9d1bfc043c77.mov

2. the line region does not follow the region management rules when un-matching an image. When we unmatch an image, this image will get a copy of the regions from the reference image. If we modify some of the regions and match the image again, the frontend should check redundancy of regions and only copy over those modified regions to the reference image. Please try to create some other regions and see how it works or let me know if you need more details on the rules.

**Comment by YuHsuan-Hwang** [comment]
@kswang1029 Ok. Will work on the issues

**Comment by YuHsuan-Hwang** [comment]
@kswang1029 Fixed both two issues.

**Comment by kswang1029** [comment]
@YuHsuan-Hwang any idea about the size field in the region list widget? The values are weird (should just be the length only).
Screen Shot 2021-07-08 at 9 07 04 AM

**Comment by YuHsuan-Hwang** [comment]
@kswang1029 Forgot to adjust this column ... Will change this part.

**Comment by kswang1029** [comment]
The PA becomes 0deg _after_ unmatching image.

https://user-images.githubusercontent.com/20819712/124847792-2f9ce300-dfce-11eb-9491-b9cc7cc57fd2.mov

**Comment by YuHsuan-Hwang** [comment]
@kswang1029
Fixed the size column (including tooltip). This column will show "NaN" if there are non square pixels.
Also fixed the unmatching image bug.

**Review by kswang1029 — APPROVED** [review]
tested. 👍  With this we can start the implementation of 
1. backend pv generator @pford 
2. frontend pv generator UI @TienHao

**Pull request merged**
