### PR TITLE
Finish exporting header as txt file

### LINKED ISSUE #1357: export header as a text file
as requested from #1355, it would be handy to have an export button so that the header file can be saved as a text file.

### PR DESCRIPTION
**Pull request by acdo2002**
Try to fix #1357 
I follow the LinePlotComponent.tsx (like channel-N-histogram.tsv to export data) & FileInfoComponent.tsx (like search-text button) structure to solve this issue. 
Thanks Yu-Hsuan's help!

Any suggestion is welcome.

### CODE REVIEW

**Comment by kswang1029** [comment]
@acdo2002 I suggest we add filename as the first line of the text file starting with #
Also, we should try to have a button group with the download button on the right hand side and the search button on the left hand side.

**Comment by veggiesaurus** [comment]
Should we not be trying to export this as someone that can be used as a fits header?

**Comment by acdo2002** [comment]
@kswang1029 
Does this format match to your thinking? (using button group, search button is on the left-hand-side, while export txt button is on right-hand-side)
Screenshot from 2021-05-12 21-39-09-1
I can add filename as the first line of the text file starting with # later.

@veggiesaurus 
Sorry I am a bit confused, do you mean the exported txt file may be used by other? 
At least my experience is that the header will generate together with the data calibration/creation rather than I import the header...

**Comment by veggiesaurus** [comment]
> @veggiesaurus
> Sorry I am a bit confused, do you mean the exported txt file may be used by other?
> At least my experience is that the header will generate together with the data calibration/creation rather than I import the header...

I was just thinking that it makes sense to make them look as similar as possible to a FITS header, but perhaps that doesn't matter

**Comment by acdo2002** [comment]
@kswang1029 I have followed your suggestion to improve the function, could you check it?

**Review by kswang1029 — APPROVED** [review]
this looks fine. 

To improve the readability, we probably want to align "=" (cf. ds9). This could happen as a different issue.

**Comment by acdo2002** [comment]
@TienHao Because I put export txt as a utilities function and change small part of your code, could you check whether it is OK? I just remove the duplicate parts.

**Review by YuHsuan-Hwang — APPROVED** [review]

**Comment by acdo2002** [comment]
@kswang1029 the minor code refactoring has been done, could you look at it again? 
there are two parts used the exportTxt function (because we wrote in the same way): One is header export, another one is spectral-line fitting results saved as log.

**Review by TienHao — APPROVED** [review]

**Review by kswang1029 — APPROVED** [review]

**Review by veggiesaurus — APPROVED** [review]

**Pull request merged**
