### PR TITLE
add a button to select all Event Types

### PR DESCRIPTION
**Pull request by acdo2002**
Refer to #1281 
I add few lines (carta-frontend/src/components/Dialogs/PreferenceDialog/PreferenceDialogComponent.tsx) to make a button that can select all the Event Types... any better suggestion is welcome!!!

### CODE REVIEW

**Comment by kswang1029** [comment]
@acdo2002 we should grey out the "select all" button when _all_ messages are selected (either via the select all button or manually).

**Comment by duidae** [comment]
this implementation is a little bit strange comparing to conventional "select all", I'll suggest we add the "select all" checkbox like gmail next to the event type header

s7h99-ybdkv

**Comment by kswang1029** [comment]
@acdo2002 What if we make "Enable logged event type" always visible as a header regardless the scrolling state of the list below, then we can add a checkbox (or a toggle) next to it with the same effect as @duidae suggested?

Screen Shot 2020-12-23 at 3 16 04 PM

**Comment by acdo2002** [comment]
I am ok with this. My initial motivation is very simple and naive, just would like to have a button that can select all :)

**Comment by duidae** [comment]
send a PR #1284 for select all, so close this.

**Pull request closed without merging**
