### PR TITLE
Thchang/fix image viewer tab

### LINKED ISSUE #1686: reset tab title of image viewer when we close all images
Screen Shot 2021-10-29 at 12 03 44 PM

### PR DESCRIPTION
**Pull request by TienHao**
closes #1686. Clear image viewer title after all images closed.

### CODE REVIEW

**Review by kswang1029 — CHANGES_REQUESTED** [review]
Please try the following case to see the issue:
1) load two images, say A.fits and B.fits in order.
2) we should see the title is B.fits
3) close B.fits either via the file menu or using the context menu (right click) of the image list widget
4) we should see the title gets updated to A.fits as it is the active image now but we still see B.fits as the title.

**Comment by TienHao** [comment]
> Please try the following case to see the issue:
> 
> 1. load two images, say A.fits and B.fits in order.
> 2. we should see the title is B.fits
> 3. close B.fits either via the file menu or using the context menu (right click) of the image list widget
> 4. we should see the title gets updated to A.fits as it is the active image now but we still see B.fits as the title.

fixed

**Review by YuHsuan-Hwang — COMMENTED** [review]
https://github.com/CARTAvis/carta-frontend/blob/dev/src/stores/AppStore.ts#L1439
Could we remove these lines in `autorun` if title update is handled in `changeActiveFrame` and `closeFile`?

**Comment by TienHao** [comment]
> https://github.com/CARTAvis/carta-frontend/blob/dev/src/stores/AppStore.ts#L1439 Could we remove these lines in `autorun` if title update is handled in `changeActiveFrame` and `closeFile`?

I think it's OK to remove these lines.

**Review by kswang1029 — APPROVED** [review]
Tested. Now the tab title of the image viewer shows correct image name. 👍

**Review by YuHsuan-Hwang — APPROVED** [review]

**Pull request merged**
