### PR TITLE
Yuhsuan/GitHub project

### PR DESCRIPTION
**Pull request by YuHsuan-Hwang**
**Description**

This PR is for some minor updates when migrating to GitHub Projects:
* Updated protobuf to the latest dev commit (some GitHub Actions were added)
* Updated the PR template checkboxes
* Updated the GitHub workflow section of the documentation website

Also updated the version bump PR template based on our discussion on Slack. I assume the template could be used when updating to, for example, v5.0.0-beta (on a release branch), v5.0.0 (on a release branch, with user manual url update), and v6.0.0-dev (on the dev branch, with doc website update).

**Checklist**

For the pull request:
- [x] reviewers and assignee added
- [ ] ZenHub estimate, milestone, and release (if needed) added
- [x] ~changelog updated~ / no changelog update needed
- [x] ~unit test added (for functions with no dependenies)~
- [x] ~API documentation added (for public variables and methods in stores)~

For dependencies:
- [x] e2e test passing / corresponding fix added / new e2e test created
- [x] ~protobuf version bumped~ / no protobuf version bumped needed
- [x] protobuf updated to the latest dev commit / ~no protobuf update needed~
- [x] ~corresponding ICD test fix added (`BackendService` changed)~ / no ICD test fix needed (`BackendService` unchanged)
- [x] ~user manual prepared (for large new features)~

### CODE REVIEW

**Comment by kswang1029** [comment]
@YuHsuan-Hwang the backend dev branch is now with carta-protobuf commit "701220443c977641b1884d2fed97a5b71ed46b9d" but this PR is with "3219acafa7bc454fe8d448f4dd99cef29f5ac5e8". Any idea?

**Comment by YuHsuan-Hwang** [comment]
@kswang1029 Backend also need to update to `3219aca` because some GitHub Actions were added.

**Comment by kswang1029** [comment]
> @kswang1029 Backend also need to update to `3219aca` because some GitHub Actions were added.

So do you mean we need a backend PR doing such? (ie joint merge is needed?)

**Comment by YuHsuan-Hwang** [comment]
Yes, but we can merge them separately since no messages are changed.

**Review by kswang1029 — APPROVED** [review]
looks good.

**Pull request merged**
