### PR TITLE
fixed support for floating widgets in layout

### PR DESCRIPTION
**Pull request by veggiesaurus**
Adjusts floating widget saved config to be consistent with docked widgets

### CODE REVIEW

**Comment by duidae** [comment]
thanks for fixing, btw it's better tested before merge to ensure the functionality correctness (seems that @kswang1029 did not approve the previous PR #1081?)

**Review by kswang1029 — CHANGES_REQUESTED** [review]
when there is a docked catalog widget in the layout, saving is fine but in a new session we cannot see the saved layout.

**Comment by veggiesaurus** [comment]
> when there is a docked catalog widget in the layout, saving is fine but in a new session we cannot see the saved layout.

This is just designed to fix floating layout widgets. Catalog widgets (#980) will be handled by @duidae in a separate PR

**Comment by kswang1029** [comment]
@veggiesaurus ok. in that sense, it works well

**Review by kswang1029 — APPROVED** [review]

**Comment by veggiesaurus** [comment]
@kswang1029 @duidae I've made a couple of changes, so that older layouts should still work. Please re-review

**Review by duidae — APPROVED** [review]

**Review by kswang1029 — APPROVED** [review]
yes old layouts still load

**Comment by duidae** [comment]
closes #1103

**Pull request merged**
