### PR TITLE
Add guard to invalid spectral conversion

### LINKED ISSUE #761: add guard to spectral conversion
some headers in fits will not be provided, ex:
if RESTFREQ is missing => velocity cant convert to frequency, vise versa
if OBSERVATION-DATE is missing, LSRK/LSRD cant convert to TOPO, BARY, vise versa
if OBSGEO-X OBSGEO-Y OBSGEO-Y are missing, any cant convert to TOPO, vise versa

### PR DESCRIPTION
**Pull request by duidae**
closes #761

### CODE REVIEW

**Review by veggiesaurus — APPROVED** [review]
code looks fine. Will leave it to @kswang1029 to test in terms of science

**Comment by kswang1029** [comment]
@veggiesaurus @duidae will do with artificial cubes

**Comment by kswang1029** [comment]
@duidae could you check the case that if we only have RESTFRQ missing? Now I see the x-axis is channel and we cannot do any conversions. 
If RESTFRQ is missing, we should still have x-axis as 
1) 'Radio velocity' or 'Optical velocity' or 'Channel' if CTYPE3/4 is velocity-like
2) 'Frequency' or 'Vacuum wavelength' or 'Air wavelength' or 'Channel' if CTYPE3/4 is frequency-like.
Could you double check the guard?
Other guards with missing observatory info, missing observation date, etc. work fine. 👍

**Comment by veggiesaurus** [comment]
@kswang1029 @duidae is this still in progress?

**Comment by duidae** [comment]
@kswang1029  said it still needs test

**Comment by kswang1029** [comment]
Not sure if I have time before freeze. I suppose we can go ahead. At least I did some basic tests.

**Comment by veggiesaurus** [comment]
@duidae can you fix the merge conflicts and we'll merge this in?

**Comment by duidae** [comment]
@veggiesaurus  fixed

**Pull request merged**
