### PR TITLE
Hj/#420 layout breadcrumb

### PR DESCRIPTION
**Pull request by zarda**
Fixed the issue #420 and fine tuned the layout to avoid incomplete file list.

### CODE REVIEW

**Comment by veggiesaurus** [comment]
@zarda this is looking good. One comment: I like the change you've made to the file list table's header, but I'm not convinced we need `height: 40px` for that
image

Just using the normal height looks more consistent: 
image

Or is it done for alignment purposes? @kswang1029 what do you think?

**Comment by kswang1029** [comment]
@veggiesaurus I think `height: 40px` is for alignment. Following are the two screenshots with different theme. In the file info/file header, we have a horizontal bar as an indicator on what the currently view is. I am not sure how to solve this in a clever way... In addition, in the dark mode, the extra height is even highlighted due to its background color. 
Screen Shot 2019-08-06 at 9 26 25 AM
Screen Shot 2019-08-06 at 9 26 10 AM

**Comment by kswang1029** [comment]
@zarda @veggiesaurus there is an issue with this PR: breadcrumbs do not work after loading an image.
When loading an image for the first time, it works.
Screen Shot 2019-08-06 at 10 49 58 AM
After an image is loaded and if we launch file browser again, the breadcrumbs do not work and we are locked in the current folder.
Screen Shot 2019-08-06 at 10 50 12 AM

**Comment by kswang1029** [comment]
@zarda @veggiesaurus UPDATE: if you click "header" tab, the breadcrumbs show up. If you make the dialog wider, the breadcrumbs show up too.

**Comment by veggiesaurus** [comment]
> @zarda @veggiesaurus UPDATE: if you click "header" tab, the breadcrumbs show up. If you make the dialog wider, the breadcrumbs show up too.

@kswang1029 and this doesn't happen in dev?

**Comment by kswang1029** [comment]
@veggiesaurus no. in dev, it works fine.

**Comment by zarda** [comment]
The Breadcrumbs collapsed while reopening file browser. This issue will be solve whenever opening file browser again or resizing. I do not find any solution but a workaround is to set minVisibleItems=2.

**Comment by veggiesaurus** [comment]
> The Breadcrumbs collapsed while reopening file browser. This issue will be solve whenever opening file browser again or resizing. So fixed it by re-show the file browser after opening.

This is not the right way to solve the problem, because it means a duplicate `FILE_LIST_REQUEST` message gets sent to the backend every time you open the file browser. If the directory has a lot of files, this will effectively double the time it takes to list the files.

**Comment by veggiesaurus** [comment]
@zarda can you try to find another way to solve this? the current solution also breaks appending files

**Pull request merged**
