### PR TITLE
carli/2164_aips_beam_support

### LINKED ISSUE #2164: Legacy FITS header support - AIPS beam
This is the frontend part of the backend issue https://github.com/CARTAvis/carta-backend/issues/1083. The detailed discussion is in https://docs.google.com/document/d/1qUm02JOLxOoG_4p_lDJpKRj7z4tnwsEh5GoOxASKNSs/edit#.

The frontend part is to support a new tab "Compatibility" including a toggle in the preferences dialog. If the toggle is enabled (default off), the backend will do a guess of the beam info from HISTORY in the header and set BMAJ, BMIN, and BPA accordingly. Then the frontend will be able to render the beam element in the image viewer. Intensity unit conversion will be also possible too.

### PR DESCRIPTION
**Pull request by crocka**
**Description**

This PR resolves the frontend part of issue #2164. Closes #2164. A compatibility tab is added to the preference dialog, where a single toggle is added to turn on/off support for AIPS beam. The corresponding backend and protobuf pr is carta-frontend [#1275](https://github.com/CARTAvis/carta-backend/pull/1275), and carta-protobuf [#86](https://github.com/CARTAvis/carta-protobuf/pull/86).

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] e2e test passing / corresponding fix added
- [ ] changelog updated / ~~no changelog update needed~~
- [ ] protobuf updated to the latest dev commit / ~~no protobuf update needed~~
- [ ] ~~`BackendService` unchanged~~ / `BackendService` changed and corresponding ICD test fix added

### CODE REVIEW

**Comment by kswang1029** [comment]
@crocka please convert this to formal PR and proceed code review.

**Comment by kswang1029** [comment]
@crocka please update this branch with dev and convert it to a formal PR. Please proceed code review.

**Review by YuHsuan-Hwang — APPROVED** [review]
Looks good to me.
@crocka Could you add the corresponding backend and protobuf PRs in the description?

**Review by kswang1029 — APPROVED** [review]

**Comment by YuHsuan-Hwang** [comment]
@acdo2002 `BackendService` is changed, so we might need to fix ICD tests.

**Review by acdo2002 — APPROVED** [review]
The Test code change is ready

**Comment by YuHsuan-Hwang** [comment]
This PR is ready for merge. @crocka Please update the changelog, thanks.

**Pull request merged**
