### PR TITLE
add key prop

### LINKED ISSUE #2116: Root menu warning
**Describe the bug**
Warning from the root menu component. A regression after v3 release.

**To Reproduce**
Launch Carta and check the console

**Expected behavior**
No warnings

**Screenshots or videos**
image

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Big Sur
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 108
 - Backend branch [e.g. dev, v3b2 release]: dev, not in v3 release
 - Frontend branch [e.g. dev, v3b2 release]: dev

**Additional context**

### PR DESCRIPTION
**Pull request by YuHsuan-Hwang**
**Description**
Fixes #2116. Remove the warning by adding key prop.

**Checklist**

For linked issues (if there are):
- [X] assignee and label added
- [X] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [X] reviewers and assignee added
- [X] ZenHub estimate, milestone, and release (if needed) added
- [x] e2e test passing / ~corresponding fix added~
- [X] ~changelog updated~ / no changelog update needed
- [X] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [X] `BackendService` unchanged / ~`BackendService` changed and corresponding ICD test fix added~

### CODE REVIEW

**Comment by acdo2002** [comment]
I checked out this branch and the warning message disappear. (MacOS 11 + Chrome 109)

**Review by kswang1029 — APPROVED** [review]
this appears having no impact on the user side based on e2e tests and manual tests.

**Comment by kswang1029** [comment]
@I-Chenn please proceed code review.

**Review by I-Chenn — APPROVED** [review]
The regression message disappears by checking out to this branch both on my MacBook and Ubuntu desktop.
Thanks for adding the key prop to the function I made. Will remember to add the key prop to get avoid the regression next time.

**Pull request merged**
