### PR TITLE
Jason/issue 265

### PR DESCRIPTION
**Pull request by duidae**
the behavior of reverse animation seems incorrect, however can confirm the UI & bouncing/blink first to see whether it's appropriate

related to #265 

image

### CODE REVIEW

**Comment by kswang1029** [comment]
@veggiesaurus @duidae For the range slider, since we use radio button to select which to animate (frame, channel, stokes), how about we just the range slider for the selected one? For example, if users want to animate stokes, when the radio button is selected, the range slider shows up right below stokes slider. How about this?

**Comment by veggiesaurus** [comment]
> @veggiesaurus @duidae For the range slider, since we use radio button to select which to animate (frame, channel, stokes), how about we just the range slider for the selected one? For example, if users want to animate stokes, when the radio button is selected, the range slider shows up right below stokes slider. How about this?

That might just work... :+1:

**Comment by veggiesaurus** [comment]
> @veggiesaurus @duidae For the range slider, since we use radio button to select which to animate (frame, channel, stokes), how about we just show the range slider for the selected one? For example, if users want to animate stokes, when the radio button is selected, the range slider shows up right below stokes slider. How about this?

@kswang1029 @duidae I think we should leave this enhancement to a separate issue and PR, because it would require a bit of work. Is that ok? If so, we can leave out blink/bouncing support for frame animations.

**Comment by kswang1029** [comment]
Yes!

**Comment by duidae** [comment]
ok

**Pull request merged**
