### PR TITLE
Jason/fix filelist header

### PR DESCRIPTION
**Pull request by duidae**
trial approach to fix the sortable header th with scrollable tbody in table

out ogv

### CODE REVIEW

**Comment by veggiesaurus** [comment]
Very nice! I'd forgotten about `position: sticky` :+1: 

While you're fixing the list, can you try align the sort indicators more clearly. They need to move up and to the right a bit

**Comment by duidae** [comment]
okok

**Comment by duidae** [comment]
@veggiesaurus icon adjustment added, please take a look when available, thanks!

**Comment by duidae** [comment]
closes #245

**Pull request merged**
