### PR TITLE
Ksw/scaling eqn png

### PR DESCRIPTION
**Pull request by YuHsuan-Hwang**
This PR is for updating the equation images for both light and dark themes.
image

The incorrect the popover width is fixed in another PR: https://github.com/CARTAvis/carta-frontend/issues/1369.

### CODE REVIEW

**Review by kswang1029 — APPROVED** [review]
👍

**Comment by veggiesaurus** [comment]
This looks fine, but I'm wondering if there isn't a more sustainable solution here. What about using the original PNG and just inverting it with CSS?

**Comment by YuHsuan-Hwang** [comment]
@veggiesaurus Ok. I will change it.

**Comment by veggiesaurus** [comment]
> @veggiesaurus Ok. I will change it.

Well, give it a try and see if its straightforward 😊 I know CSS has some useful filters. I guess it depends whether we can keep the transparency layer uninverted

**Comment by YuHsuan-Hwang** [comment]
@veggiesaurus Changed to CSS style solution. The images look the same as the above.
image

**Comment by veggiesaurus** [comment]
> @veggiesaurus Changed to CSS style solution. The images look the same as the above.
> image

@YuHsuan-Hwang I know this is now a little bit of feature creep, but do you think we could try to also highlight the equations in a similar fashion to that of the text?

**Comment by YuHsuan-Hwang** [comment]
@veggiesaurus Sure, I also thought about this. Let me try if `brightness` works.

**Comment by YuHsuan-Hwang** [comment]
I have changed the color to white, but it's not significant. We may have to change the characters into bold.
image

**Comment by kswang1029** [comment]
> I have changed the color to white, but it's not significant. We may have to change the characters into bold.
> image

Try drop-shadow?

**Comment by YuHsuan-Hwang** [comment]
@kswang1029 I think drop-shadow works. Thanks.
image

**Review by veggiesaurus — APPROVED** [review]

**Pull request merged**
