### PR TITLE
carli/2028_region_position_offset_problem

### LINKED ISSUE #2028: matched regions have position offset after clicking the zoom-to-fit button
**Describe the bug**
Matched regions will have position offset after we click the zoom-to-fit button. 

https://user-images.githubusercontent.com/20819712/194985137-9839a58c-1a3e-4dcd-9d26-04d343ee4799.mov

If we click the zoom-to-fit button again, we will see the offset is gone. Or if we pan the image a bit, the offset will be gone.

**To Reproduce**
1. download the attached images, load them, and match them
2. enable the coordinate grid
3. create a point region as RA=18:00:31.8, Dec=-4:00:52
4. pan/zoom the image a bit
5. now on the matched image, click the zoom-to-fit button and we will see on that image the point has a position offset

**Expected behavior**
Regions should not have position offset after clicking the zoom-to-fit button.

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Monterey
 - Browser [e.g. chrome, safari, electron app]: electron app
 - Browser version [e.g. 22]: 
 - Backend branch [e.g. dev, v3b2 release]: v3-stable
 - Frontend branch [e.g. dev, v3b2 release]: v3-stable

[tmp.zip](https://github.com/CARTAvis/carta-frontend/files/9750614/tmp.zip)

### PR DESCRIPTION
**Pull request by crocka**
**Description**
This PR fixes #2028. The `centerStage` function in the `RegionViewComponent` sets the `stage.position()` to `correctedOrigin`, when the user clicks `Zoom to Fit` button in the tool bar. However, before calling `centerStage`, the program calls `syncStage` function in the `RegionViewComponent`, which does the same thing as `centerStage` function. The solution to this bug is simply removing the `centerStage` function.

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] e2e test passing / ~corresponding fix added~
- [x] ~~changelog updated~~ / no changelog update needed
- [x] ~~protobuf updated to the latest dev commit~~ / no protobuf update needed
- [x] `BackendService` unchanged / ~~`BackendService` changed and corresponding ICD test fix added~~

### CODE REVIEW

**Review by kswang1029 — CHANGES_REQUESTED** [review]
The fix works. No regression is observed via e2e tests.

However, I spotted a problem when panning images. It is "jumpy" if we pan the image slowly. 
this branch


https://user-images.githubusercontent.com/20819712/210194188-ed0ab0bd-d48b-4c1b-bac4-077659384d02.mov



v3-stable


https://user-images.githubusercontent.com/20819712/210194200-410ab153-557d-4c79-9c77-72fdc7cdbe5f.mov

**Review by kswang1029 — APPROVED** [review]
this works well. no regression is observed from e2e tests. 👍

**Review by YuHsuan-Hwang — CHANGES_REQUESTED** [review]
The fix is nice. We can also remove the input param `isZoomToFit`.

**Comment by YuHsuan-Hwang** [comment]
The issue exists in v3, so please update the change log, thanks.

**Review by YuHsuan-Hwang — APPROVED** [review]

**Pull request merged**
