### PR TITLE
Qi/spectral floating settings panel

### PR DESCRIPTION
**Pull request by panchyo0**
1. added LinePlotSettingsPanelComponentProps and LinePlotSettingsPanelComponent for line plots settings.
2. added ScatterPlotSettingsPanelComponentProps and ScatterPlotSettingsPanelComponent for scatter plots settings.
3. removed pop up settings panel for histogram, spatial profiler, spectral profiler and render config.
4. added scss margin-right = 5px for Spectral Profiler and histogram .profile-container.
5. added scss overflow = auto for floating settings widgets which will allow scroll for overflow.
6. changed the floating settings widgets id format from "${defaultId}-${nextIndex}" to "${parentId}-${defaultId}-${nextIndex}"
7. changed the default stokes widget size.
8. apply cog button for histogram, spatial profiler, spectral profiler, render config and stokes.
9. hide cog button for unnecessary widgets with golden layout.
10. finished #495 
11. finished #413 by making value =0.0 grid line more thicker.

### CODE REVIEW

**Comment by kswang1029** [comment]
We can have multiple spectral profile widgets and thus each can have a floating settings panel (this actually applies to all widgets and their settings panels). We will need a way to let users know the pairs visually.

**Comment by veggiesaurus** [comment]
> We can have multiple spectral profile widgets and thus each can have a floating settings panel (this actually applies to all widgets and their settings panels). We will need a way to let users know the pairs visually.

I agree. Is matching the title sufficient? Perhaps a `*` in the title of the profiler when the settings widget is focused?

**Comment by panchyo0** [comment]
@veggiesaurus Currently spectral settings panel only match the region for title. since the settings panel will allow user custom the line plot for entire widget(stokes Q, U, I, V and Current). Should we add stokes parameter in title? When user change the size of the spectral widget to min, the title UI starts at another line. Should we add "overflow=auto" to solve it?
Screen Shot 2019-11-04 at 10 50 42 AM

**Comment by veggiesaurus** [comment]
> @veggiesaurus Currently spectral settings panel only match the region for title. since the settings panel will allow user custom the line plot for entire widget(stokes Q, U, I, V and Current). Should we add stokes parameter in title? When user change the size of the spectral widget to min, the title UI starts at another line. Should we add "overflow=auto" to solve it?
> Screen Shot 2019-11-04 at 10 50 42 AM

I'd prefer not to change the widget title height, but am open to the idea if it looks ok

**Pull request merged**
