### PR TITLE
ajm/2108 url copy

### LINKED ISSUE #2102: "Copy Session URL to clipboard" modification needed for macOS Electron version
**Describe the bug**

For the macOS Electron version of CARTA, the `File > Server > Copy Session URL to clipboard` feature will need to be modified. 
At the moment it copies something like this: 
```
file:///Applications/CARTA.app/Contents/Resources/app/index.html?socketUrl=ws://localhost:55051&token=c533b90f-5bf1-4814-b81c-a889a35e79d8/
```

It should instead be:
```
http://localhost:55051?token=c533b90f-5bf1-4814-b81c-a889a35e79d8/
```

I imagine it should be easy to fix. I guess an extra loop can be added to the appropriate section in `src/components/Menu/RootMenuComponent.tsx` to check for the presence of "socketUrl" in the string, and if present it could take the value of socketUrl, as well as substitute "ws" with "http", and "&" with "?" (Replacing "&" with "?" is necessary as the python scripting interface does not seem to be able to parse it "&").

**To Reproduce**
1. Run our CARTA-python-test-17-2-23.dmg macOS Electron version.
2. Click on File > Server > Copy Session URL to clipboard
3. Paste it somewhere.
4. See the extended URL.

**Expected behavior**
For easier python scripting interface use, the URL should be shorter. There should be 3 changes:
1. Only copy the text after socketUrl=
2. Replace "ws" with "http"
3. Replace "&" with "?"

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]:  macOS Monterey
 - Browser [e.g. chrome, safari, electron app]: Electron app  CARTA-python-test-17-2-23.dmg
 - Browser version [e.g. 22]: Electron 23.0.0 (Chrome 108)
 - Backend branch [e.g. dev, v3b2 release]: dev 28152ab
 - Frontend branch [e.g. dev, v3b2 release]: dev 2978e72

### LINKED ISSUE #2108: navigator.clipboard without secure origin problem
**Describe the bug**
When testing #2102 in a CARTA AppImage, I found a new issue; The `Copy session ID to clipboard` and `Copy session URL to clipboard` feature does not work.

After investigating I see why. The feature uses `navigator.clipboard` and that apparently "requires a secure origin - either HTTPS or localhost".  However, our CARTA AppImage uses a HTTP IP address and not "localhost". e.g. 

> http://10.211.55.38:3002/?token=e3d039b9-7b85-4207-b815-026121432a4e

Therefore, the `navigator.clipboard` feature does not work. 

If we extract the AppImage and simply run the carta_backend executable, we get a URL with "localhost" and then the copy & paste feature works.

So we could either modify the AppImage to not show the IP and instead show "localhost" (although I wonder if there are other use cases where the user would have an http:// IP address?), or have a fallback method to `navigator.clipboard` such as the older `document.execCommand`.

1. Run an AppImage built from the current 'dev' branch carta-backend and carta-frontend.
2. Click on File > Server > Copy session ID to clipboard.
3. Try to paste it.

**Expected behavior**
The session ID and URL should be able to be copy and pasted.

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: Ubuntu 20.04
 - Browser [e.g. chrome, safari, electron app]: Chrome
 - Browser version [e.g. 22]: 110
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

### PR DESCRIPTION
**Pull request by ajm-ska**
**Description**

This fixes issue #2102 (to exclude the extended URL from the macOS Electron version) as well as the newer issue in #2108 (the `navigator.clipboard` not working with non-localhost and non-https URLs). The solution to the latter is to fall back to `document.execCommand("copy");` if `navigator.clipboard` does not work.

I checked it with the following combinations and it was able to copy the session ID and URL successfully in each case:

- [x] AppImage with Chrome
- [x] AppImage with Firefox
- [x] macOS Electron version
- [x] Normal usage (tested Mix 'n Match) with Chrome
- [x] Normal usage (tested Mix 'n Match) with Firefox
- [x] Normal usage (tested Mix 'n Match) with Safari

Note: The only use case not directly covered by these fixes is that of our Mix 'n Match system where the frontend component of the URL is preceded by https:// and not file://. Therefore it copies the entire URL as: 

> https://carta.asiaa.sinica.edu.tw/frontend/749c0335/?socketUrl=wss://carta.asiaa.sinica.edu.tw/socketdev&skipTelemetry=1

However, this may be a unique use case of CARTA for developers only, so is not addressed by these fixes.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] e2e test passing / corresponding fix added
- [x] changelog updated
- [x] no protobuf update needed
- [x] `BackendService` unchanged

### CODE REVIEW

**Comment by kswang1029** [comment]
Can anyone try AppImage at remote server and use local chrome/Firefox/safari to see if all are okay?

**Comment by kswang1029** [comment]
@ajm-asiaa if we have a test electron app and an AppImage, I can test them with my resources. Or I can just use my dev build.

**Comment by ajm-ska** [comment]
@kswang1029 I'll send them to you soon.

**Comment by kswang1029** [comment]
@ajm-asiaa trid a Mac local build with local safari/chrome/firefox. All good. Also tried to use Ubuntu 22.04 to access the backend on my Mac with chrome/firefox in Ubuntu. All good too. I used http://octopus.local:3002 as the url.

**Review by kswang1029 — APPROVED** [review]
tested
1. local Mac build with local chrome/firefox/safari
2. local Mac build and a ubuntu 22.04 box in the same wifi network with chrome/firefox
3. remote AppImage and a local Mac with VPN and with chrome/firefox/safari
4. AppImage in ubuntu 22.04 with its chrome/safari
all are good.

No regression is observed from e2e tests.

**Review by YuHsuan-Hwang — APPROVED** [review]

**Review by veggiesaurus — APPROVED** [review]

**Pull request merged**
