### PR TITLE
adjusted default layout and removed GUI items that are not available

### PR DESCRIPTION
**Pull request by veggiesaurus**
- Minor change to default layout: removing spectral profile and replacing with region list and stats
- Removed items that are not available in 1.1
- Rearranged toolbar to match layout menu item ordering

### CODE REVIEW

**Comment by veggiesaurus** [comment]
@duidae hold off on merge until @kswang1029 signs off on changes

**Comment by kswang1029** [comment]
Yes. Works nicely. 👍

**Comment by duidae** [comment]
hihi @veggiesaurus, so the default z profiler will change to "lm-react-component"?

aa

**Comment by veggiesaurus** [comment]
@duidae in this branch, the default Z-profiler has been removed, so it shouldn't say "lm-react-component" (that occurs in master)

Master branch:
image

This branch:
image

**Comment by duidae** [comment]
okok got it (sorry I forgot to checkout orz)

**Pull request merged**
