### PR TITLE
Jason/fix spectralline issue

### LINKED ISSUE #1063: wavelength conversion in the spectral line query widget
1mm = 299792.458 MHz
1cm = 29979.2458 MHz

With the spectral line query widget, we see the conversion is incorrect (10x smaller). 
1mm
Screen Shot 2020-07-28 at 10 16 11 AM

1cm
Screen Shot 2020-07-28 at 10 25 20 AM

### LINKED ISSUE #1064: spectral line query: line table is not updated if a new query results in zero line
To reproduce the issue:
1) query 100000 MHz to 100001 MHz, there will be 9 entries returned.
2) query 100000 MHz to 100000.001 MHz, there should be zero entry returned but the table is not updated accordingly. 

shall we also show a popup to warn users that the query results in 0 entry returned?

### PR DESCRIPTION
**Pull request by duidae**
closes #1063 #1064

### CODE REVIEW

**Comment by kswang1029** [comment]
weird error: I tried to query in mm but the frontend complains about the range is too wide in GHz...
Screen Shot 2020-07-28 at 3 21 44 PM

**Comment by duidae** [comment]
wavelength with .1 mm is surely over 10GHz

**Comment by kswang1029** [comment]
Uh right...🙈

**Review by kswang1029 — APPROVED** [review]
all looking good 👍

**Comment by duidae** [comment]
@kswang1029 refined message with wavelength range: 

**Frequency range is too wide. Please specify a frequency range within 10 GHz or wavelength range larger than 2.99792458 cm.**

**Comment by kswang1029** [comment]
@duidae the wavelength part is less clear. We also have center+range method. I suggest we explicitly mention the "frequency" coverage that users set after "Frequency range is too wide. Please specify a frequency range within 10 GHz."

**Comment by duidae** [comment]
@kswang1029  do you mean like this?

image

**Comment by kswang1029** [comment]
Yes, and show the values in ascent order (here it should be 1.1mm to 1mm but in frequency)

**Comment by duidae** [comment]
ok, refined
image

**Review by veggiesaurus — APPROVED** [review]

**Pull request merged**
