### PR TITLE
Angus/mip range icd change

### PR DESCRIPTION
**Pull request by veggiesaurus**
Companion PR of https://github.com/CARTAvis/carta-backend/pull/430

Allows loading of mip-mapped HDF5 files, in order to drastically reduce initial time to load. Below is an example of a 40K x 40K image loading off a normal hard drive

https://user-images.githubusercontent.com/592504/106865505-f46f4e80-66d3-11eb-9cce-fc0380370869.mp4

Requests cropped and mip-mapped spatial profiles while the cursor is not frozen. 

~~Note: smoothing currently seems to break things, I'll attempt to fix this soon.~~ Note: the entire image needs to be loaded in full-resolution when a contour is requested. #727 would help a lot with this.

HDF5 files with mipmapped datasets can be generated using the latest version of [fits2idia](https://github.com/idia-astro/fits2idia) (or ask @veggiesaurus for example files).

### CODE REVIEW

**Review by duidae — APPROVED** [review]

**Comment by kswang1029** [comment]
With the frontend: origin/angus/mip_range_icd_change 91f1352 and the backend origin/confluence/hdf5-mipmaps 165db40 , I see the full resolution spatial profiles got updated only when I press F to freeze the cursor movement, not automatically updated when cursor stops moving for a short time. Is it the intended behavior? That is, we only see full resolution profile when the state of the cursor is frozen.

https://user-images.githubusercontent.com/20819712/107332414-1bbc8600-6aef-11eb-809c-8ca2d077286e.mp4

I see the behavior is the same in FITS. This will cause usability issues.

**Comment by veggiesaurus** [comment]
> With the frontend: origin/angus/mip_range_icd_change [91f1352](https://github.com/CARTAvis/carta-frontend/commit/91f1352a4ffce2accff17fd67317a4034d361b8e) and the backend origin/confluence/hdf5-mipmaps 165db40 , I see the full resolution spatial profiles got updated only when I press F to freeze the cursor movement, not automatically updated when cursor stops moving for a short time. Is it the intended behavior? That is, we only see full resolution profile when the state of the cursor is frozen.

@kswang1029 this is fixed in `fb65497e` :slightly_smiling_face: Now it also shows the full profile when the cursor stops for 250 ms or more.

**Comment by kswang1029** [comment]
> @kswang1029 this is fixed in `fb65497e` 🙂 Now it also shows the full profile when the cursor stops for 250 ms or more.

Confirmed! Nice

**Comment by kswang1029** [comment]
@veggiesaurus do you think the following is an intended behavior? When the cursor is outside the image and moving, the spatial profiles are switched to the downsampled ones. Once the cursor stops moving, the profiles are switched back to the full resolution ones. In this case, we see identical profiles getting updated repeatedly along with the movement of the cursor in the empty area.
https://user-images.githubusercontent.com/20819712/116955227-82070e00-acc4-11eb-81b6-d7e74d285dbd.mp4

**Comment by kswang1029** [comment]
with regular FITS image, changing channel does not work and we see the image does not update accordingly. HDF5 works fine.
Screen Shot 2021-05-04 at 10 52 34 AM

**Comment by kswang1029** [comment]
I am also seeing the following warning from the console. 
Screen Shot 2021-05-04 at 11 00 00 AM
Screen Shot 2021-05-04 at 10 59 47 AM
Screen Shot 2021-05-04 at 10 59 27 AM

**Comment by kswang1029** [comment]
@veggiesaurus when testing https://github.com/CARTAvis/carta-backend/pull/430 I see that when we export a spatial profile to tsv format, it is the decimated profile being exported, not the full resolution one (it should be). This is independent of the image type (FITS or HDF5).
 Could you confirm this is the case?

**Comment by veggiesaurus** [comment]
> @veggiesaurus when testing [CARTAvis/carta-backend#430](https://github.com/CARTAvis/carta-backend/pull/430) I see that when we export a spatial profile to tsv format, it is the decimated profile being exported, not the full resolution one (it should be). This is independent of the image type (FITS or HDF5).
> Could you confirm this is the case?

@kswang1029 I can't reproduce this issue. Is it possible that the full resolution spatial profile is still being streamed?

**Comment by confluence** [comment]
If the image is HDF5, the profile can only be decimated if the file doesn't have any mipmaps. Otherwise a low-res HDF5 profile should be downsampled. (Although it shouldn't be in this case.)

**Comment by kswang1029** [comment]
@veggiesaurus could you try the s255 cube? Following is what I see from the tsv file when the frontend decimation is applied for visualization.

Screen Shot 2021-07-06 at 10 41 59 AM

If we maximize the spatial profiler and make a big enough browser window so that there is no frontend decimation, we will see the full resolution data in the tsv.

Screen Shot 2021-07-06 at 10 42 51 AM

**Pull request merged**
