### PR TITLE
#239 support point region

### PR DESCRIPTION
**Pull request by zarda**
Add support of point region type to parts of lists on #239 

- Toolbar to add region point
- Move on canvas
- Show on region list
- A box to show the selected point region
- Appearance for editing

### CODE REVIEW

**Comment by kswang1029** [comment]
Can we make the region highlighter to be more readable? Making it bigger perhaps?

Some style changes for the custom dialog:
Screen Shot 2019-07-09 at 18 28 25
It should be just "color" and the text format of wcs coordinate should be consistent with the other region types (cf rectangle).

**Comment by zarda** [comment]
Does the region point mean a coordinate which will map to the raw point intensity? It is a matter of if the front will acquire the intensity data from backend. Current region point "is closed" and performed as other regions, it it?

**Comment by veggiesaurus** [comment]
> Does the region point mean a coordinate which will map to the raw point intensity? It is a matter of if the front will acquire the intensity data from backend. Current region point "is closed" and performed as other regions, is it?

A point region is not closed in the sense that it can't be reduced to a single pixel using a specific stats type, since it already corresponds to only a single pixel. It should behave like any other region, in the sense that it can be used in the spectral profile widget to view the spectral profile, but it should not have the stats type enabled.

**Comment by kswang1029** [comment]
Could we use a simpler point selection indicator? Currently it looks quite blocky... 
Screen Shot 2019-07-11 at 3 30 55 PM

I see there is a circle inside a square. Could we just use the square in dashed/dotted line?
Screen Shot 2019-07-11 at 3 29 28 PM

**Comment by arusstaylor** [comment]
How about just a cross hair with the centre clear?


         |
    —   —
         |

Russ

**Comment by veggiesaurus** [comment]
agree we should change the symbol. However, it needs to be changed so that:
1) It's clear when the region is selected or deselected
2) It's clear that it's not the mouse cursor or region creation cursor

**Comment by kswang1029** [comment]
@zarda after checking with the science team members, the consensus is that we will just use anchors to indicate the a region is selected. Please remove the border in dashed line (except point region).

**Comment by veggiesaurus** [comment]
@zarda now that @pford has fixed point regions on the backend ([carta-backend/#279](https://github.com/CARTAvis/carta-backend/pull/279)), can you test your PR and confirm it's working?

**Comment by zarda** [comment]
The patch is tested well. This PR is ready.

**Comment by kswang1029** [comment]
@veggiesaurus sometimes I find it hard to click right on the point too. Is that because the "square" is rotated? Or the invisible clickable area is simply too small?

**Comment by kswang1029** [comment]
Can we have the "statistic" to "mean" to be the same as cursor?

**Comment by veggiesaurus** [comment]
> @veggiesaurus sometimes I find it hard to click right on the point too. Is that because the "square" is rotated (and why?)? Or the invisible clickable area is simply too small?

I think currently only the visible area is clickable.

**Comment by kswang1029** [comment]
> I think currently only the visible area is clickable.

Then perhaps we use square not diamond shape. Although the area is the same but I believe square is easier to click on.

**Pull request merged**
