### PR TITLE
Add NaN pixel color selection in render config overlay

### LINKED ISSUE #1946: configure NaN pixel color in the render config
user feedback from v3 beta testers

With the v3 release, the color for NaN pixel rendering can be configured in the preferences. This enhancement is to add the feature in the render config widget so that it is easier to adjust the NaN color for publications.

We can synchronize the NaN color state in the preferences and in the render config widget.

### PR DESCRIPTION
**Pull request by I-Chenn**
**Description**

This draft PR is to resolve #1946.

A `FormGroup` is added to `ColormapConfigComponent` to add a NaN pixel color selection to the `Render Configuration` overlay. The result is shown below:
[Screencast from 12-14-2022 10:14:37 AM.webm](https://user-images.githubusercontent.com/106953609/207488938-d2dcca49-d358-4819-afb7-6919476e995f.webm)

Would like to make sure with @kswang1029:
1. If this is the effect you would like to have for this issue?
2. If the position of the "NaN pixel color selection" is OK for you?

If it's all OK for Kuo-Song, then I will turn this draft into a formal one.

**Checklist**

For linked issues (if there are):
- [X] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [X] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [x] e2e test passing / corresponding fix added
- [X] changelog updated / ~no changelog update needed~
- [X] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] `BackendService` unchanged / `BackendService` changed and corresponding ICD test fix added

### CODE REVIEW

**Comment by kswang1029** [comment]
I would prefer to put the NaN color button below the bias/contrast button as it is less frequently used. And we dont need to use a wide button for the color I think once it is relocated.

Ideally I was thinking about integrating this NaN color button with the colormap dropdown but at the moment I am not sure what UI would provide a better UX.

**Comment by veggiesaurus** [comment]
> I would prefer to put the NaN color button below the bias/contrast button as it is less frequently used. And we dont need to use a wide button for the color I think once it is relocated.

I agree 👍

**Comment by I-Chenn** [comment]
Just commit the result of relocating the NaN color button, and I still need to configure the width of the button.

**Comment by I-Chenn** [comment]
@kswang1029, I have modified the position and the size of the button (shown below)
截圖 2022-12-21 下午6 54 29

As for the "integration" thing, would you like have a discussion with @YuHsuan-Hwang and me?

**Comment by kswang1029** [comment]
> @kswang1029, I have modified the position and the size of the button (shown below) 截圖 2022-12-21 下午6 54 29
> 
> As for the "integration" thing, would you like have a discussion with @YuHsuan-Hwang and me?

ok to have the UI as it is now.

**Comment by I-Chenn** [comment]
@kswang1029 OK, so may I turn this draft-PR into formal one (and perhaps update the changelog as well) and let Yu-Hsuan to merge the branch?

**Review by kswang1029 — APPROVED** [review]
this looks good. no regression is observed from e2e tests.

**Review by YuHsuan-Hwang — APPROVED** [review]

**Comment by YuHsuan-Hwang** [comment]
@I-Chenn Please update the change log, thanks.

**Comment by I-Chenn** [comment]
@YuHsuan-Hwang, the changelog is updated.

**Pull request merged**
